### ISSUE TITLE
Is it possible to inject presenter using Dagger instead of @InjectPresenter?

### ISSUE THREAD

**Issue by MasoodFallahpoor** [Arello-Mobile/Moxy#100]
Is it possible to inject the presenter using Dagger and @Inject instead of provided @InjectPresenter? From my experiments that's not possible.

**Comment by senneco** [comment]
@MasoodFallahpoor yes, it's. But then you should manually attach/detach view from prersenter and manage lifecycle of presenters.

Also, you can use both Moxy and Dagger =) Then you should write some like this:

```java
@Inject
Presenter daggerPresenter;

@InjectPresenter
Presenter moxyPresenter;

@ProvidePresenter
Presenter providePresenter() {
    return daggerPresetner;
}

@Override
public void onCreate(Bundle saveState) {
    Component.get().inject(this);
    super.onCreate();
    ....
```

Or

```java
@Inject
@InjectPresenter
Presenter presenter;

@ProvidePresenter
Presenter providePresenter() {
    return presetner;
}

@Override
public void onCreate(Bundle saveState) {
    Component.get().inject(this);
    super.onCreate();
    ....
```

**Comment by MasoodFallahpoor** [comment]
Thanks for your super quick response!

**Comment by alaershov** [comment]
@senneco In your second code sample, won't the presenter be injected by Dagger every time you call `Component.get().inject(this);` in `onCreate()`?

**Comment by A-Zaiats** [comment]
@alaershov you can move `Component.get().inject(this)` into the `providePresenter()` method.

**Comment by alaershov** [comment]
@A-Zaiats But then I won't be able to inject other dependencies into my activity, if it depends on something besides presenter.

Maybe it would be better to do this:

```java
@InjectPresenter
MyPresenter mPresenter;

@ProvidePresenter
MyPresenter providePresenter() {
    return mComponent.providePresenter();
}

@Override
public void onCreate(Bundle saveState) {
    mComponent = getComponent();
    mComponent.inject(this);
    super.onCreate();
    ...
```

It allows me to inject other dependencies to the activity, and does not reinject presenter on each recreate.

**Comment by alaershov** [comment]
@A-Zaiats But then I won't be able to inject other dependencies into my activity, if it depends on something besides presenter.

Maybe it would be better to do this:

```java
@InjectPresenter
MyPresenter mPresenter;

@ProvidePresenter
MyPresenter providePresenter() {
    return mComponent.providePresenter();
}

@Override
public void onCreate(Bundle saveState) {
    mComponent = getComponent();
    mComponent.inject(this);
    super.onCreate();
    ...
```

It allows me to inject other dependencies to the activity, and does not reinject presenter on each recreate.

**Comment by bejibx** [comment]
I'm doing it like this:
```java
@InjectPresenter
MyPresenter mPresenter;

@Inject
Provider<MyPresenter> presenterProvider;

@ProvidePresenter
MyPresenter providePresenter() {
    return presenterProvider.get();
}

@Override
public void onCreate(Bundle saveState) {
    mComponent = getComponent();
    mComponent.inject(this);
    super.onCreate();
    ...
```

**Comment by matzuk** [comment]
@alaershov about this example:
```java
@Inject
@InjectPresenter
Presenter presenter;

@ProvidePresenter
Presenter providePresenter() {
    return presetner;
}

@Override
public void onCreate(Bundle saveState) {
    Component.get().inject(this);
    super.onCreate();
    ....
```
If your Presenter was provided from Dagger with concrete Scope than there is only one instance of your Presenter and there is no cause for concern I think.

**Comment by alaershov** [comment]
@matzuk That's true, it's only a matter of taste. I find this example a bit confusing for beginners, but it's a nice puzzle for those who want to thoroughly understand the order of injections in Moxy+DI combo, as well as the essence of DI scopes.

**Comment by xanderblinov** [comment]
@alaershov with another DI framevork it looks more sweetly:

```kotlin
    @InjectPresenter
    internal lateinit var presenter: ProfilePresenter

    @ProvidePresenter
    fun providePresenter(): ProfilePresenter {
        return Toothpick.openScopes(DI.USER_SCOPE).getInstance(ProfilePresenter::class.java)
    }
```

**Comment by alaershov** [comment]
@xanderblinov Toothpick is definitely more user-friendly than Dagger :) However, your example does not inject the Activity/Fragment itself, and the more complete example could look like this: 
```kotlin
private val scope: Scope by lazy { Toothpick.openScopes(DI.USER_SCOPE) }

@Inject
internal lateinit var someStuff: SomeStuff

@InjectPresenter
internal lateinit var presenter: ProfilePresenter

@ProvidePresenter
fun providePresenter(): ProfilePresenter {
    return scope.getInstance(ProfilePresenter::class.java)
}

@Override
fun onCreate(...) {
    Toothpick.inject(this, scope);
    super.onCreate();
}
```

**Comment by matzuk** [comment]
@alaershov @xanderblinov 
Oh God, it's amazing!
But Toothpick is not DI =)

**Comment by Yazon2006** [comment]
Possible way of injection with Dagger. Initialization of presenter happening only when `providePresenter()` calls.
`	@Inject
	lateinit var daggerPresenter: Lazy<SomePresenter>
	
	@InjectPresenter
	lateinit var presenter: SomePresenter
	
	@ProvidePresenter()
	fun providePresenter(): SomePresenter = daggerPresenter.get()
`

**Comment by danilNikolaenko1990** [comment]
> @MasoodFallahpoor yes, it's. But then you should manually attach/detach view from prersenter and manage lifecycle of presenters.
> 
> Also, you can use both Moxy and Dagger =) Then you should write some like this:
> 
> ```java
> @Inject
> Presenter daggerPresenter;
> 
> @InjectPresenter
> Presenter moxyPresenter;
> 
> @ProvidePresenter
> Presenter providePresenter() {
>     return daggerPresetner;
> }
> 
> @Override
> public void onCreate(Bundle saveState) {
>     Component.get().inject(this);
>     super.onCreate();
>     ....
> ```
> 
> Or
> 
> ```java
> @Inject
> @InjectPresenter
> Presenter presenter;
> 
> @ProvidePresenter
> Presenter providePresenter() {
>     return presetner;
> }
> 
> @Override
> public void onCreate(Bundle saveState) {
>     Component.get().inject(this);
>     super.onCreate();
>     ....
> ```



> I'm doing it like this:
> 
> ```java
> @InjectPresenter
> MyPresenter mPresenter;
> 
> @Inject
> Provider<MyPresenter> presenterProvider;
> 
> @ProvidePresenter
> MyPresenter providePresenter() {
>     return presenterProvider.get();
> }
> 
> @Override
> public void onCreate(Bundle saveState) {
>     mComponent = getComponent();
>     mComponent.inject(this);
>     super.onCreate();
>     ...
> ```

in my case it doesn't worked out. I see in debugger, that dagger presenter was injected, but when calls providePresenter daggerPresetner is null. It seems like  ProvidePresenter fulfills BEFORE @inject fulfils. What could be cause of problem? thanks. Sorry for my english

**Comment by alaershov** [comment]
@danilNikolaenko1990 Hi there! Moxy has migrated to a [new repository](https://github.com/moxy-community/Moxy). This repository is deprecated and no longer maintained. You're welcome to open a new issue in the new repository, but if you only need some advice - welcome to our [Telegram group](https://t.me/moxy_ru)! Feel free to ask any questions about Moxy there.

**Comment by danilNikolaenko1990** [comment]
> @danilNikolaenko1990 Hi there! Moxy has migrated to a [new repository](https://github.com/moxy-community/Moxy). This repository is deprecated and no longer maintained. You're welcome to open a new issue in the new repository, but if you only need some advice - welcome to our [Telegram group](https://t.me/moxy_ru)! Feel free to ask any questions about Moxy there.

thanks!
