### ISSUE TITLE
Improve delegating child views

### ISSUE THREAD

**Issue by morder** [Arello-Mobile/Moxy#105]
Было бы хорошо, при подключении зависимых(child) делегатов, повторять выполненные методы
onCreate и onAttach родителя, чтобы child также был в состоянии, в каком состоянии находится родитель.

Например, если мы динамически добавляем некую view, которая содержит MvpDelegate и к этому делегату мы применяем setParentDelegate, то не сработает ни onCreate, ни onAttach.
onCreate конечно можно дернуть сразу после setParentDelegate, но вот onAttach нужно дергать только в том случае если у родительского делегата был вызван onAttach.
У MvpDelegate сейчас есть поле mIsAttached но оно private и нет метода для получения ее значения.

Возможно стоить подумать над неким общим решением для того чтобы зависимые делегаты находились в том же состоянии что и родитель.

**Comment by senneco** [comment]
А почему обязательно дожидаться, пока родительский делегат не вызовет onAttach? Если тот, кто создал дочерний делегат, готов принимать команды из презентера, пусть аттачится

**Comment by senneco** [comment]
@morder если будут мысли, то можно переоткрыть задачу ;)
