### ISSUE TITLE
Missing DaggerAppComponent.java in sample-github

### ISSUE THREAD

**Issue by zTrap** [Arello-Mobile/Moxy#107]
Огромное спасибо за великолепную библиотеку и отличный пример её реализации.

Может, конечно, так и было задумано, но отсутствует файл `DaggerAppComponent.java` который должен располагаться по пути `com.arellomobile.mvp.sample.github.di.DaggerAppComponent`.

Если это и было задумано - объясните пожалуйста его функционал, а если нет - добавьте его, пожалуйста, в репозиторий. Для меня это критично так как знакомлюсь с Dagger и с Moxy используя ваш пример. =)

**Comment by senneco** [comment]
Этот класс будет сгенерирован даггером, после первого билда проекта. Так что для начала просто соберите проект ;)

**Comment by zTrap** [comment]
Да, спасибо, это решило проблему =)
