### ISSUE TITLE
Presenter's onDestroy not called when app killed

### ISSUE THREAD

**Issue by Dedoxyribose** [Arello-Mobile/Moxy#108]
Добрый день.
Заметил, что если сворачиваю приложение, а потом "смахиваю" вручную из списка - onDestroy в Presenter'е не вызывается. Так и должно быть?

Если выйти через кнопку back - всё нормально, вызов есть.

**Comment by Dedoxyribose** [comment]
И сразу ещё один баг, даже более важный.
Если приложение выгружено из памяти системой (при нехватке памяти), то при попытке его открыть снова (при этом система пытается восстановить старые активити) у Presenter'а не вызывается onFirstViewAttach. Но при этом все поля в Presenter потеряны. Т.е. если в onFirstViewAttach происходит какая-то инициализация полей, то здесь её не произойдёт и в итоге всё падает. 
Есть какой-то workaround на этот счёт?

**Comment by senneco** [comment]
1. В Андроиде нет каллбэка, что прочесс уничтожается. Так же onDestroy у активити не вызывается. Поэтому мы не можем определить, что нам пора бы вызвать presenter.onDestroy

2. Ни разу такого поведения не наблюдал. Всегда наблюдал, что если процесс уничтожен, то потом presenter ведёт себя, как будто он только-только создан. Потому что так и есть -- презнтер только-только создаётся, и к нему ещё ни одна View не аттачилась.

**Comment by Dedoxyribose** [comment]
1. Понял
2. На всякий случай ещё раз уточню, что имеется в виду не уничтожение процесса вручную, а когда система вырубает при нехватке памяти. 
Лично я сейчас воспроизвожу это через:
свернуть (home button) -> открыть настройки телефона -> для разработчиков -> работающие приложения ->найти приложение и "Остановить".

P.S. А в остальном очень классная библиотека, хочется выразить вам благодарность, авторы.

**Comment by senneco** [comment]
Нет разницы, каким образом умер процесс. Если процесс умирает, то умирает все объекты, и презентеры, подавно =) Т.е. в плане жизни презнетера, для него без разницы, это первый запуск прилоежние, или воссоздание приложения после остановки процесса - презентер всё равно будет создан новый

**Comment by Dedoxyribose** [comment]
Понял в чём дело.
onFirstViewAttach вызывается, но при таком сценарии - вызывается позже, чем некоторые колбэки у вьюшек Активити (а обычно наоборот), ещё не понял почему, но разберусь.
Таким образом, косяк мой, проблема закрыта =)
