### ISSUE TITLE
Не сохраняется состояние

### ISSUE THREAD

**Issue by pasha656** [Arello-Mobile/Moxy#11]
Обновился с версии 0.5.2 -> 0.5.4 ViewState перестало сохранять свое состояние. 

Например: Есть метод который показывает диалоговое окно @StateStrategyType(AddToEndSingleStrategy.class)
void showLoadingDialog();

при перевороте экрана, диалог не показывается, а на 0.5.2. - показывается

**Comment by CherryPerry** [comment]
В 0.5.3 обновились базовый fragment и activity. Вы их обновили?
[MvpActivity](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-android/src/main/java/com/arellomobile/mvp/MvpActivity.java)

**Comment by pasha656** [comment]
Обновил [MvpActivity](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-android/src/main/java/com/arellomobile/mvp/MvpActivity.java), и [MvpFragment ](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-android/src/main/java/com/arellomobile/mvp/MvpFragment.java) ошибка пропала.

Могли бы вы вести https://github.com/Arello-Mobile/Moxy/issues/9 - было бы удобно отлеживать изменения.

**Comment by senneco** [comment]
@pasha656 а [в таком](https://github.com/Arello-Mobile/Moxy/releases) виде вам не удобно отслеживать изменения? Для некоторых апдейтов я забыл указать ченджи. Но благо в них не было ничего критичного =)

**Comment by pasha656** [comment]
Прошу прощения. Совсем забыл про эту вкладку =(
