### ISSUE TITLE
Приложение не восстанавливает состояние после выгрузки из памяти.

### ISSUE THREAD

**Issue by uncledoc** [Arello-Mobile/Moxy#118]
По мотивам этого поста https://github.com/Arello-Mobile/Moxy/issues/108
Дело в том что товарищ **Dedoxyribose** прав, если запустить приложение после того как ОС выгрузила его из памяти то состояние Activity не восстановится.
Как мне видится проблема в том что у вас команды для view "висят" закешированными в памяти и когда процесс прибивается то эти команды неоткуда восстановить. 
Как вариант предлагаю сделать следующее чтобы решить эту проблему:
1. Все формальные аргументы функций которые расширяют интерфейс MvpView должны наследовать интерфейс Serializable или попросту быть сериализуемыми.
2. Сделать отображение сериализуемых команд из памяти на внутреннюю память устройства
....
4. PROFIT!!!

или может быть у вас есть другое решение этой проблемы?

**Comment by senneco** [comment]
Да, и это сделано специально. Потому что таким образом можно случайно сериализовать команду showProgress, хотя презентер ничего не начнёт делать после рестарта процесса. Опять же, если он из коробки начнёт что-то делать, то может сделать не то, что надо -- например, запостить комментарий ещё раз. Поэтому, если сильно хочется, то можно самому сохранить всё в бандл. Но тогда корректней сохранять состояние презентера, а не вью. Поэтому, можете делать так:

1. прокидывать onSaveInstanceState в презентер
2. в презентере сохранять нужное состояние в пришедший бандл
3. в onCreate брать бандл и передавать его в презентер(если презнтера ещё нет) и делать то, что нужно лично вам

**Comment by terrakok** [comment]
Стейт должна сохранять модель, а не презентер.

**Comment by senneco** [comment]
@terrakok да, да, точно, именно так. Тут я хотел больше сделать акцент, что можно сохранить состояние в бандле сэйв стейта. Хотя можно сохранить его хоть где, хоть как, и хоть когда :D главное, что всегда самостоятельно

**Comment by uncledoc** [comment]
Согласен. 
Но для простых действий можно было бы и добавить, например через какой-то интерфейс MvpViewSerializable или сделать функцию getViewStateSerializable, установка там переключателей, текстовых полей, картинок и т.д. и использовать это дело осознанно. Как по мне, то сохранение состояния это килер-фича данного фреймворка, но без этого ценность немного нивелируется, допустим можно использовать девайс Samsung galaxy s3 mini и ловить то что я описал практически постоянно.

**Comment by terrakok** [comment]
Такие вещи нельзя делать в библиотеках, так как их начнут использовать не по назначению
Да и сделать это правильно и надежно гораздо сложнее чем кажется

**Comment by jeksor** [comment]
Можно сделать отдельную dependency, в которой реализовать необходимый
инструментарий. Так же как есть moxy-android, moxy-compiler.

**Comment by uncledoc** [comment]
та можно сделать все что угодно, было бы желание (:
