### ISSUE TITLE
Фрагменты и isInRestoreState

### ISSUE THREAD

**Issue by AlexSoft22** [Arello-Mobile/Moxy#119]
Добрый день, столкнулся с непонятным поведением isInRestoreState для фрагментов, просматривая 
https://github.com/senneco/MoxyCases (Case5)  версию изменил на последнюю 1.5.2
добавил для проверки состояния презентера вывод  значения функции

`
@Override
public void showCount(int count)  {
	Log.d(TAG," mCounterPresenter.isInRestoreState="+mCounterPresenter.isInRestoreState(this));
	mCounterTextView.setText(String.valueOf(count));
}
`

При первом  старте получаю True, но это же не восстановленное состояние (переворота экрана не было). После нажатия кнопки изменения счетчика возвращается False. 
Почему?

**Comment by senneco** [comment]
Такое поведение получается потому, что `getViewState().showCount(mCount);` вызывается из конструктора Presenter. А это значит, что ещё не приаттаченна View. Значит, команда складывается в очередь команд. Затем аттачится первая View. И для неё восстанавливается состояние → isInRestoreState == true

**Comment by AlexSoft22** [comment]
Правильно, ли будет в таком случае перенести вызов showCount(mCount) в onFirstViewAttach()?
Проверил - работает.

**Comment by senneco** [comment]
Если это критично, то да, это будет правильное решение

**Comment by AlexSoft22** [comment]
Критично только для понимания текущего состояния презентера для принятия решения после воспроизведения очереди команд из ViewState (анимация и прочее). Если я правильно понимаю, то есть два основных механизма - StateStrategy и isInRestoreState.

**Comment by senneco** [comment]
Для управления тем, делать анимацию или нет -- только `isInRestoreState`. Стратегии не о том ;)
