### ISSUE TITLE
View for Presenter is not found if they are in different modules

### ISSUE THREAD

**Issue by ynlvko** [Arello-Mobile/Moxy#120]
The case is: there are 2 app modules for Tablets and Phone, which contains Fragments that implements Views, and another one module with shared code, in which I wanted to put Presenters. In this case I got compile time error:
`Error:Moxy compilation failed; see the compiler error output for details (java.lang.IllegalArgumentException: View "com.example.shared.Contract$View" for com.example.shared.Presenter cannot be found)`

**Comment by senneco** [comment]
Resolved in Moxy 1.5.3
