### ISSUE TITLE
Always need to do Clean Project

### ISSUE THREAD

**Issue by sanyok7734** [Arello-Mobile/Moxy#122]
Здравствуйте. Решил попробовать Moxy взял ваш код с презентации и написал на kotlin. Но вот беда появилась ошибка 

>    kotlin.UninitializedPropertyAccessException: lateinit property counterPresenter has not been initialized

делаю Clean Project и нормально, потом делаю изменения в коде и опять ошибка пока не сделаю Clean Project.
```
@InjectViewState
class CounterPresenter : MvpPresenter<CounterView>() {

    var count: Int = 0

    init {
        viewState.showView(count)
    }

    fun onPlusClick() {
        count++
        viewState.showView(count)
    }
}
```
```

interface CounterView : MvpView {
    fun showView(count: Int)
}
```

```
class CounterFragment : MvpAppCompatFragment(), CounterView {

    @InjectPresenter
    lateinit var counterPresenter: CounterPresenter

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater?.inflate(R.layout.fragment, container, false)
    }

    override fun onViewCreated(view: View?, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        parentView.setBackgroundColor(arguments.getInt("color", 0))

        button.setOnClickListener {
            countPlus()
        }
    }

    fun countPlus() {
        counterPresenter.onPlusClick()
    }
    
    override fun showView(count: Int) {
        textCounter.text = "$count"
    }
}
```
```

    compile 'com.arello-mobile:moxy:1.5.3'
    compile 'com.arello-mobile:moxy-android:1.5.3'
    compile 'com.arello-mobile:moxy-app-compat:1.5.3'
    kapt 'com.arello-mobile:moxy-compiler:1.5.3'
```

**Comment by sanyok7734** [comment]
Забыл добавить apply plugin: 'kotlin-kapt'
после добавления эта ошибка но так же решаеться 
![image](https://cloud.githubusercontent.com/assets/5102102/26558808/30a96c00-44b4-11e7-94fe-61c680fddcb1.png)

**Comment by evstep** [comment]
@sanyok7734, эта проблема вроде только в 3.0 сanary.

**Comment by sanyok7734** [comment]
Но, у меня 2.3.2 стабильная. Ну ладно буду пробывать разбираться

**Comment by jeksor** [comment]
Александр, подтверждаю, сталкивался с такой же проблемой на 2.3. К
сожалению, решения адекватного ещё нет.

**Comment by senneco** [comment]
@xanderblinov не знаешь, в чём может быть проблема? Ты же на котлине фулл тайм фигачишь =)

**Comment by ekursakov** [comment]
Тоже есть такая проблема, периодически (иногда через раз) при запуске вылазит ошибка с PresentersBinder, помогает еще раз запустить приложение, даже без очистки.

**Comment by limelightG** [comment]
+1

**Comment by abbath0767** [comment]
Возникает аналогичная проблема. AS3 Canary 1 gradle-plugin 3-alpha1

**Comment by senneco** [comment]
@ekursakov так у тебя похоже проблема из-за того, что несколько модулей? Я даже не знаю, чем тут помочь, особенно с учётом, что мульти-модульность появилась из-за твоего пулл реквеста =)

**Comment by xanderblinov** [comment]
Поставьте gradle 3.5 и tools 2.3.1

**Comment by jeksor** [comment]
Это не решает проблему.

**Comment by evstep** [comment]
Решения так и нет?

**Comment by senneco** [comment]
@evstep так и не получается получить такую же проблему =( А вы пробовали взять сэмпл? С ним такие же проблемы?

**Comment by evstep** [comment]
@senneco сегодня проверю, отпишусь

**Comment by senneco** [comment]
@ekursakov @sanyok7734 @evstep @frozzyk @limelightG @abbath0767 некоторым помогает убрать `apply plugin: 'kotlin-kapt'` – вы можете у себя попробовать так сделать? + добавить 

```groovy
kapt {
    generateStubs = true
}
```

**Comment by frozzyk** [comment]
@senneco у меня без `аpply plugin: 'kotlin-kapt'` Room не работает

**Comment by abbath0767** [comment]
@senneco apply plugin: 'kotlin-kapt' убрал давно, с новым грейдлом. Строку что просишь добавить - уже добавлена. Но подозреваю что были проблемы в грейдле/капте так как с последними версиями я данную проблему не встречал

**Comment by xanderblinov** [comment]
Проблема в kapt. К сожалению, он нестабилен.
