### ISSUE TITLE
@ProvidePresenter работает только для той имплементации View, где есть этот метод

### ISSUE THREAD

**Issue by AudasViator** [Arello-Mobile/Moxy#123]
Имеются две вьюхи, которые implements один и тот же интерфейс, но в одной из них есть @ProvidePresenter, а в другой нет. Везде type = GLOBAL, теги нигде не указаны

Если сначала создастся та вьюха, где есть @ProvidePresenter, то во вторую Moxy его заинжектит
Если сначала создастся та вьюха, где нет этого метода, то всё упадёт из-за того, что презентер брать неоткуда (внутри Moxy его нет, нет и @ProvidePresenter в этой имплементации View)

Ожидалось, что если хоть в одной вьюхе есть метод @ProvidePresenter, то и для остальных он будет доступен и будет поставлять презентер, не зависимо от порядка их создания

Баг или фича? =)

**Comment by terrakok** [comment]
Все так и должно работать. @providepresenter берется у той вью для которой понадобился презентер, а не где-то еще.
А вообще не используйте GLOBAL презентеры. Сам автор библиотеки уже отказался от них. Это нарушение MVP подхода, и они совсем не нужны.
Есть вероятность, что в мажорных обновлениях Moxy останутся только нормальные презентеры.
