### ISSUE TITLE
Проблема сохранения позиции скролла при аттаче к глобальному презентеру

### ISSUE THREAD

**Issue by Demin92** [Arello-Mobile/Moxy#126]
Всем привет!
Столкнулся со следующей проблемой. Есть Presenter для экрана со списком акций
@InjectViewState
public class ActionsPresenter extends MvpPresenter<IActionsView>
Который загружает и отображает данные при первом аттаче:
@Override
    protected void onFirstViewAttach() {
        super.onFirstViewAttach();
        model.getActions().subscribe(new Subscriber<ArrayList<Action>>() {
            @Override
            public void onCompleted() {
            }

            @Override
            public void onError(Throwable e) {
            }

            @Override
            public void onNext(ArrayList<Action> actionsResponse) {
                getViewState().showData(actionsResponse);
            }
        });
    }
Во фрагменте Presenter помечен как глобальный:
@InjectPresenter(type = PresenterType.GLOBAL, presenterId = "ActionsPresenter")
ActionsPresenter actionsPresenter;
При этом при пересоздании Активити позиция скролла сохраняется, но если добавить новый ActionFragment вместо текущего
getSupportFragmentManager().beginTransaction().replace(R.id.container, new ActionsFragment()).commitAllowingStateLoss(); , то изменения применятся, но позиция скролла не сохранится. Почему так происходит и как сохранить позицию скролла?
Спасибо!

**Comment by senneco** [comment]
Android из коробки сам хорошо сохраняет такие примитивные параметры View, как позиция скролла. Но т.к. вы запихиваете новый фрагмент, Android и не считает нужным проскроллить на нужную позицию.

Какие выходы я вижу:
1. Не реплейсить фрагмент(зачем вам это после пересоздания активити?)
2. Прогонять позицию спролла через презентер. Т.е. в onSaveInstanceState сообщаете в презентер текущую позицию скролла, а затем отправляете во ViewState команду со скроллом на требуемое место. Тогда когда новая View приаттачится, она будет перемотанна на новую позицию. Но зачем вам это? И глобальные презентеры -- зло %)

**Comment by Demin92** [comment]
У меня есть требование по хитрому сохранению стеков фрагментов, которое приходится реализовывать вручную.При этом не хочется хранить фрагменты в памяти, а вместо этого хранить соотв презенторы. И когда нужно будет показать какой-либо фрагмент показанный ранее, создавать его и аттачить. И таким образом обеспечить тот же вид фрагмента, что и до его реплейса.

**Comment by senneco** [comment]
Раз вы снимаете эту обязанность с Android SDK, значит придётся делать самостоятельно, через Presenter-ViewState

**Comment by Demin92** [comment]
Понятно, спасибо.
