### ISSUE TITLE
Multiple presenters (Question)

### ISSUE THREAD

**Issue by Onregs** [Arello-Mobile/Moxy#130]
Hello,

For example, I have two presenters and each of them shows progress and starts performs an async operation. So, I would like to hide progress when the last operation will be ended. Both presenters are injected in one activity. How can I resolve this?

Thanks

**Comment by senneco** [comment]
Hi,

Well, I recommend to you create different view-methods like `finishLoadingPresenter1` and `finishLoadingPresenter2`. And then inside your activity you can join calls of these methods and then hide progress (when both methodes will be called).

**Comment by jeksor** [comment]
Hi,

Presenters are using the same View interface?
Give more details please. What the logic of this screen? Why you split
logic between two presenters?
Maybe you need to rethink this part of your app?)

**Comment by Onregs** [comment]
The main idea is to create presenters that can provide specific data and can be reused in different screens.   But it seems difficult to manage. Handle it in activity is a good idea to resolve it, but I think it will be anti-mvp approach. I think I have to rethink this part.
