### ISSUE TITLE
Presenter didn't created

### ISSUE THREAD

**Issue by september669** [Arello-Mobile/Moxy#133]
[SourceAndGradle.zip](https://github.com/Arello-Mobile/Moxy/files/1118204/SourceAndGradle.zip)

Uses annotationProcessor and last version of Moxy. 
I tried to cleanUp project, but presenter didn't created anyway.

**Comment by ekursakov** [comment]
Hi!
You need to subclass your activity from MvpAppCompatActivity or manually call MvpDelegate callbacks.

**Comment by september669** [comment]
Hi!
Thanks a lot!
