### ISSUE TITLE
Modules' MoxyReflector cannot be generated

### ISSUE THREAD

**Issue by ccyfly** [Arello-Mobile/Moxy#134]
/app/build/generated/source/apt/debug/com/arellomobile/mvp/MoxyReflector.java
Error:(66, 59) error: cannot find symbol class MoxyReflector

The line in class MoxyReflector show below code with red underline.
sViewStateProviders.putAll({My ReflectorPackage}.MoxyReflector.getViewStateProviders());
sPresenterBinders.putAll({My ReflectorPackage}.MoxyReflector.getPresenterBinders());
sStrategies.putAll({My ReflectorPackage}.MoxyReflector.getStrategies());

**Comment by senneco** [comment]
Всмысле не может найти класс {My ReflectorPackage}.MoxyReflector ? А он точно есть и доступен из этого места?

**Comment by ccyfly** [comment]
It cannot find class {My ReflectorPackage}.MoxyReflector.
And I followed this [guide](https://github.com/Arello-Mobile/Moxy/wiki/Multiple-modules).

I added code in library gradle
```
javaCompileOptions {
    annotationProcessorOptions {
        arguments = [ moxyReflectorPackage : 'com.test.mylibrary' ]
    }
}
```

In app module, I add code below on my Application class
```
@RegisterMoxyReflectorPackages({"com.test.mylibrary"})
```

While I run this app, it would show "error: cannot find symbol class MoxyReflector"
```
sViewStateProviders.putAll(com.test.mylibrary.MoxyReflector.getViewStateProviders());
sPresenterBinders.putAll(com.test.mylibrary.MoxyReflector.getPresenterBinders());
sStrategies.putAll(com.test.mylibrary.MoxyReflector.getStrategies());
```

**Comment by senneco** [comment]
@ekursakov could you help there?

**Comment by ekursakov** [comment]
Hi, there is few thoughts about why it can happen:
1. Is library module added to application dependencies?
1. Is `annotationProcessor 'com.arello-mobile:moxy-compiler:1.5.3'` dependency added in both modules?
1. Is MoxyReflector in library module generated? It should be in folder like `<library module>/build/generated/source/apt/debug/<reflector package>/`
1. If not:
    1. Are Moxy annotations used in this library? 
    1. If Kotlin is used, you need to use `kapt` instead of `annotationProcessor`, because `annotationProcessor` don't process Kotlin files.

**Comment by ccyfly** [comment]
@ekursakov 
1) yes
2) yes
3) no
4i) no, 
in my library, I create own base view and presenter only. And implement those base view/presenter in app module. 
ii) my project is not using Kotlin

**Comment by ekursakov** [comment]
Yes, if Moxy annotations (`@InjectViewState`, `@InjectPresenter`, ...) not used in module, annotation processor from `moxy-compiler` will not be called at build time so it can't generate MoxyReflector file.
In this case you do not need to register library module at all (remove this module package from `@RegisterMoxyReflectorPackages` annotation).

**Comment by ccyfly** [comment]
@ekursakov 
It works now. 
The issue may be closed. 

Thank you for helping me.

**Comment by RashidMalikov** [comment]
У меня причиной была в отсутствии
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by AlexanderKudinov** [comment]
В моем случае ошибка была из-за названия пакета, должно начинаться с маленькой буквы.
