### ISSUE TITLE
Как пересоздать презентер при изменении данных

### ISSUE THREAD

**Issue by LionZXY** [Arello-Mobile/Moxy#136]
У меня есть проинициализированная полностью активити и фрагмент.
Как можно переинициализировать презентер, чтобы он создался новый, с новыми данными?

Заранее спасибо за ответ :)

**Comment by atkdev** [comment]
Это нарушает идею mvp. Если нужно обновить данные, то это делает presenter. После обновления данных presenter передает их во view. Обновление данных происходит либо по запросу view на действие пользователя, либо по какой-то внутренней логике presenter.
