### ISSUE TITLE
Clearing Command Queue

### ISSUE THREAD

**Issue by Arash-gm** [Arello-Mobile/Moxy#138]
first of all thx for your great effort , my problem is with command strategy , maybe i didn't understand that well and i think the wiki is a bit unclear, the problem is when i navigate from one activity to another with a command, if i go back to first activity , if i rotate the app , the last command which is navigate to second activity execute again which is wrong, what is the best way to handle that? (as a user request, please communicate on issues in english(on other issues) )

**Comment by senneco** [comment]
Just apply `@StateStrategyType(OneExecutionStateStrategy.class)` to this command =) Then this command will be removed from queue after first apply.

**Comment by Arash-gm** [comment]
@senneco Thanks
