### ISSUE TITLE
ProGuard rules

### ISSUE THREAD

**Issue by garmax1** [Arello-Mobile/Moxy#14]
I can't find any proguard rules for moxy. I use moxy 0.5.4 and after building with proguard @InjectPresenter returns null.
With this line `-keep class * extends com.arellomobile.mvp.PresenterBinder` it works. Does moxy need any additional rules?

**Comment by garmax1** [comment]
And @InjectViewState works with
-keep class * extends com.arellomobile.mvp.MvpPresenter
-keep class * extends com.arellomobile.mvp.viewstate.MvpViewState
-keep class * extends com.arellomobile.mvp.ViewStateClassNameProvider
-keep interface * extends com.arellomobile.mvp.MvpView

It's not good to exclude presenter with business logic from proguard

**Comment by senneco** [comment]
Ready! =)
```
-keep class **$$PresentersBinder
-keep class **$$State
-keep class **$$ParamsHolder
-keep class **$$ViewStateClassNameProvider
-keepnames class * extends com.arellomobile.mvp.*
```
