### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by MrKrivorotoff** [Arello-Mobile/Moxy#142]
Пожалуйста, добавьте полноценные javadoc описания открытым классам и методам.

**Comment by zTrap** [comment]
@MrKrivorotoff вся документация присутствует. Возможно у вас есть уведомление о возможности подгрузки доков при просмотре исходного кода. Если оно есть, то необходимо загрузить документацию, кликнув `Download`

**Comment by xanderblinov** [comment]
@MrKrivorotoff получилось открыть документацию? В случае, если возникнут проблемы можете за оперативной консультацией обращаться в [telegram чат Moxy ](https://t.me/moxy_ru)
