### ISSUE TITLE
AddToEndSingleStrategy отрабатывает 2 раза при пересоздании фрагмента.

### ISSUE THREAD

**Issue by Troyanskii** [Arello-Mobile/Moxy#145]
Опишу все компоненты так как возможно я где то допустил ошибку и проблема в "пилоте".
Есть вью:

public interface AppMapFragmentView extends MvpView {
    @StateStrategyType(AddToEndSingleStrategy.class)
    void onMarkerClick(MapPoint mapPoint);
}

есть презентер:

@InjectViewState
public class AppMapFragmentPresenter extends MvpPresenter<AppMapFragmentView>{
    public void onMarkerClick(int position) {
        getViewState().onMarkerClick(pointsResult.get(position));
        isPointSelected = true;
    }
}

Вот так я делаю инжект презертера и использую его:

    @InjectPresenter(type = PresenterType.GLOBAL)
    AppMapFragmentPresenter mapFragmentPresenter;

    @Override
    public boolean onMarkerClickListener(Marker marker) {
        mapFragmentPresenter.onMarkerClick((int)marker.getTag());
        return true;
    }

    @Override
    public void onMarkerClick(MapPoint mapPoint) {
        pointTitle.setText(mapPoint.getTitle());
        pointDescription.setText(mapPoint.getDescription());
    }

Проблема в том что когда меняешь ориентацию и фрагмент пересоздается, метод apply с onMarkerClick дважды(соответственно и в фрагменте отрабатывает дважды) не смотря на то что он отмечен как @StateStrategyType(AddToEndSingleStrategy.class). Это баг или возможно я что-то делаю не так? Такая же картина и с остальными методами.

**Comment by senneco** [comment]
Советую продебажить и посмотреть, откуда прилетает второй вызов `onMarkerClick`

**Comment by senneco** [comment]
Если проблема не решилась, то можете переоткрыть задачу и дать новые данные
