### ISSUE TITLE
Multiple inheritance

### ISSUE THREAD

**Issue by YaDaniil** [Arello-Mobile/Moxy#146]
What should I do if I want my activity to extend MvpAppCompatActivity() and another activity from lib simultaneously? Is it turns out that I can't use Moxy if an activity is already extended from another one?

**Comment by senneco** [comment]
You have ability to manually call MvpDelegate methods. Just call those at that time as they are called by MvpAppCompatActivity.

**Comment by YaDaniil** [comment]
Thanks. Is there any example to avoid reading the whole doc?

**Comment by senneco** [comment]
[There](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-app-compat/src/main/java/com/arellomobile/mvp/MvpAppCompatActivity.java) are the best doc 😃 Just copy-paste

**Comment by YaDaniil** [comment]
Thanks)
