### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by idanbar134** [Arello-Mobile/Moxy#15]
How to use this awesome library on recycleview adapter?

**Comment by garmax1** [comment]
look at sample https://github.com/Arello-Mobile/MoxySample

**Comment by idanbar134** [comment]
I looked before I posted, he use ListView

**Comment by jeksor** [comment]
What exactly issue with RecyclerView in your case?
RecyclerView much like a ListView, just more powerful.

**Comment by senneco** [comment]
@idanbar134 if you need more samples, you could open issues in [sample repo](https://github.com/Arello-Mobile/MoxySample).
