### ISSUE TITLE
Наследование от имплементаций MvpView и приватность.

### ISSUE THREAD

**Issue by CeH9** [Arello-Mobile/Moxy#152]
Прежде всего, спасибо за ваш огромный труд, проделанный при создании этой библиотеки.

**Предложение:** 
Пометить приватные поля имплементаций MvpView как **protected**.

**Причина:** 
Недавно был кейс с ViewPager, в котором нужно было создать свою версию [MvpAppCompatFragment-a](https://github.com/Arello-Mobile/Moxy/blob/cbf6b911d51f7a9125e4879576c3ffb8833b5135/moxy-app-compat/src/main/java/com/arellomobile/mvp/MvpAppCompatFragment.java) и и добавить пару методов типа:

``` java
@Override
public void onShowPage() {
	mIsStateSaved = false;
	getMvpDelegate().onAttach();
}
```

Можно было бы унаследоваться от фрагмента из библиотеки, но **mIsStateSaved**  приватный. Пришлось целиком копипастнуть класс. Вроде не страшно, но с новыми версиями появляются всякие фиксы багов например:  [такой](https://github.com/Arello-Mobile/Moxy/blob/cbf6b911d51f7a9125e4879576c3ffb8833b5135/moxy-app-compat/src/main/java/com/arellomobile/mvp/MvpAppCompatFragment.java#L84-L90). С наследование о таком можно будет не париться. 

P.S. из приватного встречал только поля, но это можно отнести и к важным приватным методам, если таковые имеются.

**Comment by xanderblinov** [comment]
Добрый день, @CeH9 открытые для редактирования потомкам филды бизнес логики могут привести к непредсказуемому поведению, тем более при смене внутренней логики. Также открывая внутреннюю логику класса мы теряем возможность менять её в дальнейшем. В вашем случае рекомендую делать отдельную реализацию и следить за разделом [Changelog](https://github.com/Arello-Mobile/Moxy/releases)
