### ISSUE TITLE
How to handle animation in Moxy?

### ISSUE THREAD

**Issue by Buckstabue** [Arello-Mobile/Moxy#153]
I have  show***() methods in a View interface. How should I disable animation when the view is reattached?

**Comment by defaultbr** [comment]
without some more information(code)

i can suggest to add above method at MvpView Interface
```
    @StateStrategyType(SkipStrategy  ::class)
```
```

public interface myCustomActivityInterface  {

 @StateStrategyType(SkipStrategy.class)
public showButtonAnimated()

}
```

so it will only run once and will not run again when you rotate

**Comment by senneco** [comment]
Presenter has method [isInRestoreState](https://github.com/Arello-Mobile/Moxy/blob/master/moxy/src/main/java/com/arellomobile/mvp/MvpPresenter.java#L111). It can help you to determine, why these method show****() was called.

**Comment by Buckstabue** [comment]
@senneco much thanks! So before animation is started I can check in my Fragment/Activity/View whether I'm restoring state? Cool. I wonder why this method is not defined in BaseMvpFragment class or in the MvpDelegate

**Comment by xanderblinov** [comment]
@Buckstabue cause view may contains several presenters, so it's impossible to add this method to BaseMvpFragment class or to the MvpDelegate.

You a right, non void methods of presenters are evil, so this a special lifecycle method.

**Comment by Buckstabue** [comment]
@xanderblinov how can a view have more than one presenter? How can it be useful?

**Comment by senneco** [comment]
@Buckstabue just inject two or more presenters in your View implementation. Also, implemet all required View interfaces ;)

It mays be usesull if you have big activity/fragment with many different responsibilities
