### ISSUE TITLE
Стратегия по умолчанию

### ISSUE THREAD

**Issue by OsipXD** [Arello-Mobile/Moxy#154]
Доброго времени суток.

Возник такой вопрос. Почему по умолчанию используется стратегия `AddToEndStrategy`, если самая популярная это `AddToEndSingleStrategy`?

**Comment by xanderblinov** [comment]
Добрый день, `AddToEndStrategy `  имеет самое ожидаемое поведение. Данную стратегию выбрали по причине того, что она интуитивно понятна и с нее легче будет начать.

**Comment by OsipXD** [comment]
Но разве самое ожидаемое поведение это не то, которое чаще всего используется?

**Comment by xanderblinov** [comment]
Когда вы начинаете работать с библиотекой, проще понимать, что все команды выполняются после переворота. Когда вам нужно выкинуть какие-то команды, вы начинаете уже смотреть на стратегии.

Согласен, что тема спорная, однако сейчас уже меть команду по умолчанию нельзя, так как это может вызвать непредсказуемое поведение при апгрейде с более ранней версии

**Comment by OsipXD** [comment]
Да, менять нельзя. Но я думаю, что было бы полезно иметь возможность изменить стратегию по умолчанию для всего проекта. Правда я не знаю как это лучше сделать если код генерируется.

**Comment by xanderblinov** [comment]
Уже был пулл реквест https://github.com/Arello-Mobile/Moxy/pull/79  от @A-Zaiats . Пока этот функуционал откатили. Issue закрываю, дальнейшее обсуждение можете продолжить под указанным выше пулл реквестом.
