### ISSUE TITLE
Why MvpActivity extends Activity not AppCompatActivity. 

### ISSUE THREAD

**Issue by kazimdsaidul** [Arello-Mobile/Moxy#155]
Why MvpActivity extends Activity. If We use Activity we can't use toolbar and another design view component in my activity.  Activity like pause when presenter working. Please fixed it. 
Thanks

**Comment by senneco** [comment]
Hi @kazimdsaidul . There is [moxy-app-compat](https://github.com/Arello-Mobile/Moxy/tree/master/moxy-app-compat) module. This contains MvpAppCompatActivity ;)
