### ISSUE TITLE
 BaseMvpFragment super.onCreate() is called before mvpDelegate.onCreate() 

### ISSUE THREAD

**Issue by Buckstabue** [Arello-Mobile/Moxy#158]
Please consider calling mvpDelegate.onCreate() before super.onCreate(). Reason: imagine we have a host fragment and a child fragment. Child fragment's presenter should be able to communicate with the host presenter in onCreate() method. Firstly I add a child fragment in onCreate()/onStart()/whatever I want method of the host fragment. All is ok. But after the user rotates the phone, the child presenter gets onCreate() call before the host's onCreate and it causes the child presenter to communicate with unexistent/uninitialized host presenter. It will be fixed if you call mvpDelegate.onCreate() first

**Comment by senneco** [comment]
Hi, sorry, but I'm confused in your problem. But I have one comment: you should not communicate between presenters. You should communicate through the Domain layer (via Interactors). And then you will not have any problems ;)

**Comment by xanderblinov** [comment]
Hi @Buckstabue , moxy presenters exists while device rotating. Check you implemented it correct.

**Comment by Buckstabue** [comment]
To be honest the problem is not in presenters, the problem is in MvpDelegate. I implemented such a delegate which can save dagger component on configuration change. The problem is that the MvpDelegate in the host fragment initializes dagger component in onCreate() method. And the child fragment asks the host fragment for the dagger component in its onCreate(). In conclusion, I get NPE when device is rotated since dagger component is not initialized in the host fragment MvpDelegate

**Comment by Buckstabue** [comment]
Raughly, the host fragment MvpDelegate creates dagger component and the child fragment asks the host for the component in onCreate()

**Comment by xanderblinov** [comment]
You may implement your own implementation of base Moxy Fragment with calling delegates method whenever you want. But we suggest you store daggers components in separated place and do not mix MVP and DI logic
