### ISSUE TITLE
ViewStates and process kill

### ISSUE THREAD

**Issue by UvarovBoris** [Arello-Mobile/Moxy#160]
Hi, is it possible to restore view states afrer process kill. For example, after working with activity user turn it and come back after hour. There is big chance that Android kill process. How to restore that view states?

**Comment by senneco** [comment]
Hi, Moxy doesn't solve this problem =( But you can tell for your Presenter that activity go to save/restore instance state and Presenter is able to restore self state. But then you should restore your Interactor's state, at the same time it's not Presentation layer's responsibility.

In my mind, you should restore state of your Interactor by any persistant storage, firstly. And then restore state of Presenter by the Interactor rules.

**Comment by UvarovBoris** [comment]
Clear, thanks
