### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Vakk** [Arello-Mobile/Moxy#162]
Hello! I have an memory leak in MvpFacade and presenters counter. 

Steps to reproduce:
- Open some view;
- Bind test  data array of generated strings) into presenter;
- Close view;
- Open another view;
- After some time check memory and activity is removed by GC but presenter still alive.

Presenters holds in MvpFacade-> mPresentersCounter->mConnections (Map) which is a cause of memory leak. 

About using:
- Moxy Version is "1.3.3"
- I'm uses only local presenter.

**Comment by senneco** [comment]
Just use Moxy v1.5.3 ;)
