### ISSUE TITLE
[Feature] Группы методов

### ISSUE THREAD

**Issue by zTrap** [Arello-Mobile/Moxy#163]
Существуют ситуации когда необходимы группы методов, например:

есть равнозначные по отношению к состоянию вью методы
```java
@StateStrategyType(AddToEndSingleStrategy.class)
public interface SomeView extends MvpView {
 
    @StateStrategyType(SkipStrategy.class)
    void addItems(List<Review> list, boolean hasNext);

    void showApiError(String message);

    void showNetworkError();

    void showUnexpectedError();

    void hideError();
}
```
Понятно дело они должны выполняться по стратегии `AddToEndSingleStrategy` группой, отсюда и идея объединить их, например так:
```java
@StateStrategyType(AddToEndSingleStrategy.class)
public interface SomeView extends MvpView {

    @StateStrategyType(SkipStrategy.class)
    void addItems(List<Review> list, boolean hasNext);

    @StateStrategyGroup(1)
    void showApiError(String message);

    @StateStrategyGroup(1)
    void showNetworkError();

    @StateStrategyGroup(1)
    void showUnexpectedError();

    @StateStrategyGroup(1)
    void hideError();
}
```
или так
```java
@StateStrategyGroup(1)
@StateStrategyType(AddToEndSingleStrategy.class)
public interface SomeView extends MvpView {

    @StateStrategyGroup(2)
    @StateStrategyType(SkipStrategy.class)
    void addItems(List<Review> list, boolean hasNext);

    void showApiError(String message);

    void showNetworkError();

    void showUnexpectedError();

    void hideError();
}
```

Тогда можно будет удалить из стека не только одну и ту же команду, но и соответствующую ей.
На данный момент есть 2 пути решения подобной ситуации:
   1. Написать собственную стратегию
   2. Объединить методы в 1 и разграничивать критерии флагами и переменными
Оба способа менее удобны нежели данное решение.

Данная фича очень облегчила бы разрешение данной ситуации.

**Comment by senneco** [comment]
Hi, may be this helps you https://gist.github.com/senneco/98a532df9915901da8065448722cef9f

**Comment by zTrap** [comment]
@senneco yes, this example was helpful, but anyway i have one question: why this solution didn't included in library

**Comment by zTrap** [comment]
and if use this example we must write `@StateStrategyType(AddToEndSingleByTagStateStrategy.class, tag='some_tag')` under each method. This construction is so much bigger then my proposion

**Comment by zTrap** [comment]
The good solution will be splitting up tag and strategy-class in two different annotations, or allow write tag w/o strategy-class

**Comment by zTrap** [comment]
@senneco have you taken any decision regarding my question?

**Comment by senneco** [comment]
An additional thing adds complexity to the library. I also can not understand why is it necessary, when it is possible to do it on already working strategies?)

And what we should do if some command should be contained in two groups but not in a third?

At 99% cases you sholdn't to use `AddToEndSingleByTagStateStrategy`. All commands apply on the main thread and do this very quick. This strategy is requred only for very important cases. In other cases your strategies should be as simple as possible.

**Comment by xanderblinov** [comment]
Adding another annotation is useless.
A good solution is using [AddToEndSingleTagStrategy](https://github.com/Arello-Mobile/Moxy/blob/develop/sample-custom-strategy/src/main/kotlin/com/redmadrobot/app/presentation/launch/AddToEndSingleTagStrategy.kt)

How to make custom strategies you may check article at [Стратегии в Moxy (Часть 2)](https://habrahabr.ru/company/redmadrobot/blog/341108/) (sorry for Russian lang )
