### ISSUE TITLE
MvpActivity can not  add  v4 Fragment 

### ISSUE THREAD

**Issue by weilixing00** [Arello-Mobile/Moxy#169]
can let MvpActivity extents FragmentActivity?

**Comment by senneco** [comment]
You able to extends MvpAppCompatActivity (available in `com.arello-mobile:moxy-app-compat:1.5.3`) for ability to add support v4 fragments.

Also you able to create your own activity. Then just call `MvpDelegate` methods how `MvpActivity` does this.

**Comment by weilixing00** [comment]
thanks
