### ISSUE TITLE
How exactly does this work?

### ISSUE THREAD

**Issue by donnysim** [Arello-Mobile/Moxy#17]
Let's take a simple login screen. We have `LoginView` 

```
@StateStrategyType(value = AddToEndStrategy::class)
interface LoginView : MvpView {
    fun showProgress()
}
```

LoginActivity:

```
@InjectPresenter(type = PresenterType.LOCAL)
@JvmField
var mLoginPresenter: LoginPresenter? = null

// basic boilerplate ...

override fun showProgress() {
        contentContainer.visibility = View.GONE
        progressLoader.visibility = View.VISIBLE
        progressLoader.show()
    }
```

and a presenter:

```
@InjectViewState
open class LoginPresenter : MvpPresenter<LoginView>() {
    fun login() {
        viewState.showProgress()
    }
}
```

If I call `mLoginPresenter.login()` when I press login button my progressbar appears (ViewCommands are created for ViewState), but when I rotate the screen, it's shows login form. If I inspect it, it seems that the presenter does not survive state change and contains no ViewCommands afterwards to restore the state as a new instance is injected:
```
if (mViewCommands.isEmpty())
		{
			return;
		}
```
is always positive.

Tried `Notelin` app example, has the same problem - presenter does not survive. Is this behavior expected or am I not getting something?

**Comment by senneco** [comment]
Hi! Are LoginActivity extends from MvpActivity?

**Comment by donnysim** [comment]
Login activity extends MvpAppCompatActivity that is a copy paste from MvpActivity. Used the one from Moxy example.

**Comment by senneco** [comment]
Well, this behavior isn't expected. Could you check, is presenter the same after activity recreated? It should be same with same memory address.

Also, you can debug into viewState.showProgress() and see, what happenned inside generated code(if kotlin plugin allow this).

**Comment by donnysim** [comment]
Oh, I've found the problem. The form was in a fragment and there were no `if (savedInstanceState == null) {` check so it recreated the whole fragment. Whew. Thanks for the help. Analyzing someones else code is difficult :D
