### ISSUE TITLE
Activity and Presenter place at different gradle modules - NPE at Presenter on getViewState()

### ISSUE THREAD

**Issue by lelyuh-aa** [Arello-Mobile/Moxy#171]
добрый день!
Есть два модуля (отдельная библиотека - в ней Presenter и View, и модуль основного приложения - в нем Activity, реализующая View) Аннотации используются в обоих модулях, поэтому Moxy генерирует два разных MoxyReflector, один в библиотеке, другой в приложении. В одном есть правильный sViewStateProviders, в другом правильный sPresenterBinders. 
Когда в Presenter вызывается метод getViewState(), то по всей видимости используется MoxyReflector из приложения, где нет нужного  sViewStateProviders и возникает NPE.
Подскажите, есть ли возможность корректной настройки обоих модулей, чтобы не было ошибок? Либо обязательно нужно, чтобы аннотируемые классы находились в одном модуле?
Спасибо.

**Comment by senneco** [comment]
Hi,

When you use moxy in different modules, you should do this: https://github.com/Arello-Mobile/Moxy/wiki/Multiple-modules

**Comment by lelyuh-aa** [comment]
спасибо!
проблема решена.
