### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by DmitryTankovich** [Arello-Mobile/Moxy#172]
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.arellomobile.mvp.viewstate.strategy.AddToEndSingleStrategy.beforeApply(SourceFile:23)
       at com.arellomobile.mvp.viewstate.ViewCommands.beforeApply(SourceFile:27)

Версия 1.5.3

**Comment by senneco** [comment]
Кажется, у вас происходит вот что:
1. Вы отправляете команду во вью
2. Во время выполнения этой команды вы отправляете команду в презентер
3. Во время выполнения этой команды презентером, отправляете какую-то команду во вью

**Comment by DmitryTankovich** [comment]
Да, функции в презентере могут выполняться асинхронно. 
У вас команды хранятся в листе, было бы не плохо переделать на что-то многопоточное ConcurrentLinkedQueue, Collections.synchronizedList к примеру

**Comment by senneco** [comment]
Нет, дело не в многопоточности. Даже наоборот -- в однопоточности. И заключается она вот в чём: во время восстановелния вью стейта происходит итерирование по очереди команд. И в этот момент вы отправляете новую команду в эту очередь. И получается, что итератор ломается.

**Comment by DmitryTankovich** [comment]
Получается нужно дождаться isInRestoreState и только после этого отправлять новые команды?

**Comment by horse315** [comment]
Не, надо из основного потока обновлять вью стейт.

**Comment by jeksor** [comment]
Цельная цепочка вызовов может заканчиваться одним из таких вариантов:
1. Presenter -> View
2. Presenter -> View -> Presenter

А у вас скорее всего:
Presenter -> View -> Presenter -> View

Из-за этого когда ViewState восстанавливается, происходит то, что описал
Юрий.

**Comment by senneco** [comment]
@DmitryTankovich вы разобрались? Или может есть больше информации?

**Comment by DmitryTankovich** [comment]
@senneco да, я разобрался, спасибо за пояснения
