### ISSUE TITLE
ClassCastException при одинаковом именовании разных презентеров

### ISSUE THREAD

**Issue by sharezz** [Arello-Mobile/Moxy#173]
Добрый день. 

**Fragment1**
`class Fragment1 : MvpAppCompatFragment(), Fragment1View {

    @InjectPresenter(type = PresenterType.WEAK)
    lateinit var mPresenter: Fragment1Presenter

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val textView = TextView(context)
        textView.text = "Fragment1"
        return textView
    }
}`

**Fragment2**
class Fragment2 : MvpAppCompatFragment(), Fragment2View {

    @InjectPresenter(type = PresenterType.WEAK)
    lateinit var mPresenter: Fragment2Presenter

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val textView = TextView(context)
        textView.text = "Fragment2"
        return textView
    }
}

На первом шаге отображаю Fragment1 и все идет отлично. Вторым шагом переключаюсь на второй фрагмент и ловлю:
`java.lang.ClassCastException: sharezzorama.com.moxyclasscastexample.fragment1.Fragment1Presenter cannot be cast to sharezzorama.com.moxyclasscastexample.fragment2.Fragment2Presenter`

Заметил, что в сгенерированных классах в конструктор, в качестве тэга передается имя презентера(mPresenter):
**Fragment1$$PresentersBinder.java**
`public mPresenterBinder() {
			super("mPresenter", PresenterType.WEAK, null, sharezzorama.com.moxyclasscastexample.fragment1.Fragment1Presenter.class);
		}`

**Fragment2$$PresentersBinder.java**
`public mPresenterBinder() {
			super("mPresenter", PresenterType.WEAK, null, sharezzorama.com.moxyclasscastexample.fragment2.Fragment2Presenter.class);
		}`

Проблема уходит если использовать различные имена для презентеров либо при предоставлении тэга через @ProvidePresenterTag. Проект с демонстрацией ошибки: https://github.com/sharezz/MoxyPresentersClassCastExample

**Comment by xanderblinov** [comment]
Hy, @sharezz 
Thank you for your question.
Firstly, I recommend you do not use weak presenters at all. Storing state and share it between multiple view is responsibility of interactor or stuff like this.

But, if you decide to use Weak presenter type, please provide tag at annotation parameters for every Weak presenter. Global and Weak presenters storing at special map, and this tag is a key for a presenter. If you have not provide a tag, presenter storing with `null` tag, so you have `ClassCastException ` when you trying to assign Fragment1Presenter (which stored at presenters map) for a Fragment2Presenter field

**Fragment1**
`class Fragment1 : MvpAppCompatFragment(), Fragment1View {

    @InjectPresenter(type = PresenterType.WEAK, tag = "SOME_TAG_FOR_PRESENTER")
    lateinit var mPresenter: Fragment1Presenter

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val textView = TextView(context)
        textView.text = "Fragment1"
        return textView
    }
}`
