### ISSUE TITLE
Another issue about testing presenter. With kotlin this time.

### ISSUE THREAD

**Issue by LolusKekus** [Arello-Mobile/Moxy#178]
Hello!

I'm trying to write some tests for presentation layer and faced off with a problem.

I'm decided to use your sample from [this](https://github.com/Arello-Mobile/Moxy/tree/develop/sample-kotlin) source for my experiments.

I wrote next piece of code and tried it:
```
import com.nhaarman.mockito_kotlin.mock
import com.nhaarman.mockito_kotlin.verify
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.junit.MockitoJUnitRunner

@RunWith(MockitoJUnitRunner::class)
class DialogPresenterTest {
    lateinit var presenter: DialogPresenter
    lateinit var view: DialogView

    @Before
    fun setUp() {
        view = mock()
        presenter = DialogPresenter()
        presenter.attachView(view)
    }

    @Test
    fun testShowDialog(){
        presenter.onShowDialogClick()
        verify(view).hideDialog()

    }
}
```

When i'm starts this test its fail with NPE when calling
```
fun onShowDialogClick() {
    viewState.showDialog()
}
```
because viewState is null.

This is my gradle

```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.yourname.moxykotlintest"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
kapt {
    generateStubs = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'com.arello-mobile:moxy:1.5.3'
    compile 'com.arello-mobile:moxy-app-compat:1.5.3'
    kapt 'com.arello-mobile:moxy-compiler:1.5.3'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.12.0'
    androidTestCompile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testCompile "com.nhaarman:mockito-kotlin-kt1.1:1.5.0"
}
```
```
ext.kotlin_version = '1.2.0'
```

Please, help me to understand where i'm wrong.

**Comment by senneco** [comment]
Hi @LolusKekus 

See [here](https://github.com/Arello-Mobile/Moxy/blob/develop/sample-github/src/test/java/com/arellomobile/mvp/sample/github/mvp/presenters/RepositoriesPresenterTest.java) how to test presenter and do similar in your kotlin code.

**Comment by a-f0x** [comment]
in build gradle
apply plugin: 'kotlin-kapt'
class DialogPresenterTest {

    @Test
    fun testPresenterOnShowDialog() {
        var isCalled = false
        val p = DialogPresenter()

        p.attachView(object : DialogView {
            override fun showDialog() {
                isCalled = true
            }
            override fun hideDialog() {
            }
        })
        p.onShowDialogClick()
        Assert.assertEquals(true,isCalled)
    }
}

**Comment by a-f0x** [comment]
@Test
    fun testPresenterWithMock(){
        val p = DialogPresenter()
        p.attachView(dialogView)
        p.onShowDialogClick()
        verify(dialogView).showDialog()
    }

**Comment by LolusKekus** [comment]
@a-f0x Yes! Yes! ```apply plugin: 'kotlin-kapt'``` That's what i'm exactly needed! Thanks a lot!
