### ISSUE TITLE
Работа с Custom View

### ISSUE THREAD

**Issue by daniil-vinogradov** [Arello-Mobile/Moxy#179]
Здравствуйте!

Столкнулся с проблемой.
Пытаюсь сделать  mvp custom view внутри фрагмента, но при открытие нового фрагмента или активити текущий фрагмент не уничтожается, т.е. у него не вызывается `onDestroy()`, а только `onDestroyView() `.

При возвращение на фрагмент с custom view, методы custom view отрабатывают по 2 раза, у уничтоженной старой view и у только что созданной, если снова уйти на новый фрагмент и вернуться, то методы отработают уже 3, 4 и т.д. раз

Данный код в `onDestroyView()` помогает избежать этого:
```
//        TODO Moxy CustomView workaround
        try {
            Field field = MvpDelegate.class.getDeclaredField("mChildDelegates");
            field.setAccessible(true);
            List<MvpDelegate> childDelegates = (List<MvpDelegate>) field.get(getMvpDelegate());
            childDelegates.remove(mCustomWidget.getMvpDelegate());
        } catch (Throwable ignored) {
            // do nothing
        }
```

Тестовый проект: https://github.com/daniil-vinogradov/MoxyIssue
Сейчас приложение крашится, но если раскомментировать этот код в `FragmentA`, то все работает как надо.
В чем может быть проблема? Делал по https://github.com/Arello-Mobile/Moxy/wiki/CustomView-as-MvpView

**Comment by rsajob** [comment]
Постарался решить проблему Pull Request #182 

На всякий случай тут продублирую более детальное описание

1. Задача: Есть 2 фрагмента. По кнопке из первого фрагмента переходим на второй, сохраняя первый в стеке. Из второго фрагмента по кнопке Back возвращаемся обратно на первый фрагмент.
2. В первом фрагменте имеется `CustomView` c MVP. Каждый раз при показе первого фрагмента, при создании его view через inflate создается новый объект класса `CustomView` в котором нужно проинициализировать MVP. 
3. Инициализация MVP заключается в создании своего делегата у `CustomView` и привязке его к родительскому (к делегату фрагмента) через метод `MvpDelegate::setParentDelegate()`. В этом методе происходит двойное связывание родительского и дочернего делегатов. Родительский делегат начинает хранить ссылки на дочерний (вызов `delegate.addChildDelegate(this)`)
5. При переходе на второй фрагмент, объект класса первого фрагмента не уничтожается, а сохраняется в стеке (`onDestroy()` у него не вызывается) и его делегат тоже продолжает жить. А вот весь его view уничтожается (вызывается `onDestroyView()`) вместе c `CustomView`. Однако родительский делегат всё равно продолжает хранить ссылку на `CustomView` (в поле `MvpDelegate::mChildDelegates`). И нет никакой нормальной возможности его отвязать. **Вот тут происходит утечка памяти.** 
6. При возврате обратно на первый фрагмент, layout создаётся заново, создается новый объект `CustomView` и его делегат ещё раз добавляется в родительский. Таким образом там уже 2 ссылки, на старый `CustomView` и на новый. Далее происходит передача событий (`onAttach` `onDetach` и т.д.) а также команд в дочерний делегат умершего `CustomView`.
7. При перевороте экрана такого не происходит, так как первый фрагмент пересоздается вместе с делегатом.

**Comment by rsajob** [comment]
Ещё есть такая проблема.
При создании делегат генерирует тег (mDelegateTag), создает презентер, сохраняет презентер в хранилище c этим тегом. Но не сохраняет этот тег в bundle сразу. Также при создании он проверяет наличие тега в bundle и если он там есть то берёт оттуда а не генерирует. 

Метод MvpDelegate::onSaveInstanceState() нужно вызывать только когда делегат является дочерним. При вызове у корневого делегата всё сохраняется в новый Bundle который нигде не используется и не хранится. Я думаю стоит бросать Exception если вызван MvpDelegate::onSaveInstanceState() у корневого делегата. 

Если делать иерархию из CustomView чтото типа такого:
```
Fragment
  - CustomView1
     - CustomView2
```
То нужно обязательно после инициализации mvp у CustomView1 вызвать метод `mMvpDelegate.onSaveInstanceState()` чтобы в Bundle фрагмента сохранились теги презентеров, иначе презентеры начинают создаваться заново в MvpDelegate.onCreate() и копится в PresentorStore.

Всё это не явно и новичкам в библиотеке придётся хорошо посидеть с отладчиком чтобы выявить все эти нюансы.
