### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by ITGoodBoy** [Arello-Mobile/Moxy#188]
Всем привет, подскажите, вот у меня есть два презентера - DownloadPicturePresenter и UploadPicturePresenter, так как на одном экране нужно лишь загружать фото на сервер, в другом лишь получать, но есть так же экран где надо два этих действия, так вот, как реализовать композицию  в моём случае? Я создал PicturePresenter но всунуть туда DownloadPicturePresenter  и UploadPicturePresenter не получилось, т.к. при InjectPresenter без интерфейсов не работает(ошибка при сборке проекта) а если создавать презентеры через new, их методы выполняются, однако похоже getViewState.someMethod игнорируются, что странно, так как моя целевая активность имплементит DownloadPictureView и UploadPictureView, вот код для наглядности: 

```
public interface UploadPictureView extends MvpView {

    void uploadPictureToServerSuccess(Image image);
    void uploadPictureToServerFailed(String message);
} 

public interface DownloadPictureView extends MvpView {

    void downloadPictureFromServerAsyncStarted();
    void downloadPictureFromServerFailed(String message);
}

public interface PictureView extends DownloadPictureView, UploadPictureView{
}
```

и Presenters: 
```
@InjectViewState
public class UploadPicturePresenter extends BasePresenter<UploadPictureView> {

    @Inject
    ImageApi mImageApi;

    public UploadPicturePresenter () {
        App.getAppComponent().inject(this);
    }


    public void uploadPictureToServer(RequestBody pictureBase64, AuthToken authToken) {
      Disposable disposable = mImageApi
                .uploadPictureToServer(pictureBase64, authToken.getToken())
                .compose(Utils.applySchedulers())
                .subscribe(pictureResponse -> {
                    switch (pictureResponse.code()) {
                        case CREATED:
                            getViewState().uploadPictureToServerSuccess(pictureResponse.body());
                            break;
                        default:
                            getViewState().uploadPictureToServerFailed("UnexpectedError");
                            break;
                    }
                }, throwable -> {
                    throwable.printStackTrace();
                    getViewState().uploadPictureToServerFailed("UnknownError or Not inernet");
                });

        disposeOnDestroy(disposable);
    }

}






@InjectViewState
public class DownloadPicturePresenter extends BasePresenter<DownloadPictureView> {

    @Inject
    Context mContext;

    public DownloadPicturePresenter() {
        App.getAppComponent().inject(this);
    }


    public void downloadPhotoAsync(String profilePhoto, String authToken, ImageView imageView) {
        GlideApp.with(mContext)
                .asBitmap()
                .load(GlideUtils.createGlideUrl(profilePhoto, authToken))
               // .apply(RequestOptions.circleCropTransform())
                .into(imageView);

        getViewState().downloadPictureFromServerAsyncStarted();
    }


}
```

и мой PicturePresenter в котором пытаюсь сделать композицию 

```
@InjectViewState
public class PicturePresenter extends BasePresenter<PictureView>{

   
    UploadPicturePresenter mUploadPicturePresenter;
    DownloadPicturePresenter mDownloadPicturePresenter;

    public PicturePresenter() {
        mUploadPicturePresenter= new UploadPicturePresenter ();
        mDownloadPicturePresenter = new DownloadPicturePresenter();
    }

    public void uploadPictureToServer(RequestBody pictureBase64, AuthToken authToken) {
        mUploadPicturePresenter.uploadPictureToServer(pictureBase64, authToken);
    }

    public void downloadPhotoAsync(String profilePhoto, String authToken, ImageView imageView) {
        mDownloadPicturePresenter.downloadPhotoAsync(profilePhoto, authToken, imageView);
    }
```

Методы вложенных presenters будут работать, однако не getViewState в этих методах, даже если моя активность их имплементит. Буду рад любой подсказки.

P.S. Я знаю два варианта решения, первый из которых просто создать PicturePresenter  с этими методами и юзать те его методы которые необходимы в разных активностях, однако мне не хочется  
что бы в презентере был метод который не когда не будет использован активностью ( это тоже самое если создать один огромный презентер укоторого будут методы обработки всех запросов к серверу,а потом просто юзать только его, что как то не красиво смотрится), Второй вариант просто инжектить UploadPicturePresenter и DownloadPicturePresenter там где надо и то и другое, однако у меня очень масштабируемое приложение, и вот есть к примеру 20 экранов по одному презентеру, все они разные (в одном например отображается имя, во втором фамилия, в третем возраст, и так все остальные)  и еще 10 экранов где нужны все методы этих 20 презентеров, мне же не инжектить по 20 презентеров в каждом из этих экранов верно?

**Comment by senneco** [comment]
В мокси нет такой возможности композиции презентеров -- чтобы сложить их в третий, и магическим образом они соединятся с вьюхой, в которой вставлен изначальный презентер.

Вы можете сделать так, что `PictureView extends UploadPictureView, DownloadPictureView`, а затем в конструкторе `PicturePresenter` устанавливать влоежнным презентерам его вью стейт в качестве их вью стейтов. М.б. тогда взлетит.

Но я не уверен на счёт правильности такого подхода впринципе. Но может я плохо понял вашу задачу.

**Comment by ITGoodBoy** [comment]
@senneco Спасибо за такой оперативный ответ, вы были правы всё отлично работает через attachView. P.S. Спасибо за такую крутую библу, очень удобная.

```
@InjectViewState
public class PicturePresenter extends BasePresenter<PictureView>{

   
    UploadPicturePresenter mUploadPicturePresenter;
    DownloadPicturePresenter mDownloadPicturePresenter;

    public PicturePresenter() {
        mUploadPicturePresenter= new UploadPicturePresenter ();
        mUploadPicturePresenter.attachView(getViewState());

        mDownloadPicturePresenter = new DownloadPicturePresenter();
        mDownloadPicturePresenter.attachView(getViewState());
    }

    public void uploadPictureToServer(RequestBody pictureBase64, AuthToken authToken) {
        mUploadPicturePresenter.uploadPictureToServer(pictureBase64, authToken);
    }

    public void downloadPhotoAsync(String profilePhoto, String authToken, ImageView imageView) {
        mDownloadPicturePresenter.downloadPhotoAsync(profilePhoto, authToken, imageView);
    }
```
