### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by olegsvs** [Arello-Mobile/Moxy#192]
Всем привет, есть такая проблема:
Имеется BaseView
```
public interface BaseView extends MvpView {
    void showError(Throwable throwable);
}
```
которую наследует другой view(ProblemView)
`interface ProblemView extends BaseView { }`
 и переопределяет ее в фрагменте(ProblemFragment):
```
    @InjectPresenter
    ProblemPresenter presenter;
//...
    @Override
    public void showError(Throwable throwable) {
//
    }
```
в то же время данный метод вызывает presenter(ProblemPresenter).
```
@InjectViewState
public class ProblemPresenter extends BasePresenter<ProblemView>
```
Проблема в том, что при навигации на другой фрагмент и возвращении оттуда данный метод вызывается повторно(причем с теми же параметром throwable). В чём может быть проблема?

**Comment by olegsvs** [comment]
Сделал так:
```
public interface BaseView extends MvpView {
    @StateStrategyType(SkipStrategy.class)
    void showError(Throwable throwable);
}
```
Это правильное решение?

**Comment by ekursakov** [comment]
Правильное, но для того чтобы событие не потерялось, если вдруг презентер вызовет метод пока вью не приаттачено, вместо `SkipStrategy ` лучше использовать `OneExecutionStateStrategy `.

**Comment by olegsvs** [comment]
@ekursakov данная стратегия подойдет к кейсу, когда данный метод может вызваться и несколько раз из кода(к примеру пользователь несколько раз сделал ошибочное действие)? Но не должен вызываться после перезахода на view? Спасибо.

**Comment by ekursakov** [comment]
После перезахода метод вызовется только в случае, если метод был вызван из презентера, когда вью не была присоединена. Обе эти стратегии вызывают метод во вью не более 1 раза.
Про отличия стратегий в статье https://habrahabr.ru/company/redmadrobot/blog/325816/ более подробно можно почитать.

**Comment by olegsvs** [comment]
Спасибо
