### ISSUE TITLE
Build fails if View method have return value

### ISSUE THREAD

**Issue by Akkell** [Arello-Mobile/Moxy#2]
If you add a method that returns a value to the View (both interface and implementation) - generated code will contain error and won't be compiled.
Specifically, generated method with return value will contain:

		if (mViews == null || mViews.isEmpty())
		{
			return; //compile-time error. missing return value
		}

This statement should `return null;` at least.

**Comment by senneco** [comment]
Thanks to this comment. We will think about it. Because it is very dangerous to have methods in view, that can return come value. Because one presenter may send command to multiple view.

Now i think, that we should break codegeneration, if view method is not void. Then the user will not be able to shoot yourself in the foot.

**Comment by micdm** [comment]
@senneco could you give an example when there is a need to attach single presenter to multiple views simultaneously?
In my opinion it is very handy to have views returning some events like `Observable<Channel> getSelectedChannel();` and combine that stream on the presenter with another RxJava-related stuff (not sure though if it is canonical MVP still). So another way of `presenter.setSelectedChannel(Channel channel);` isn't very convenient for me.

**Comment by senneco** [comment]
@micdm I have some simple sample. You make an audio player. And you want show current track in some place of application and show current track in notification area. For simplify communication between notification and some view you can attach both of this views to single prersenter.

More abstractly: if you show some content in different places in app, you can use single presenter for all views.

In your case, you shouldn't get selected channel from view. It's really not canonical MVP. You should send from presenter to view, what is selected channel. And nothing to stop you to make method setSelectedChannel in presenter, where you emit new channel to some subscriber.

**Comment by micdm** [comment]
Thanks, it makes sense now.
> In your case, you shouldn't get selected channel from view. It's really not canonical MVP. You should send from presenter to view, what is selected channel. And nothing to stop you to make method setSelectedChannel in presenter, where you emit new channel to some subscriber.

I guess I'll end up with something like this on the presenter:
```
protected PublishSubject<String> email = PublishSubject.create();
public void setEmail(String email) {
    this.email.onNext(email);
}
// Executed once when the presenter is initialized:
protected Subscription subscribeForEmail() {
    return email.filter(Functions::isEmailCorrect).subscribe(...);
}
```
Huge boilerplate code, yeah.

**Comment by senneco** [comment]
It's payment for canonical MVP =) But in future it could save you.

**Comment by micdm** [comment]
Alright, if someone ever will look into that issue with the same trouble then I've make [a dirty hacks](https://github.com/micdm/Moxy/commit/54576d38ed27c924029332d75d4d8cfd697172e6). It allows to write an Observable getters as I mentioned above. Really fast and dirty.
And again:
```
@Override
public Observable<String> getEmail() {
    return RxTextView.textChanges(emailView).map(CharSequence::toString);
}
```
vs
```
@Override
public void setupEmailView() {
    emailView.addTextChangedListener(new TextWatcher() {
        @Override
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
        @Override
        public void onTextChanged(CharSequence s, int start, int before, int count) {
            presenter.setEmail(s.toString());
        }
        @Override
        public void afterTextChanged(Editable s) {}
    });
}
```
The first way allows your views to not even known about the presenter (except two @InjectPresenter lines).

**Comment by senneco** [comment]
Really dirty =) Why not make method `setEmailObservable(Observable<String> email)` inside your presenter. And simply send observable from `onCreate` method?

Like this:

```
public void onCreate(Bundle savedState) {
    super.onCreate();
    ButterKnife.bind(this);

    mPresenter.setEmailObservable(RxTextView.textChanges(emailView).map(CharSequence::toString))
}
```

Then you shold not modify library and no boilerplate code. Also, if you attach two view to this presenter, you will be able to decide which one of observable to use.

**Comment by micdm** [comment]
Well then I have to create properties on the presenter like `Observable<String> email` and maybe even `Observable<String> email2` and so on. Not sure if there is a need to know which view has triggered an event. Back to the audioplayer example: we can press one of many Play buttons across the application and do the same work every time. Your idea is great that the presenter doesn't know how many views attached, so we could keep it (or maybe not — will see).
Hacking the library is bad idea for sure. Would be nice if there were some way to extend the compiler so I could make just a little addition for RxJava support.
Anyway you guys made a cool job! I'm going to use it for production now.

**Comment by senneco** [comment]
Now annotation processing wil be failed if your view method returns some value.
