### ISSUE TITLE
The v.1.5.4 is broken

### ISSUE THREAD

**Issue by Yukooo** [Arello-Mobile/Moxy#202]
Hello, according to the [the maven](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.arello-mobile%22%20AND%20(a%3A%22moxy%22%20OR%20a%3A%22moxy-compiler%22%20OR%20a%3A%22moxy-android%22%20OR%20a%3A%22moxy-app-compat%22)) there is the  v.1.5.4 but it doesn't contain com.arellomobile.mvp.InjectViewState at least

**Comment by senneco** [comment]
Hi, it's known problem. Use 1.5.3 please

пт, 1 июн. 2018 г., 14:02 Yuriy Kovalenko <notifications@github.com>:

**Comment by senneco** [comment]
@Yukooo hi, I released moxy v1.5.5. Could you check is it work for you? Thx.

**Comment by Yukooo** [comment]
It works for me. Thx a lot, for a quick support. PS. Дай вам бого здоровья за вашу замечательную  работу.
