### ISSUE TITLE
Broken generation for parameterized view.

### ISSUE THREAD

**Issue by ValdZX** [Arello-Mobile/Moxy#203]
Broken generation if view interface is parameterized of any. Example:
`@StateStrategyType(SingleStateStrategy.class)
public interface CommonView<T> extends MvpView {
    void showParametrizedData(T any);
}`
`@StateStrategyType(SingleStateStrategy.class)
public interface MainView extends CommonView<String> {
    void showNotParametrizedData(String any);
}`

# Gradle log:
:app:javaPreCompileDebug
/home/valdzx/Workspace/github/MoxyTesting/app/build/generated/source/apt/debug/ua/com/vald_zx/moxyissuesample/mvp/main/view/MainView$$State.java:27: error: cannot find symbol
	public void showParametrizedData(T any) {
	                                 ^
  symbol:   class T
  location: class MainView$$State
/home/valdzx/Workspace/github/MoxyTesting/app/build/generated/source/apt/debug/ua/com/vald_zx/moxyissuesample/mvp/main/view/MainView$$State.java:58: error: cannot find symbol
		public final T any;
		             ^
  symbol:   class T
  location: class MainView$$State.ShowParametrizedDataCommand
/home/valdzx/Workspace/github/MoxyTesting/app/build/generated/source/apt/debug/ua/com/vald_zx/moxyissuesample/mvp/main/view/MainView$$State.java:60: error: cannot find symbol
		ShowParametrizedDataCommand(T any) {
		                            ^
  symbol:   class T
  location: class MainView$$State.ShowParametrizedDataCommand
3 errors

> Bug actual for version **Moxy 1.5.5**
> On 1.5.3 works fine.

## Sample https://github.com/ValdZX/MoxyTesting

**Comment by senneco** [comment]
[There](https://github.com/Arello-Mobile/Moxy/blob/feature/extends-of-generic-view/moxy-compiler/src/test/java/com/arellomobile/mvp/compiler/ViewStateTest.java) is test that should go for resolve this issue ("view.ExtendsOfGenericView" should be processed well)

**Comment by ekursakov** [comment]
I'll look into it soon. I started to investigate this bug several months ago. But I only wrote similar test and some code which I don't quite understand now :)

**Comment by AlexeyKorshun** [comment]
I try to understand code right now, i have got a idea, but I have trouble with with test.

**Comment by vkotovv** [comment]
@senneco any updates on this?

**Comment by senneco** [comment]
@shaders could you help with publishing of new moxy version, pls?) There is merged this PR
