### ISSUE TITLE
AndroidX is not supported

### ISSUE THREAD

**Issue by ahulyk** [Arello-Mobile/Moxy#204]
MvpAppCompatFragment extends android.support.v4.app.Fragment and should extends androidx.fragment.app.Fragment to support androidX namespace

**Comment by senneco** [comment]
Hi,

I plane to make moxy-android-x module. This allows to use different ways without some conflicts.

**Comment by ahulyk** [comment]
@senneco hi :)
Cool, thanks!

**Comment by jordan1997** [comment]
I added PR #212 for this issue

**Comment by a-solovyev** [comment]
@senneco Hi. Can you merge **develop** into **master** and publish Moxy with moxy-androidx module?

**Comment by Bendor** [comment]
@senneco Any news about support androidX?

**Comment by foxyoverdrive** [comment]
Any news?..

**Comment by pereved** [comment]
When? :)

**Comment by Xset-s** [comment]
When???

**Comment by BuddyJava** [comment]
When? 🤓

**Comment by timuruktus** [comment]
We are waiting for Moxy for androidx :)

**Comment by ahulyk** [comment]
would be nice to have androidX support in place 👍

**Comment by shcherbuk96** [comment]
When?

**Comment by jordan1997** [comment]
I see some people need this feature, I will deploy my fork to maven central on this weekend. My fork has back compatible with Moxy 1.5.5 and support androidX.

**Comment by jordan1997** [comment]
https://github.com/jordan1997/Moxy

**Comment by senneco** [comment]
I did moxy specially for independent different modules  updates. So, feel free to use standart moxy library and 'tech.schoolhelper:moxy-x-androidx:1.5.6' for andoridx compatibility. Also, you can create other adapters to MvpDelegate (g.e. special wrapper for recycler view).

**Comment by kykaparov** [comment]
If you want to wait for official release and migrate anyway to AndroidX, then you can move `MvpAppCompatActivity.java`, `MvpAppCompatDialogFragment.java`, `MvpAppCompatFragment.java` to your project and change the `support` imports to `androidx` and refer to this files in your project.

**Comment by victorlapin** [comment]
> If you want to wait for official release and migrate anyway to AndroidX, then you can move `MvpAppCompatActivity.java`, `MvpAppCompatDialogFragment.java`, `MvpAppCompatFragment.java` to your project and change the `support` imports to `androidx` and refer to this files in your project.

Yep, I've posted the link somewhere above. You know, for lazy folks =)

**Comment by marinat** [comment]
expect an official release in the main branch?

**Comment by luckcoolla** [comment]
any news here?

**Comment by olegivo** [comment]
To work around the issue we can cut out Moxy from our projects...

**Comment by ivanessence** [comment]
up problem

**Comment by senneco** [comment]
There is not problem =) Just apply `implementation 'tech.schoolhelper:moxy-x-material:1.7.0'`

**Comment by pavelpoley** [comment]
can someone help
https://github.com/Arello-Mobile/Moxy/issues/258
