### ISSUE TITLE
Add composite annotation support

### ISSUE THREAD

**Issue by rcd27** [Arello-Mobile/Moxy#205]
This comes quite handy to be able to create a "composite" annotation.
For example, it is impossible to have `private` field for `@InjectPresenter presenter`, and lint is going crazy about telling me to make it private. This is good to have something like [this](https://stackoverflow.com/questions/23562005/java-make-a-separate-annotation-that-combines-a-others?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) but with `@SuppressWarnings("WeakerAccess")`

**Comment by jordan1997** [comment]
@InjectPresenter
internal lateinit var presenter: MainPresenter

**Comment by senneco** [comment]
After you run code generation it will be ok, because this field will be used from generated code. And then lint seeing this and not highlight this as error.

**Comment by jordan1997** [comment]
@senneco you are right, but we need to use 'internal' in the Kotlin files and `package local` in the Java file because of auto-generate code state in the same package. Am i right?

**Comment by senneco** [comment]
@jordan1997 it depends on your environment =) [There](https://github.com/Arello-Mobile/Moxy/blob/master/sample-kotlin/src/main/kotlin/com/arellomobile/mvp/sample/kotlin/MainActivity.kt#L15) all is right without `internal`
