### ISSUE TITLE
Не могу запустить Moxy/sample-github/

### ISSUE THREAD

**Issue by OstapenkoYevgeniy** [Arello-Mobile/Moxy#210]
Хочу изучить Moxy и Dagger2.

Я хочу "поковырять" пример, но проблема в том, что при попытке запустить проект получаю сообщение:

`C:...\sample-github\src\main\java\com\arellomobile\mvp\sample\github\app\GithubApp.java Error:(8, 45) error: cannot find symbol class DaggerAppComponent`

Пробовал создавать новый проект и переносить только sample-gitgub, т.к. sample-kotlin запускается. При попытке очистить и пересоздать проект вылетают ошибки gradle относящиеся к sample-kotlin. Т.к. только начинаю изучать Moxy и Dagger2, не могу самостоятельно разобраться и исправить ошибку, что бы запустить проект.

**Comment by alkocher** [comment]
Нужно повысить версию в build.gradle для dagger до 2.16

**Comment by OstapenkoYevgeniy** [comment]
@alkocher Спасибо, заработало!
