### ISSUE TITLE
Отложенный запуск очереди команд после пересоздания активити

### ISSUE THREAD

**Issue by igorkazakov** [Arello-Mobile/Moxy#211]
Возможен ли отложенный запуск очереди команд после пересоздания активити? Например на экране карта, у нее есть колбек - onMapReady(googleMap: GoogleMap?), так вот, я хочу, чтоб активити пересоздалось, затем через время вызвался колбек готовности карты и уже после всего этого начать запуск команд, которые отобразят данные на карте.

**Comment by xanderblinov** [comment]
Посмотрите в FAQ, там есть пример, как подключить Мокси к карте.

**Comment by senneco** [comment]
А если конкретней, то вот так: https://gist.github.com/terrakok/cd080a6a0213ef7430bdd72ebe92c9ef

Но конечно сходит в FAQ правильней =)
