### ISSUE TITLE
sample-github не компилируется

### ISSUE THREAD

**Issue by akadatsky** [Arello-Mobile/Moxy#214]
Скачал проэкт и хотел запустить sample-github.
AndroidStudio 3.1.3 AndroidSDK обновлено до последних версий.
Проэкт не компилируется:

> com/arellomobile/mvp/sample/github/app/GithubApp.java
> error: cannot find symbol class DaggerAppComponent

Gradle Clean, Rebuild, Invalidate Caches и прочие манипуляции не помогли.

После обновления в `build.gradle` dagger с версии 2.7 до 2.13 проэкт запустился.

Обновите плиз семпл до рабочего состояния.

**Comment by iljaosintsev** [comment]
Проблема остается. Не компилируются некоторые модули.

`./gradlew sample-github:assDeb -q`

```
GithubApp.java:8: error: cannot find symbol
import com.arellomobile.mvp.sample.github.di.DaggerAppComponent;
                                            ^
  symbol:   class DaggerAppComponent
  location: package com.arellomobile.mvp.sample.github.di

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-github:compileDebugJavaWithJavac'.
> java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: com.squareup.javapoet.ParameterSpec.get(Ljavax/lang/model/element/VariableElement;)Lcom/squareup/javapoet/ParameterSpec;
```

`./gradlew sample-custom-strategy:assDeb -q`

```
Moxy/sample-custom-strategy/src/main/kotlin/com/redmadrobot/app/presentation/launch/LaunchFragment.kt: (52, 5): 'onCreateView' overrides nothing
Moxy/sample-custom-strategy/src/main/kotlin/com/redmadrobot/app/presentation/launch/LaunchFragment.kt: (56, 5): 'onViewCreated' overrides nothing
Moxy/sample-custom-strategy/src/main/kotlin/com/redmadrobot/app/presentation/launch/LaunchFragment.kt: (57, 29): Type mismatch: inferred type is View? but View was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-custom-strategy:compileDebugKotlin'.
> Compilation error. See log for more details
```

**Comment by B0yma** [comment]
Попробуйте версию библиотеки 1.4.5
implementation 'com.arello-mobile:moxy-android:1.4.5'
    implementation 'com.arello-mobile:moxy-app-compat:1.4.5'
    annotationProcessor 'com.arello-mobile:moxy-compiler:1.4.5'

**Comment by jordan1997** [comment]
Fixed in the #225

**Comment by pringleActivity** [comment]
спасибо огромное. блин, нельзя так делать, знаете сколько я времени потратил, чтобы запустить? поменяйте версию moxy на 1.4.5 и у вас запустится. исправьте проблему!

**Comment by coffeeplanter** [comment]
Moxy 1.5.4 и 1.5.5 — sample-github опять не собирается.
На 1.5.3 собирается.
