### ISSUE TITLE
TabLayout and more than 2 fragments

### ISSUE THREAD

**Issue by R12rus** [Arello-Mobile/Moxy#217]
I have an activity. Inside this activity i use TabLayout and ViewPager. 
Inside onCreate method i create 3 fragments.

```
@ContentView(R.layout.activity_partner)
class PartnerActivity: BaseActivity(), PartnerView {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val session = getSerializableExtra<Session>(EXTRA_SESSION)
        val partner = getSerializableExtra<Partner>(EXTRA_PARTNER)
        val fragmentsMap = LinkedHashMap<BaseFragment, String>()
        fragmentsMap[InformationFragment.newInstance(session, partner)] = getString(R.string.tab_title_information)
        fragmentsMap[SalesFragment.newInstance(session, partner)] = getString(R.string.tab_title_shares)
        fragmentsMap[ShopsFragment.newInstance(session, partner)] = getString(R.string.tab_title_shops)
        viewpager.adapter = BaseFragmentPagerAdapter(supportFragmentManager, fragmentsMap)
        tabLayout.setupWithViewPager(viewpager)
    }
}
```

This is my activity presenter code. I don't use presenter to switch between fragments, cause ViewPager with adapter do it. 
```
@InjectViewState
class PartnerPresenter(
        private val sessions: Session,
        private val partner: Partner
) : BasePresenter<PartnerView>() {

    init {
        viewState.setTitle(Text.from(partner.name))
        viewState.setLogo(partner.image)
    }

}
```

This is FragmentPagerAdapter code.
```
class BaseFragmentPagerAdapter(
        fm: FragmentManager,
        fragmentsMap: LinkedHashMap<BaseFragment, String>
) : FragmentPagerAdapter(fm) {

    private val fragments= fragmentsMap.keys.toTypedArray()
    private val titles = fragmentsMap.values.toTypedArray()

    override fun getItem(position: Int): Fragment = fragments[position]

    override fun getCount(): Int = fragments.size

    override fun getPageTitle(position: Int): CharSequence? = titles[position]

}
```

All fragments are simple and have the same functional - request list of data from server and add it to recyclerview adapter.

```
@InjectViewState
class ShopsPresenter(
        private val sessions: Session,
        private val partner: Partner
) : BasePresenter<ShopsView>() {

    init {
        requestData()
    }

    private fun requestData() {
      ......
    }

}
```

And i came across with next situation: 
User on the fragment 1. Switch to fragment number 3. 
Presenter number 3 load data and set it to fragment (recyclerview adapter). 
User switch to fragment 1. 
User switch to fragment 3 again. And Fragment state is empty (no data in adapter).
I guess android can't save more than two fragments in memory. When you switch to fragment number 3 at the second time FragmentPagerAdapter (viewpager) recreate this fragment. But presenter doesn't understand that is new instance of fragment.

What I'm doing wrong ? Can you provide me an example with TabLayout, ViewPager and more than 2 fragments inside activity ?
Thank you.

**Comment by senneco** [comment]
I don't dive into your problem (sorry 😄 ). Dut firstly you can use FragmentStatePagerAdapter instead of FragmentPagerAdapter

**Comment by R12rus** [comment]
I found what was wrong. I used this function inside fragments.
    
```
protected fun <T : View> bind(@IdRes res: Int): Lazy<T> {
        @Suppress("UNCHECKED_CAST")
        return lazy(LazyThreadSafetyMode.NONE) {
            view!!.findViewById<T>(res)
        }
    }
```

The same situation.
https://stackoverflow.com/questions/35752575/kotlin-lazy-properties-and-values-reset-a-resettable-lazy-delegate
