### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference

### ISSUE THREAD

**Issue by max-makeichik** [Arello-Mobile/Moxy#218]
Добрый день!

Стектрейс:

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.example/ru.example.ui.auth.login.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2543)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2609)
>        at android.app.ActivityThread.access$900(ActivityThread.java:174)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1465)
>        at android.os.Handler.dispatchMessage(Handler.java:111)
>        at android.os.Looper.loop(Looper.java:207)
>        at android.app.ActivityThread.main(ActivityThread.java:5683)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
>        at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2587)
>        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2383)
>        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(SourceFile:2338)
>        at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2245)
>        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(SourceFile:3248)
>        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:3200)
>        at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:195)
>        at android.support.v4.app.FragmentActivity.onStart(SourceFile:597)
>        at android.support.v7.app.AppCompatActivity.onStart(SourceFile:177)
>        at com.arellomobile.mvp.MvpAppCompatActivity.onStart(SourceFile:27)
>        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1245)
>        at android.app.Activity.performStart(Activity.java:6286)

Crashlytcs показывает, что воспроизводится только на ZTE BLADE V7 LITE, Android 6.

В LoginActivity нет презентера и она не имплементит интерфейсов, наследует BaseActivity, которая наследует MvpAppCompatActivity.

implementation "com.arello-mobile:moxy:$moxyVersion"
kapt "com.arello-mobile:moxy-compiler:$moxyVersion"
implementation "com.arello-mobile:moxy-app-compat:$moxyVersion"
Версия moxy 1.5.3

**Comment by senneco** [comment]
Не похоже, чтобы проблема была в мокси. А с чего вы решили, что это имеет отношение к мокси?)

**Comment by max-makeichik** [comment]
Crashlytcs выделила эту строку - at com.arellomobile.mvp.MvpAppCompatActivity.onStart(SourceFile:27)

**Comment by senneco** [comment]
Это ясно. Но если посмотреть, что происходит в MvpAppCompatActivity на 27 строчке, то можно заметить, что там идёт вызов super.onStart(). И в этот момент мокси ничего не делает. Но если дадите гисты с вашим кодом, то может смогу помочь ;)

**Comment by max-makeichik** [comment]
Спасибо.
