### ISSUE TITLE
Некорректный app-compat fragment

### ISSUE THREAD

**Issue by CherryPerry** [Arello-Mobile/Moxy#22]
В обычном фрагменте есть [фикс](https://github.com/Arello-Mobile/Moxy/commit/ab2dc2352de74d4b6c614486896852411a7436ef) на закрытие активности:
```java
if (isRemoving() || getActivity().isFinishing()) {
    getMvpDelegate().onDestroy();
}
```

В саппортовском фрагменте этого фикса нет:
```java
if (isRemoving()) {
    getMvpDelegate().onDestroy();
}
```

**Comment by senneco** [comment]
Fixed!

Thanks for issue =)
