### ISSUE TITLE
FATAL EXCEPTION: ConcurrentModificationException при сохранении состояния активити

### ISSUE THREAD

**Issue by epereskokov** [Arello-Mobile/Moxy#222]
FATAL EXCEPTION: java.util.ConcurrentModificationException
                      at java.util.ArrayList$Itr.next(ArrayList.java:860)
                      at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
                      at com.arellomobile.mvp.viewstate.MvpViewState.detachView(MvpViewState.java:84)
                      at com.arellomobile.mvp.MvpPresenter.detachView(MvpPresenter.java:72)
                      at com.arellomobile.mvp.MvpDelegate.onDetach(MvpDelegate.java:143)
                      at com.arellomobile.mvp.MvpAppCompatActivity.onSaveInstanceState(MvpAppCompatActivity.java:44)
                      at android.app.Activity.performSaveInstanceState(Activity.java:1555)
                      at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1392)
...

Вылетает при переключении на другое приложение (нажатии на home button). Вылетает не всегда, иногда на первый, иногда на третий-четвертый раз переключения.
Иногда та же ошибка вызывает при восстановлении состояния, то есть в attachView().

Кусок кода, в котором происходит данная ошибка:
MVPViewState.java : 
```
    public void detachView(View view) {
	      mViews.remove(view);
	      mInRestoreState.remove(view);
		Set<ViewCommand<View>> currentState = Collections.newSetFromMap(new WeakHashMap<ViewCommand<View>, Boolean>());
		currentState.addAll(mViewCommands.getCurrentState());
		mViewStates.put(view, currentState);
	   }
```

Не совсем понятно, даже чисто теоретически при каких условиях может вылететь эта ошибка?
Дебаггер в режиме логгирования отлавливает заход только одного потока в этот метод, после чего вылетает COncurrentModificationException.

**Comment by senneco** [comment]
Скорей всего у вас зацикленность такого плана:

команда идёт из презентера во вью, вью что-то делать и отправляет команду в презентер, презентер реагирует на это и посылает очередную команду во вью. И тогда получается при восстановлении состояния вью такая ситуация, что вы меняете вью стейт во время его модификации. Оттуда и такая проблема. Необходимо делать так, чтобы вью не меняла презентер изза того, что презентер как-то повлиял на вью.

**Comment by epereskokov** [comment]
Цепочка вью -> презентер -> вью допустима?
Пример: экран чата, пользователь выбирает файл и нажимает "отправить". С вью (активити) идет команда презентеру на загрузку файла на удаленное хранилище, по итогам которой презентер посылает команду на добавление сообщения с файлом в чат/выведение ошибки загрузки. Итого получаем цепочку вью - презентер - вью.

**Comment by senneco** [comment]
Такая цепочка ок, т.к. не идёт изменение состояния вью во время восстановления вью из этого же сотсояния

**Comment by epereskokov** [comment]
А если у нас грузится несколько файлов, к примеру, и презентер по мере загрузки периодически посылает команды на обновление вью (индикатор загрузки, кол-во загруженных файлов, создание нового сообщения), это может происходить и в момент восстановления вью, и в момент записи состояния. Это может быть причиной подобных проблем или все же нет?

Непонятно, что означает "это же состояние"? Если я посылаю команду из презентера, то как определить, состояние вью является измененным или этим же? По сути новые и новые команды добавляются в очередь команд в то время, когда приложение находится в фоне. Я так понимаю, эта ситуация стандартна и должна разруливаться самим фреймворком?

Уточню: сейчас из активити методы презентера у меня вызываются только в случае действий пользователя (клики по кнопкам, выбор файла из галереи при отправке файлов).

**Comment by epereskokov** [comment]
Итак, причина похоже, ясна. Необходимо все изменения вью, которые могут быть инициированы презентером во время отсутствия вью (асинхронные таски, периодические события), вызывать на главном потоке (например runOnUIThread()), иначе при совпадении момента восстановления вью (итерация по всему стеку команд) с моментом добавления новой команды (как раз в этот стек) вылетает ConcurrentModificationException. Этого не произойдет, если операция  вызывается на главном потоке, так как итерация по стеку команд происходит в нем же.
Баг перестал воспроизводится после добавления всех вызовов методов вью в runOnUiThread().
Юрий, спасибо за оперативные ответы. 
Есть предложение добавить исключение при вызове команд вью стейта вне главного потока. В противном случае невнимательный разработчик вроде меня получает трудновоспроизводимые баги в приложении.

**Comment by Yazon2006** [comment]
> Есть предложение добавить исключение при вызове команд вью стейта вне главного потока.
А вроде неплохая идея. Теоретически ведь нету необходимости обращаться к вью вне UI потока? Не знаю, будет ли такая проверка достаточно легковесной, что бы не повлиять на перфоманс и нету ли у нас случаев, когда действительно небходимо обратиться к вью из бекграунда?

**Comment by senneco** [comment]
Имхо, оно того не стоит - чтобы у всех в рантайме проверялось, на каком потоке выполняется команда. Это будет слишком часто. Лучше привыкнуть работать со view state только с main thread.

**Comment by evgenyPereskokov** [comment]
> Имхо, оно того не стоит - чтобы у всех в рантайме проверялось, на каком потоке выполняется команда. Это будет слишком часто. Лучше привыкнуть работать со view state только с main thread.

Из личного опыта - на 3 проектах с совершенно разными разрабами в разных компаниях все совершают эту ошибку. Возможно, хотя бы в доках где-то стоит упомянуть, что вызов вью-стейт методов является изменением UI, а значит, они должны вызываться в главном потоке. Либо можно попробовать как-то исхитриться с помощью аннотации @MainThread вызывать warning в IDE.

**Comment by senneco** [comment]
1. Если проблема из-за того, что какая-то команда отправляется не с main thread, то это всплывёт при первом же вызове (для этой проблемы не обязательно получать её только в тот момент, когда происходит восстановление стейта). А значит тут как бы всё зависит от разработчика, изначально.
2. Если проблема исключительно в восстановлении стейта, то тут как бы точно дело не в асинхронности, а проблема в модификации очереди в момент восстановеления.

Я пробовал распихать @MainThread - это не работает, студия не понимает.

Дайте реальный семпл проблемы, тогда посмотрим =)

**Comment by fAntel** [comment]
> По поводу первого случая - вроде бы не всплывет, я могу с любого потока вызвать метод вью, и он корректно отработает.

Это не отработает корректно, а вызовет исключение `CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views`
