### ISSUE TITLE
multiply modules with kotlin

### ISSUE THREAD

**Issue by tinkooladik** [Arello-Mobile/Moxy#229]
Hi!
I don't understand how to add more then one module in annotation 
![image](https://user-images.githubusercontent.com/13711706/47426081-e44a3400-d794-11e8-8fcc-beabbbfb2c81.png)
I tried to add with braces { } or [ ] or listOf(...), but it shows an error (required String)

I also tried

> @RegisterMoxyReflectorPackages("com.tachcard.login,com.tachcard.settings")

or  

> ("com.tachcard.login, com.tachcard.settings")

 or 

> ("com.tachcard.login;com.tachcard.settings")

 or 

> ("{com.tachcard.login;com.tachcard.settings}")

**Comment by senneco** [comment]
Hi,

Please, try to write some like this:

```@RegisterMoxyReflectorPackages("com.tachcard.login", "com.tachcard.settings")```

(see "Vararg" [there](https://kotlinlang.org/docs/reference/functions.html))

**Comment by tinkooladik** [comment]
> Hi,
> 
> Please, try to write some like this:
> 
> `@RegisterMoxyReflectorPackages("com.tachcard.login", "com.tachcard.settings")`
> 
> (see "Vararg" [there](https://kotlinlang.org/docs/reference/functions.html))

Thank you very much for quick response! Now it works. Feel stupid
Have a nice day :)
