### ISSUE TITLE
Шаблоны (Templates)

### ISSUE THREAD

**Issue by aratj** [Arello-Mobile/Moxy#23]
В шаблонах, еще старые подставляет классы вместо 
MvpAppCompatActivity /MvpAppCompatFragment

**Comment by senneco** [comment]
@xanderblinov что скажешь? Можно впилить, чтобы шаблон определял, есть в dependency moxy-app-compat, или можно только через дополнительную галочку в диалоге создания moxy activity/fragment?

**Comment by xanderblinov** [comment]
@senneco я не нашел способа в шаблоне узнать наличие зависимостей
более удачным вариантом будет дублировать шаблоны и поменять в них логику

как результат, в шаблонах будет 2 папки Moxy и Moxy-Compat

при использовании можно уже будет решать какие из них использовать и на какие назначать hot-keys

**Comment by aratj** [comment]
и еще уточнение, 
а когда используешь шаблон, он сам вставляет зависимости в build.gradle ?
сейчас он вставляет, хотя у меня они там есть, и из-за этого "портит" билд файлик.

**Comment by xanderblinov** [comment]
@aratj все что генерирует шаблон находится в файле [recipe.xml.ft](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-templates/MoxyActivity/recipe.xml.ftl) (на примере MoxyActivity, для MoxyFragment соответствующий файл)

Можете кастомизировать его под себя

**Comment by aratj** [comment]
Ок, в принципе я его и смотрел
