### ISSUE TITLE
Отсутствие ссылки на ViewState

### ISSUE THREAD

**Issue by JorikFat** [Arello-Mobile/Moxy#234]
При использовании фрагмента вызываю 
```
public class NewQueryFragment extends MvpAppCompatFragment implements NewQueryView{
...
        public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);
            presenter.viewReady();//работает хорошо
        }
...
}
```
Когда пытаюсь вызвать эту же конструкцию в `MvpAppCompatDialogFragment` - метод `presenter.viewReady()`; вызывается, но внутри не выполняется ничего с `getViewState()`. Используя Debug понял, что к presenter'у не привязывается ни одна View.
В какой момент работы `MvpAppCompatDialogFragment` presenter связывается с `viewState`?

**Comment by senneco** [comment]
Аттачится в момент вызова `AppCompatDialogFragment.onResume`

**Comment by JorikFat** [comment]
При этом в обычном MvpAppCompatFragment это происходит в onViewCreated()?

**Comment by JorikFat** [comment]
Почему тогда приведенный выше [код](https://github.com/Arello-Mobile/Moxy/issues/234#issue-381933087) работает нормально?

**Comment by senneco** [comment]
View значит ещё не приаттачена. А затем, когда она будет приаттачена, вью стейт обязан выполнить на ней ту команду, которая была отправлена из презентера во вью стейт. Дебаг должен больше помочь с пониманием того, что пошло не так.

**Comment by JorikFat** [comment]
Спасибо
