### ISSUE TITLE
Nested fragment leak when replace

### ISSUE THREAD

**Issue by CherryPerry** [Arello-Mobile/Moxy#24]
I have fragment with view pager with fragments. Each of them contains presenter. When this fragment is replaced with another one, only fragment's presenter that contains view pager is destroyed, but nested fragment's presenters not.

[Demonstration of leak with possible fix](https://github.com/CherryPerry/Moxy-nested-leak)

**Comment by CherryPerry** [comment]
I think, it is required to fix default android SDK fragment too, but I have not checked this problem yet.

**Comment by senneco** [comment]
mvp-android with MvpFragment fixed too in 1.0.2

**Comment by NoNews** [comment]
@senneco
 А исправлен ли `MvpAppCompatFragment`?

**Comment by senneco** [comment]
It has been fixed a long time ago too =)
