### ISSUE TITLE
Incremental annotation processing

### ISSUE THREAD

**Issue by IvanShafran** [Arello-Mobile/Moxy#240]
Hi!
[The gradle 4.7 supports incremental annotion processing with some limitations.](https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing)
Is it possible to use this feature for Moxy?

**Comment by bejibx** [comment]
Hi, everyone should consider using [this](https://github.com/moxy-community/Moxy) fork, where all new development is going. It also already supports incremental compilation.

**Comment by xanderblinov** [comment]
https://github.com/moxy-community/Moxy/blob/develop/CHANGELOG.md#added-1
