### ISSUE TITLE
Как подключить два презентера для одного фрагмента 

### ISSUE THREAD

**Issue by s-ilnar** [Arello-Mobile/Moxy#253]
Есть презентер выбора фотографий. Хочу переиспользовать этот презентер в нескольких местах. 
Или лучше для каждого экрана где есть выбор картинки из (галереи, камеры) копировать код?

Как подключить два презентера для одного фрагмента?

**Comment by senneco** [comment]
Ответ невероятно прост - просто заинжектите в один фрагмент 2 презентера и реализуйте в этом фрагменте оба интерфейса view =)

**Comment by s-ilnar** [comment]
Да, действительно) 
Думал что в Moxy это делается как то по другому - по волшебству :D

Спасибо)
