### ISSUE TITLE
Стратегия удаляющая определенные методы из очереди

### ISSUE THREAD

**Issue by s-ilnar** [Arello-Mobile/Moxy#255]
Может быть уже есть такая стратегия? И кто то для себя делал.. Если есть, поделитесь, пожалуйста.

Есть методы:
**showMarkers(List<?> data);** // условно долгая отрисовка
**clearMarkers();** //после выполнения этого метода нам не нужны предыдущие **showMarkers()** , незачем выполнять ненужную долгую UI работу.

Но чистить весь стек стейтов нельзя т.к. некоторые действия нам нужно восстанавливать.

p.s. может нубский вопрос и решается очень легко, но я в мокси не так давно

**Comment by senneco** [comment]
Вы можете сделать стратегию, похожую на эту: https://gist.github.com/senneco/98a532df9915901da8065448722cef9f#file-addtoendsinglebytagstatestrategy-java . Но придётся модифицировать немного под себя.

Но осмелюсь сказать, что это Не "долгая UI работа", потому что все команды применяются До отрисовки на экран. Значит, это происходит чрезвычайно быстро. И значит нет ничего страншого =)

Иначе просто сделайте один метод setMarkers() и передавайте пустой список, когда нужно подчистить. И всё =) Её можно сделать со стратегией AddToEndSingleStateStrategy

**Comment by s-ilnar** [comment]
Понял, спасибо за полезную подсказку!.
