### ISSUE TITLE
LoadingView и несколько презентеров

### ISSUE THREAD

**Issue by s-ilnar** [Arello-Mobile/Moxy#257]
Возможно, некорректно что пишу вопрос тут. Но все же, думаю каждый с mvp сталкивался с таким. Может поможете советом. Если нет, то просто удалите вопрос. Спасибо.)

Использую Moxy для реализации MVP.

Первый вопрос: Такая ситуация. Есть активити(вью) реализующий интерфейс Loadingable к которой привязываются 2 презентера. (Loadingable имеет методы show(Disposable d) и hide())

Есть два презентера и в обоих из них выполняется запрос на сервер(в один момент), в этот момент оба презентера отправляют во вью команду показать LoadingView и соответственно при завершении отправляют команду скрыть LoadingView.

Во вью, LoadingView один для всех.

Коллизие в том что: первый презентер может отправить команду на закрытие, в тот момент пока второй презентер все ещё получает данные. Логичнее скрывать LoadingView после выполнения запросов в обоих презентерах.

Может есть best practices как решить этот вопрос?

Второй вопрос: Мой LoadingView это cancelable Dialog с прозрачным темным фоном. При вызове show, я передаю туда disposable(rxJava) и если пользователь закрывает этот LoadingView то происходит disposable.dispose() т.к. операция далее не актуальна. Практикуете такое? Как подружить такое с первым вопросом?)

**Comment by senneco** [comment]
1. Сколько людей, столько и мнений. Но мне кажется не правильно делать Loadingable. Особенно если у вас есть возможность обновить экран через swipe-to-refresh. Потому что тогда придётся много городить в Activity. Я бы советовал пересмотреть ваш подход на подход с отдельным интерфейсом View на каждый Presenter. Или заверните всё в один Presenter.

2. Не советую тащить disposable во View. Всё оставьте в Presenter. А во View - только команды и данные для отображения.
