### ISSUE TITLE
Moxy генерирует файл с неверным именем

### ISSUE THREAD

**Issue by max75758231** [Arello-Mobile/Moxy#264]
Привет. Использую версию 1.7.0.
Возникла такая проблема, что либа генерит файл с неверным именем. То есть, я использую `MainActivity`, `MainPresenter`, `MainView`

`public class MainActivity extends MvpAppCompatActivity implements MainView.View`

    `@StateStrategyType(AddToEndSingleStrategy.class)
    interface View extends MvpView {

    }

    interface Presenter {

    }`

В итоге, Moxy должен сгенерить один из файлов с именем, на что и указывает ошибка:
`error: cannot find symbol class MainView$View$$State`
А генерит файл с именем `View$$State`

Подскажите, это я делаю что-то не так или баг в либе?
P.S. Использую версию 1.7.0, так как нужен androidX

**Comment by max75758231** [comment]
Понял, что написал не туда

**Comment by bios90** [comment]
Сталкиваюсь с точно такой же ошибкой, подскажи нашел решение?)

**Comment by max75758231** [comment]
> Сталкиваюсь с точно такой же ошибкой, подскажи нашел решение?)

Я нагуглил, что нужно смотреть в сторону [этой либы](https://github.com/moxy-community/Moxy)
Но мне показалось это костылем (я потыкал, не понравилось) и я решил отказаться от AndroidX пока и подождать нормального релиза.

**Comment by bios90** [comment]
Спасибо за ответ, официальный [https://github.com/Arello-Mobile/Moxy/wiki/Getting-started](Getting Started) не собирается вообще на Kotlin не зависимо androidx/support
