### ISSUE TITLE
StateStrategy for "clearable" ViewCommands

### ISSUE THREAD

**Issue by alextel69** [Arello-Mobile/Moxy#28]
Let's examine this use-case: presenter adds group of markers to map, removes some of them afterwards, some - not. This process may repeate multitude of times, then orientation changes, and ViewState is reapplied to newly attached View. From user perspective it would be lengthy process of repeating all actions user had done, while he just needs markers which "survived" removal. 

To solve this issue it would be great to add one more `StateStrategy` - `TraceStrategy` and `ClearStrategy` (counterpart)

For example, let's have a method:

```
public class MapView implements MvpView {
   /*
   * Some other code
   */
   private int counter = 0;

   @StateStrategy(value = TraceStrategy.class, tag = "addMarker")
   int addMarker(double lat, double lon) {
      // ...
      return counter++;
   }
}
```
In result of this `ViewCommand` on top of `ViewCommand` stack new `ViewCommand` should be added with tag = "addMarker0". Running this command again will result in `ViewCommand` with tag = "addMarker1" and so on. Number is value returned by method (more generally - `toString()` of returned `Object`).

Now counterpart for `addMarker` will be 
```
public class MapView implements MvpView {
   /*
   * Some other code
   */
   private int counter = 1; // Affected by addMarker()

   @StateStrategy(value = ClearStrategy.class, tag = "addMarker")
   int removeMarker(int id) {
      // ...
      return --counter;
   }
}
```
This `ViewCommand` appends to tag returned value than searches `ViewCommand` with tag whose value is, for instance, "addMarker0", removes it and **does not** put itself in stack.

Drawbacks of this approach are:

- Proguard should handle tag of ClearStrategy appropriately

- remove* methods shoud return its argument

P.S. 
If there is no return value required, for example, just one marker can be added, than `TraceStrategy` and `ClearStrategy` should also take care of this.

P.P.S
Issue instead of PR because I think there is discussion part in this issue.

**Comment by senneco** [comment]
Hi,

First, View methods should be void, a discussion is [here ](https://github.com/Arello-Mobile/Moxy/issues/2) =)

Next, your MvpView should be interface. And then your can't put there some logic. You should put it in your presenter. Then your code can be changed like this:

```java
public interface MapView extends MvpView {
	@StateStrategyType(AddToEndStrategy.class)
	void addMarker(long id, double lat, double lon);

	@StateStrategyType(RemoveByIdParameter.class)
	void removeMarker(long id);
}
```

```java
public class RemoveByIdParameter implements StateStrategy {
	@Override
	public <View extends MvpView> void beforeApply(List<ViewCommand<View>> list, ViewCommand<View> viewCommand) {
		for (ViewCommand<View> existingViewCommand : list) {
			if (existingViewCommand.getTag().equals("addMarker")) {
				if (((MapView$$State.AddMarkerCommand) existingViewCommand).id == ((MapView$$State.RemoveMarkerCommand) viewCommand).id) {
					list.remove(existingViewCommand);
					return;
				}
			}
		}
	}

	@Override
	public <View extends MvpView> void afterApply(List<ViewCommand<View>> list, ViewCommand<View> viewCommand) {
		// pass
	}
}
```

BUT! Currently generated `MapView$$State.AddMarkerCommand` and `MapView$$State.RemoveMarkerCommand` are private. I don't know why is it, seems like wrong code (because fields are public =) ). It will be fixed in short time.

Or is issue in something else?

**Comment by alextel69** [comment]
@senneco thanks for point with method return value. I think there is a flaw in my MVP implementation.

However, my intention was to create some generic `StateStrategy` (independent of methods attached). 
Now it seems in order to do this

-  User will need to manually buffer incoming id in `put*` method for `StateStrategy` to "see" what to add to tag, then buffer it once more in `remove*` method for `StateStrategy` to "see" what to remove

- Introduce contract that `put*` and `remove*` method should have parameter with object called id, intercept it with reflection during `beforeApply`. Degrades performance. Also unclear with Proguard

**Comment by senneco** [comment]
These strategies are more individual.  They are not be included in library. But it's great gists for future, for personal cases. May be more flexible solution will be made in future.

PS: currently moxy 1.0.3 generates public command classes!
