### ISSUE TITLE
@InjectPresenter(type=PresenterType.GLOBAL) requires tag value

### ISSUE THREAD

**Issue by micdm** [Arello-Mobile/Moxy#3]
Is it possible to not set the tag value (leave it "" as default) but have a single global Presenter? `@InjectPresenter(type=PresenterType.GLOBAL)` vs `@InjectPresenter(type=PresenterType.GLOBAL,tag="tag")` if I actually need single Presenter of such type around the application.

**Comment by senneco** [comment]
If you want to use single presenter around the application, you should set not empty tag to field.

**Comment by micdm** [comment]
Yes I see that now the tag should be set anyway. But less code is better right? It's probably possible to remove TextUtils.isEmpty check and allow to create a global presenter with no tag specified by default.

**Comment by senneco** [comment]
The problem is this. If not specified, we do not know the user wants presenter was one of the specified class or one presenter with the name of this variable.

I.e. one user will assume that in this case there will be one presenter, but other users will think that there will be two different presenter:

```
public class OneActivity extends MvpActivity
{
    @InjectPresenter(type=PresenterType.GLOBAL)
    GlobalPresenter mOneGlobalPresenter;
...

public SecondActivity extends MvpActivity
{
    @InjectPresenter(type=PresenterType.GLOBAL)
    GlobalPresenter mSecondGlobalPresenter;
...
```

**Comment by micdm** [comment]
Alright it's a matter of taste. It is not a big deal to write `@InjectPresenter(type = PresenterType.GLOBAL, tag = "global")` always and show the presenter's oneness explicitly.
