### ISSUE TITLE
Injecting dependencies into presenter

### ISSUE THREAD

**Issue by bmourat** [Arello-Mobile/Moxy#30]
I'am trying to find out proper way of injecting dependencies into presenter. Since passing dependencies in constructor is not an option we need to use some other mechanism.  If we'll take a look at MoxySample, for example at SignInPresenter

 ```@InjectViewState
  public class SignInPresenter extends MvpPresenter<SignInView> {
	@Inject
	Context mContext;
	@Inject
	GithubService mGithubService;

	public SignInPresenter() {
		GithubApp.getAppComponent().inject(this);
	}
        //...
 ```

we will see that injection is happening in constructor of presenter. But this line devaluates the whole point of DI process, since we are introducing unnecessary dependency from GithubApp. And also this prevents presenter from being tested properly. 
Another place to call component's inject method would be from activity/fragment onCreate method but this would cause reinjecting dependencies each time activity or fragment is recreated, including orientation change, which is also not good. So can you suggest preferred way of passing dependencies?

**Comment by senneco** [comment]
Hi,

Currently we working on solution like this. Now we research solution like this:

```java
@InjectPresenter(presenterId="some-id")
NewsPresenter mNewsPresenter;

@ProvidePresenter(presenterId="some-id")
public NewsPresenter providePresenter() {
    return new NewsPresenter();
}
```

This method will be called from MvpDelegate only if Moxy didn't contains proper presenter instance. That means that if view will be recreated, this method won't be called.

Known sub-issue is that require additional research is it ok or not to call this method when called MvpActivitry.onCreate(). There will be available only intent, arguments, context, activity. It's may do some misunderstanding, but I don't think.

PS: currently you can make it via PresenterFactory, but it's heavy, unobvious solution ;)

**Comment by bmourat** [comment]
This solution seems nice. Any info on when it will be released?

**Comment by senneco** [comment]
Don't know.. In progress =)

**Comment by bmourat** [comment]
Ok, thanks :)

**Comment by senneco** [comment]
Done! More info [here](https://github.com/Arello-Mobile/Moxy/wiki/Provides-Presenter-and-its-Tag),

If this wiki is not clear, let me know, please =)
