### ISSUE TITLE
Совсем простой пример.

### ISSUE THREAD

**Issue by crysan** [Arello-Mobile/Moxy#33]
Здравствуйте!

ЕСЛИ НЕ СЛОЖНО, то
можете привести совсем простой пример с использованием архитектуры Moxy?
Как например, в одной активити две кнопки и слой RelativeLayout. При нажатии на кнопки, в слой загружается один из двух фрагментов.
Интересует реализация задачи с позиции Моху и сохранении жизненного цикла.

СПАСИБО!

**Comment by senneco** [comment]
Добрый день,

Кажется, вам будет достаточно посмотреть пример. Например, [экран авторизации](https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/activities/SignInActivity.java
). На этом экране как раз есть кнопка, поля ввода, прогресс и диалог с ошибкой.

**Comment by crysan** [comment]
К сожалению, начинающий, в вашем примере ногу сломит. Он избыточен.
Поэтому я и спросил про простой законченный пример как приложение.

Пример с экраном авторизации можно вынести в законченное приложение? Без RxJava!

**Comment by crysan** [comment]
Скажите, стоит ждать пример или закроете вопрос?

**Comment by senneco** [comment]
Да, ждите – у меня дома есть микро-сэмпл. Может он подойдёт =)

**Comment by crysan** [comment]
Благодарю! Жду.

**Comment by senneco** [comment]
https://gist.github.com/senneco/a91bd53f257c0fddda6e47f7de9a9fb8

PS: т.к. для вас сложным выглядит пример экрана авторизации, ИМХО, лучше пока не суйтесь во фрагменты ;)

**Comment by crysan** [comment]
Шикарно!
Переделал прогресс бар на линейный - поворот девайса отрабатывает как надо.
Спасибо!
Двигаюсь дальше.

**Comment by crysan** [comment]
Нашел на хабре вот что:

> Ещё, Moxy не решит проблем с commit() фрагментов после выполнения onSaveInstanceState(). Поэтому не забудьте закрывать транзакцию, используя commitAllowingStateLoss(). 

Выходит, что при использовании Moxy данные фрагментов автоматом не сохраняются? Тогда придется делать приложение на одних активити без фрагментов? Или я не верно понял?

> Так же, она не решит проблем с утечкой памяти – если вы передадите ссылку на Context/Activity/Fragment в Presenter(а потом ещё и во ViewState), то память может утечь. Будьте аккуратны.

Как быть в данном случае аккуратным?

**Comment by crysan** [comment]
> Обратите внимание на то, что к одному Presenter может быть привязано несколько View.

Как?

**Comment by senneco** [comment]
1. Нет, commitAllowingStateLoss() совсем про другое. Когда разберётесь, зачем нужен этот метод во FragmentTransaction. А чтобы сохранялось состояние view-фрагмента, достаточно наследовать его от MvpFragment/MvpAppCompatFragment(ну или конечно ручками подергать методы MvpDelegate).
2. Не передавать ссылку на Activity/Context внутрь Presenter.
3. Чтобы привязать несколько View к одному Presenter, необходимо чтобы он был глобальным. Тогда в @InjectPresenter можно указать один и тот же tag, и тогда будет использоваться один экземпляр глобального Presenter.

**Comment by crysan** [comment]
на 3 можно код?

**Comment by senneco** [comment]
https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/fragments/DetailsFragment.java
https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/adapters/RepositoriesAdapter.java

Используется один экземпляр RepositoryLikesPresenter
https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/fragments/DetailsFragment.java
https://github.com/Arello-Mobile/Moxy/blob/master/sample-github/src/main/java/com/arellomobile/mvp/sample/github/ui/adapters/RepositoriesAdapter.java

**Comment by crysan** [comment]
Хм...
Смотрите

Есть активити
`public class HelloActivity extends MvpAppCompatActivity implements HelloView`

есть фрагмент
`public class NewsFragment extends MvpAppCompatFragment implements NewsView`

и есть презентер
`public class HelloPresenter extends MvpPresenter<HelloView>`

Как видно, презентер привязан к HelloView
Но в нем есть код, который я могу вызвать и в активити и во фрагменте (у которого свой NewsView). Но даже не догоняю как.

**Comment by senneco** [comment]
Чтобы вы могли вызвать из HelloPresenter какой-то метод NewsFragment, этот NewsFragment должен имплементить HelloView, и этот метод должен быть объявлен в HelloView. Потому что HelloPresenter типизирован HelloView. И сгенерированный ViewState для HelloPresenter будет имплементить тот же самый HelloView. Что из этой связки не понятно – я не понимаю 😄

**Comment by crysan** [comment]
Это понятно.
Может я не так выразился. Попробую еще раз.
Вот презентер:
```
@InjectViewState
public class HelloPresenter extends MvpPresenter<HelloView>{
    public HelloPresenter() {
        getViewState().toggleMessageLoading(true);
    }

    public void onGo(){
        new AsyncTask<Void, Void, Void>(){
            @Override
            protected Void doInBackground(Void... voids) {
                try {
                    for (int i=1; i<=20; ++i) {
                        TimeUnit.SECONDS.sleep(2);
                        getViewState().setProgressBar(i);
                    }
                } catch (InterruptedException e) {
                    // pass
                }

                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) { }
        }.execute();
    }
}
```
Что он делает понятно. 
В активити и фрагменте есть свой прогресс бар.  Нужно, чтобы процедура onGo в презентере выполнялась и для бара активити и для бара во фрагменте.

активити:
```
public class HelloActivity extends MvpAppCompatActivity implements HelloView {

    @InjectPresenter(type = PresenterType.GLOBAL)
    HelloPresenter mHelloPresenter;

    private TextView mMessageTextView;
    private ProgressBar mProgressBar;
    private Button btn;
    private RelativeLayout lContainer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hello);

        mMessageTextView = (TextView) findViewById(R.id.text_view_message);
        mProgressBar = ((ProgressBar) findViewById(R.id.progress_bar));
        btn = ((Button) findViewById(R.id.btn));
        lContainer = ((RelativeLayout) findViewById(R.id.lContainer));

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mHelloPresenter.onGo();
                getSupportFragmentManager().beginTransaction().setCustomAnimations(android.R.anim.fade_in, android.R.anim.fade_out, android.R.anim.fade_in, android.R.anim.fade_out).replace(R.id.lContainer, new NewsFragment(), "NewsFragment").commit();
            }
        });
    }

    @Override
    public void showMessage(@StringRes int messageResId) {
        mMessageTextView.setText(messageResId);
    }

    @Override
    public void setProgressBar(int progress) {
        mProgressBar.setProgress(progress);
    }

    @Override
    public void toggleMessageLoading(boolean isLoading) {
        mProgressBar.setVisibility(isLoading ? View.VISIBLE : View.GONE);
        mMessageTextView.setVisibility(isLoading ? View.GONE : View.VISIBLE);
    }
}
```
фрагмент:
```
public class NewsFragment extends MvpAppCompatFragment implements NewsView {
    @InjectPresenter
    HelloPresenter mHelloPresenter;

    private ProgressBar fragment_progress_bar;

    public NewsFragment() {

    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        fragment_progress_bar = ((ProgressBar) getActivity().findViewById(R.id.progress_bar));
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mHelloPresenter.onGo();
        return inflater.inflate(R.layout.fragment_news, container, false);
    }


    @Override
    public void setProgressBar2(int progress) {
        fragment_progress_bar.setProgress(progress);
    }
}
```

**Comment by senneco** [comment]
Такой код не соберётся, потому что вы инжектите презентер в класс, который не реализует интерфейс, которым типизирован презентер. Таким образом ваш NewsFragment **обязан** implrements HelloView.

**Comment by crysan** [comment]
Вот теперь ясно почему не собирается.
Спасибо!

**Comment by crysan** [comment]
Ммм...
Вопрос решил по другому. Но
**jeksor**
Как использовать HelloPresenter для NewsFragment (из записи выше)?

**Comment by jeksor** [comment]
Презентер работает только с вьюшками (интерфейс MvpView или его наследник),
тип которой указан у него Generic параметре.

Это значит, что любой объект, например Activity, Fragment и т.д., который
реализует этот интерфейс X, может инжектировать себе соответствующий
Presenter<X>.

Чтобы ответить на Ваш вопрос, убедитесь, что
NewsFragment реализует правильный интерфейс View, которым параметризован
презентер HelloPresenter. После этого заинжектите его в NewsFragment.
В Moxy нет ограничения на количество инжектируемых презентеров в одном
классе.

Напомню, что в Java можно реализовывать несколько интерфейсов в одном
классе. Например один фрагмент может имплементить и NewsView, и HelloView.

**Comment by crysan** [comment]
Спасибо за развернутый ответ!
И еще вопрос: Как с фрагмента запустить операцию (что описана во вьюшке активити) в активити?

**Comment by iamthevoid** [comment]
Я бы тоже хотел задать вопрос по GLOBAL Presenter. Допустим есть активити и нестед фрагмент, оба имплементят один и тот же интерфейс MvpView и мы можем дергать методы презентера и оттуда и оттуда. Вопрос же в следующем. attachView вызывается в активити, но активити в таких случаях обычно используется в качестве контейнера, то есть вся информация находится внутри фрагмента. Соответственно ожидаемо и разумно, если attachView будет вызываться и внутри фразмента (тем более он должен приаттачиваться фактически), и в этот момент инитить содержимое. Но либо я что то не так делаю, либо этого не происходит. Каким образом можно разрешить эту ситуацию?

**Comment by iamthevoid** [comment]
Хм, сделал это реализовав внутри фрагмента пример отсюда https://github.com/Arello-Mobile/Moxy/wiki/CustomView-as-MvpView
