### ISSUE TITLE
presenter при повороте экрана

### ISSUE THREAD

**Issue by bogdanovkp** [Arello-Mobile/Moxy#35]
Имеется активити с проигрыванием видео-потока с возможностью выбора архива видео. Проигрывание видео начинается в onCreate через вызов презентера, потом условно выбираю проигрывание архива, поворачиваю экран, продолжает играть онлайн, а не архив.
онлайн видео при создании:

в активити в onCreate вызывается метод getCamera, в котором получаем ссылку на stream-поток.
```java
 protected void onCreate(final Bundle savedInstanceState) {
     videoPlayPresenter.getCamera(cameraId);
      }
```

```
public void getCamera(Long camId){
        String cookie = "JSESSIONID=".concat(AuthUtils.getSessionId()).concat("; XSRF- TOKEN=").concat(AuthUtils.getToken()).concat("; remember- me=").concat(AuthUtils.getRememberMe());
         final Observable<BackendData> observable = RxUtils.wrapRetrofitCall(service.getCamera(cookie,  AuthUtils.getToken(), camId, false));
         RxUtils.wrapAsync(observable)
                  .subscribe(
                          backendData -> {
                              ObjectMapper mapper = new ObjectMapper();
                              CameraSmallDTO cameraSmallDTO = mapper.convertValue(backendData.getData(),   CameraSmallDTO.class);
                             getViewState().getCamera(cameraSmallDTO);
                         },
                          throwable -> showError()
                   );
    }
```

Если все хорошо, вызывается метод в getCamera из активити и в нем вызывается метод play из презентера для проигрывания видео.
```
  @Override
     public void getCamera(CameraSmallDTO camera) {
         cameraSmallDTO = camera;
         rtmpLink = cameraSmallDTO.getInfo().getUrl();
         devCode = cameraSmallDTO.getKey();
         videoPlayPresenter.play(rtmpLink, false, null, null);
     }
```
Когда я хочу проиграть архив, я выбираю время и в активити вызываю метод play из презентера, в нем запрашивается новая ссылка на stream-поток, если это архив или продолжает играть онлайн.
```
 public void play(String path, boolean flagArchive, Long camId, Date date){
        if (camId != null && date != null){
            DateFormat df = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            String dateStart = df.format(date);
            Calendar calendar  = Calendar.getInstance();
            calendar.setTime(date);
            calendar.add(Calendar.MINUTE, 10);
            String dateStop = df.format(calendar.getTime());
            String cookie = "JSESSIONID=".concat(AuthUtils.getSessionId()).concat("; XSRF-TOKEN=").concat(AuthUtils.getToken()).concat("; remember-me=").concat(AuthUtils.getRememberMe());
            Observable<BackendData> observable = RxUtils.wrapRetrofitCall(service.getStreamArchive(cookie, AuthUtils.getToken(), camId, dateStart, dateStop, true));
            RxUtils.wrapAsync(observable)
                    .subscribe(response ->
                                    getViewState().play(response.getData().toString(), true),
                            throwable -> getViewState().play(path, false)
                    );
        } else getViewState().play(path, flagArchive);
    }
```
Если я выбрал играть архив, и повернул экран - начинает ссылка на онлайн, а не архив онлайн

**Comment by senneco** [comment]
По приведенному коду совсем не понятно, что где происходит. Если подчистите код от лишних дествий, и понятней укажите где какой метод находится, то может быть я смогу помочь ;)

**Comment by bogdanovkp** [comment]
соответственно в методе play презентера вызывается метод play в активити

**Comment by bogdanovkp** [comment]
в общем мне нужно чтобы при повороте экрана игралась та ссылка на видео, которая последней игралась до поворота

**Comment by senneco** [comment]
Всё-равно не понятно что вы делаете -- вы накидали в вопросе какие-то куски кода и толком не понять что где происходит. Но попытаюсь помочь:

Вы в onCreate передаете команду в презентер. Но onCreate вызывается не только при первом старте активити, но и при повороте экрана. А нужно вызывать только один раз. Поэтому надёжней в конструкторе презентера вызвать то, что должно происходить вначале. Если нужны параметры для инициализации презентера, то либо делаете метод, помеченный @ProvidePresenter, либо делаете в презентере метод init, в котором проверяете проинициализирован или нет презентер. И если не проинициализирован, то делает инициализируете и запускаете ту работу, которую нужно сделать на старте. Иначе ничего не делаете.

Если это не поможет, то формулируйте вопрос и код так, как-будто задаете его людям, котоыре совсем не знают что у вас происходит и контекст, в котором вы задаёте вопрос ;)

**Comment by senneco** [comment]
Возможно, я понял суть вашего вопроса. Дело в том, что в вашем случае onStart/onStop так же должен обработать Presenter -- вот и всё =) Вот микро-пример. В нём при старте плеер начинает что-то проигрывать, а при остановке -- прекращает. А после пересоздания опять начинает проигрывание. https://gist.github.com/senneco/7aa086ba23c6ef2b37eabc623f21a7d4

**Comment by bogdanovkp** [comment]
спасибо, завтра попробую!

**Comment by bogdanovkp** [comment]
разобрался, все получилось, натолкнули на нужные мысли) Спасибо!
