### ISSUE TITLE
Moxy failed at screen rotation

### ISSUE THREAD

**Issue by ValeriusGC** [Arello-Mobile/Moxy#39]
Можно по-русски, да?
Здрасьте.
Как-то при повороте экрана [не очень сохраняется state](https://youtu.be/VKKA1sevdZM)
как на эмуляторе (API-24), так и на зверьке (API-17).
Все на видео.
Причем в ланшафтном режиме кнопка "далее" тоже не переводит к следующему полю.
В чем может быть дело?
С уважением, ВВК

**Comment by senneco** [comment]
Fixed. Thanks for issue!

**Comment by ValeriusGC** [comment]
А в связи с чем упростили форму ввода - убрали модные поля? Это тоже как-то было связано с ошибками?

**Comment by senneco** [comment]
Change layout to simplify. And it seems like AutoCompleteTextView is a reason why "Next" button not working.
