### ISSUE TITLE
lateinit property Presenter has not been initialized

### ISSUE THREAD

**Issue by jamesvanhallen** [Arello-Mobile/Moxy#41]
routesPresenter.getRoutes("18089") thrown exception:

_kotlin.UninitializedPropertyAccessException: lateinit property routesPresenter has not been initialized_

```kotlin
class MainFragment: MvpAppCompatFragment(), RoutesView {
    @InjectPresenter
    lateinit var routesPresenter: RoutesPresenter

    var adapter: RoutesAdapter = RoutesAdapter()

    companion object{

        fun newInstance(): MainFragment {
            return MainFragment()
        }

    }

    override fun onCreateView(inflater: LayoutInflater?, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        App.appComponent.inject(this)
        val v = inflater?.inflate(R.layout.fragment_main, container, false)
        return v
    }

    override fun onViewCreated(view: View?, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        recyclerView.layoutManager = LinearLayoutManager(activity)
        recyclerView.adapter = adapter

        routesPresenter.getRoutes("18089")

    }

    override fun onSuccess(list: List<Route>) {
         Log.d("MainFragment", "onSuccess")
        adapter.setItems(list)
    }

    override fun onEmptyData() {
        Log.d("MainFragment", "onEmpty")
    }

    override fun onError(e: Throwable) {
        Log.e("MainFragment", "error ${e.message}" )
    }
}`

**Comment by senneco** [comment]
What is exception?

**Comment by jamesvanhallen** [comment]
kotlin.UninitializedPropertyAccessException: lateinit property routesPresenter has not been initialized

**Comment by CherryPerry** [comment]
Do you use `kapt` in your gradle file for moxy compiler?

**Comment by jamesvanhallen** [comment]
`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support:design:25.0.0'
    testCompile 'junit:junit:4.12'

    //kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    // Dagger 2
    compile 'com.google.dagger:dagger:2.4'
    kapt 'com.google.dagger:dagger-compiler:2.4'

    //Retrofit
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'

    //rx
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'

    //other
    compile 'com.squareup.picasso:picasso:2.5.2'

    //moxy
    compile 'com.arello-mobile:moxy-app-compat:1.1.1'
    kapt 'com.arello-mobile:moxy-compiler:1.1.1'
    }`

**Comment by CherryPerry** [comment]
Add to your gradle file
```groovy
kapt {
    generateStubs = true
}
```

**Comment by xanderblinov** [comment]
It should be problem of kapt2. Try to switch to kapt. (Don't use apply plugin kapt, and use generate stubs block)

**Comment by jamesvanhallen** [comment]
CherryPerry , tnx!

**Comment by CherryPerry** [comment]
@jamesvanhallen 
Hm, I deleted my comment about `generateStubs` because Dagger works.
Does not Dagger require `generateStubs` too?

**Comment by jamesvanhallen** [comment]
dagger2 works well

**Comment by senneco** [comment]
@jamesvanhallen is it working?

**Comment by xanderblinov** [comment]
Both kapt and kapt2 go problems. Its may work properly with one annotation processor and have bugs on other one. Unfortunately kap2 really doesn't stable with kotlin.

Most stable configuration is kapt with generate stubs

```groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"

    defaultConfig {
        applicationId "com.redmadrobot.moxysamplekotlin"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
kapt {
    generateStubs = true
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile project(':moxy')
    compile project(':moxy-android')
    kapt project(':moxy-compiler')
    testCompile 'junit:junit:4.12'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
```

**Comment by xanderblinov** [comment]
@CherryPerry you may add this config to #42 issue

**Comment by senneco** [comment]
@jamesvanhallen if it's not working, reopen issue or create new, pls.

**Comment by jamesvanhallen** [comment]
it works after kapt 'com.arello-mobile:moxy-compiler:1.1.1' adding

2016-11-03 18:25 GMT+03:00 Yuri Shmakov <notifications@github.com>:

**Comment by Arash-gm** [comment]
I have same issue, when i change orientation and call a funtion from presenter , kotlin throws : lateinit property Presenter has not been initialized , as you said i remove kapt plugin but it keep throwing error : 

    Error:Execution failed for task ':data:compileReleaseJavaWithJavac'.
> kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
