### ISSUE TITLE
Not an issue But

### ISSUE THREAD

**Issue by akbarsha03** [Arello-Mobile/Moxy#43]
This looks very similar to the mosby library by hannes.. Could you please tell me what advantages i would've if i upgrade to moxy?

**Comment by senneco** [comment]
Hi! Well, before make Moxy, I was researched. Mosby was most favourite library. But I not be fully agree with Mosby in some cases. Then we made Moxy with advantages:

You shouldn't be careful about activity/fragment recreate. You should not disable activity recreates or make your fragment retain. Only extends from MvpAcitivty, MvpFragment, e.t.c. or call MvpDelegate methods.

You can inject many presenters to one Activity, Fragment and other MvpView implementation.

ViewState is fully automatically. You should only apply @InjectViewState to MvpPresenter class. No enums, switch-case, flags, e.t.c.

Data of view commands shouldn't be serializable/parcelable. You can use plain object in your MvpView methods.

Boilerplate code is generated at compile time.
