### ISSUE TITLE
Кастомный MvpPresenter

### ISSUE THREAD

**Issue by NoNews** [Arello-Mobile/Moxy#45]
Здравствуйте!
Очень хочется инжектить модели к пресентерам через BasePresenter, унаследовав его от MvpPresenter. (По аналогии с BaseActivity/BaseFragment). А из самих презентеров вызывать уже готовые модели.
Возможно ли это в Moxy?

**Comment by senneco** [comment]
Здравствуйте,

Да, вы можете так сделать. Вам только придется решить задачу, как непосредственно инжектить модель, но это уже задача не мокси :)

**Comment by xanderblinov** [comment]
Посмотрите на dagger 2. Он идеально подходит для Вашей задачи

**Comment by NoNews** [comment]
Я знаю про Dagger2.
Тут речь о том, что обычно я инжекчу модели с помощью него только в BaseActivity/BaseFragment. А использую уже в начледниках. В случае с презентарами приходится инжектить модели в каждом презентере отдельно. (Например я точно знаю, что буду использовать restClient во всех презентерах - я инжекчу его отдельно в каждый презентер через Dagger2.

**Comment by NoNews** [comment]
Вот пример BaseActivity:

   @Inject protected RestApi restApi;
    @Inject protected GeoHelper geoHelper;
    @Inject protected DataChecker dataChecker;
    @Inject protected Preferences preferences;
    @Inject protected Pubnub pubnub;
