### ISSUE TITLE
[Vote] Presenters scope.

### ISSUE THREAD

**Issue by senneco** [Arello-Mobile/Moxy#46]
Hi,

We think about new feature. We want to make able to put presenter to some scope. Until scope will be closed  these presenter instances will be injected. And allow delegate to close scope. And then presenters of scope will be destroyed.

We don't think about interface currently. Only about feature.

Welcome any suggestions.

**Comment by valeragit** [comment]
Could you give an example of a situation in which it may be useful?

**Comment by xanderblinov** [comment]
@valeragit for f.e. in adapters.
If adapters contains heavy items, its need in presenters. Ability to close scope of presenter will help you to manage its destroying

**Comment by xanderblinov** [comment]
All in all presenter's scope will work like scope in dagger, so it gots the same functional

**Comment by senneco** [comment]
@xanderblinov no, it isn't fully like this (if i understand you rightly ;) ).

Scope allow you use one instance presenter in different places. You should only say @InjectPresenter which presenter scope you want. And you can clear scope.

In practice it allows presenter be non-local and non-global. 

For example you have part of back-stack. It's part only for single news detail. But contains different activities. And then you can put NewsDetailsPresenter to "news-details"-scope and use one presenter instance at all this activities. And when you go back to news details, it's scope will be finished and destroy this scope presenters.

**Comment by valeragit** [comment]
Let's say I have one activity that shows kind of tree hierarchy, like filesystem, and I open every child (folder) in new fragment (with unique tag) with activity scope. So they are all will be persistent and I can popup fragments back and inject existed presenter but only in current activity. Am I right?

**Comment by terrakok** [comment]
For MVP: Presenter life limited related View.
For Android, this rule changed to handle device rotation.
Moxy extends the capabilities by adding Global and Weak presenter scopes. Ok, it may be convenient!

For other cases, it is necessary to use the Model!

**Comment by senneco** [comment]
I think it's right to move scope to models. Don't apply scope to presenters. Are everybody agrees with it?

**Comment by xanderblinov** [comment]
@senneco how you suggest to manage presenter's life in case you have one preventer per adapter item? Just child delegate?

**Comment by senneco** [comment]
@xanderblinov yes it''s. So, on open item details you should inject new presenter instance which will work with same model.

When I did asked, I thought make scope of single news presenter and use this scope's presenter in list and on details screen. But it seems wrong.
