### ISSUE TITLE
Animate and Screen rotation 2

### ISSUE THREAD

**Issue by crysan** [Arello-Mobile/Moxy#48]
Здравствуйте!

Продолжение вот этого вопроса: [#37](https://github.com/Arello-Mobile/Moxy/issues/37)
Есть одно активити и 3 дополнительных слоя, которые вызываем так:

Activity:
```
public class StartActivity extends MvpAppCompatActivity implements StartActivityView {
    @InjectPresenter
    StartActivityPresenter pStartActivityPresenter;

    @BindView(R.id.rootContainer) ViewGroup rootContainer;

    Scene scene_setusergendername;
    Scene scene_selectchild;
    Scene scene_setchildname;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_start);

        ButterKnife.bind(this);

        scene_setusergendername = Scene.getSceneForLayout(rootContainer, R.layout.scene_setusergendername, this);
        scene_selectchild = Scene.getSceneForLayout(rootContainer, R.layout.scene_selectchild, this);
        scene_setchildname = Scene.getSceneForLayout(rootContainer, R.layout.scene_setchildname, this);
    }

    public void goSetUserGenderName(View view) {
        pStartActivityPresenter.changeScene("SetUserGenderName");
    }

    public void goSelectChild(View view) {
        pStartActivityPresenter.changeScene("SelectChild");
    }

    public void goSetChildName(View view) {
        pStartActivityPresenter.changeScene("SetChildName");
    }

    @Override
    public void showScene_SetUserGenderName() {
        TransitionManager.go(scene_setusergendername, TransitionInflater.from(StartActivity.this).inflateTransition(R.transition.fade_out_in));
    }

    @Override
    public void showScene_SelectChild() {
        TransitionManager.go(scene_selectchild, TransitionInflater.from(StartActivity.this).inflateTransition(R.transition.fade_out_in));
    }

    @Override
    public void showScene_SetChildName() {
        TransitionManager.go(scene_setchildname, TransitionInflater.from(StartActivity.this).inflateTransition(R.transition.fade_out_in));
    }
}
```
Presenter:
```
@InjectViewState
public class StartActivityPresenter extends MvpPresenter<StartActivityView> {
    public StartActivityPresenter() {    }

    public void changeScene(String scenename) {
        if ("SetUserGenderName".equals(scenename)) {
            getViewState().showScene_SetUserGenderName();
        }
        else if ("SelectChild".equals(scenename)) {
            getViewState().showScene_SelectChild();
        }
        else if ("SetChildName".equals(scenename)) {
            getViewState().showScene_SetChildName();
        }
    }
}
```
View:
```
public interface StartActivityView extends MvpView {
    void showScene_SetUserGenderName();
    void showScene_SelectChild();
    void showScene_SetChildName();
}
```

При нажатии кнопок на слоях, переходы обрабатываются нормально, претензий нет.
Как только произошел поворот устройства, то срабатывает событие goSetUserGenderName.
Т.е. после старта приложения нажали кнопку 1 раз - перешли на второй экран, нажали на кнопку снова - перешли на третий, еще раз - на четвертый экран. Повернули устройство - автоматом перешли на второй.
Как сохранить состояние экрана в этом случае?
isInRestoreState(this) не спасает.

Спасибо!

**Comment by senneco** [comment]
Я не вижу, чтобы презентер вызывал метод `goSetUserGenderName`. Это значит вы вызываете этот метод откуда-то из вне. Продебажте это место, и найдите, откуда вызывается этот метод и исправьте это поведение

**Comment by crysan** [comment]
Из разметки слоя
activity_start.xml
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <RelativeLayout
        android:id="@+id/rootContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:orientation="vertical" android:layout_width="match_parent"
            android:layout_height="match_parent">

            <TextView
                android:id="@+id/txt"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Start"
                android:textSize="24sp"/>

            <Button
                android:onClick="goSetUserGenderName"
                android:text="Button2"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_below="@+id/txt"
                android:layout_alignParentStart="true"
                android:layout_marginStart="23dp"
                android:layout_marginTop="67dp" />

        </LinearLayout>
    </RelativeLayout>
</RelativeLayout>
```
android:onClick="goSetUserGenderName"

**Comment by senneco** [comment]
Т.к. этот метод вызывается не из Presenter, Moxy тут не при чём. Дебажте  этот метод, смотрите откуда он вызывается и почему.

**Comment by crysan** [comment]
Он вызывается из разметки слоя. На кнопке определена процедура нажатия
`android:onClick="goSetUserGenderName"`
Но смысл про презентер я почти уловил.

**Comment by senneco** [comment]
Ну вам нужно разобраться почему после поворота само по себе вызывается `goSetUserGenderName`. Вопрос по Moxy ещё актуален?)

**Comment by crysan** [comment]
Moxy хранит состояние, только если оно прошло через презентер?

**Comment by senneco** [comment]
Ага. ViewState хранится внутри Presenter. Каждая команда, которая попадает во ViewState, сохраняется внутри ViewState. Когда к Presenter аттачится View, ViewState отправляет в неё хранящиеся команды.

**Comment by crysan** [comment]
Тогда как обработать нажатие новой кнопки, которая появилась после смены слоя через TransitionManager?

**Comment by senneco** [comment]
Найти нужную View → установить click-listener. Если нужна помощь по android-разработки, можно обратиться на какой-нибудь форум, или в чатик. Например https://telegram.me/android_ru

**Comment by crysan** [comment]
Благодарю!

**Comment by crysan** [comment]
А переменные в объявленные презентер сохраняются после поворота устройства?

**Comment by crysan** [comment]
Не уверен. Вот пример в презентере:
```
@InjectViewState
public class StartActivityPresenter extends MvpPresenter<StartActivityView> {
    private String nextSceneName;

    public StartActivityPresenter() {
        setNextSceneName("SelectChild");
    }

    public void changeScene(String scenename) {
        if ("SetUserGenderName".equals(scenename)) {
            getViewState().showScene_SetUserGenderName();
            setNextSceneName("SelectChild");
        }
        else if ("SelectChild".equals(scenename)) {
            getViewState().showScene_SelectChild();
            setNextSceneName("SetChildName");
        }
        else if ("SetChildName".equals(scenename)) {
            getViewState().showScene_SetChildName();
            setNextSceneName("");
        }
    }

    public String getNextSceneName() {
        return nextSceneName;
    }

    public void setNextSceneName(String nextSceneName) {
        this.nextSceneName = nextSceneName;
    }
}
```
При повороте экрана срабатывает    
```
 public StartActivityPresenter() {
        setNextSceneName("SelectChild");
 }
```
А ведь оно, насколько я понял, должно срабатывать только при первой активации презентера? Или я не прав?

**Comment by crysan** [comment]
Да, а активити:
```
    @OnClick(R.id.btnNext)
    public void goNext(View view) {
        pStartActivityPresenter.changeScene(pStartActivityPresenter.getNextSceneName());
    }
```

**Comment by senneco** [comment]
Да, конструктор вызывается только при первом старте активити. Возможно, вы где-то меняете бэк-стэк. Попробуйте поставить break-point в коструктор и посмотреть, откуда он вызывается.

**Comment by crysan** [comment]
Попробовал. Такое ощущение, что конструктор пересоздается при пересоздании активити.

**Comment by senneco** [comment]
Какую версию Moxy вы используете?

**Comment by crysan** [comment]
compile 'com.arello-mobile:moxy:1.1.2'
    compile 'com.arello-mobile:moxy-app-compat:1.1.2'
    provided 'com.arello-mobile:moxy-compiler:1.1.2'

**Comment by senneco** [comment]
Хм. Ну у меня догадки иссякли. Можете взять сэмпл и убедиться, что там конструктор вызывается только один раз ;) А затем начать модифицировать сэмпл до того состояния, которое вам нужно ;)

**Comment by crysan** [comment]
Возможно, если вы недалеко от андроид студио, можете принять проект (из 1 активити) на тестирование?
Если нет - так нет.
Спасибо!

**Comment by senneco** [comment]
Уберите из него анимации, и тогда я посмотрю ;) Кинуть можете простым gist

**Comment by crysan** [comment]
не могу gist
только на почту архив ((
Но спасибо, что не отказали ))

**Comment by senneco** [comment]
Я вспомнил, что есть wiki! https://github.com/Arello-Mobile/Moxy/wiki/Simple-Async вот, можете начать с этого примера. И если поставить breakpoint в конструктор презентера, то видно, что он вызывается только один раз ;)

**Comment by crysan** [comment]
в случае с wiki - да
но в этом примере в презентере нет переменных, которые при повороте не должны пересоздаваться

**Comment by senneco** [comment]
Ну добавьте в сэмпловый презентер какую-нибудь филду. И увидите, что он всё-равно не пересоздаётся ;) А если бы он пересоздавался, то после переворота устройства, АлертДиалог не был бы показан.

**Comment by crysan** [comment]
Убил себе мозг.
Моху сохраняет состояние переменной. Проверено!
Было так:
```
    @Override
    public void showScene_SelectChild() {
        TransitionManager.go(scene_selectchild, TransitionInflater.from(StartActivity.this).inflateTransition(R.transition.fade_out_in));
    }
```
Стало:
```
    @Override
    public void showScene_SelectChild() {
        if (pStartActivityPresenter.isInRestoreState(this)) {
            rootContainer.removeAllViews();
            rootContainer.addView(scene_selectchild_);
            return;
        }
        TransitionManager.go(scene_selectchild, TransitionInflater.from(StartActivity.this).inflateTransition(R.transition.fade_out_in));
    }
```
В чем проблема отработки анимации после поворота, так и не понял ((
Но теперь все работает.

Спасибо!
