### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by Quatja** [Arello-Mobile/Moxy#5]
Hi, I understand how to use moxy in activities and fragments, but how can I use moxy in android dialogs? Can you provide an example code, please?

**Comment by senneco** [comment]
@Quatja are you interesting in FragmentDialog or simple dialog? Are you want to attach dialog view to some presenter? If you give me your dialog, it help me to make right sample ;)

**Comment by Quatja** [comment]
Problem is solved. Presenter was null in Dialog constructor, but it was ready in onCreate. Sorry
