### ISSUE TITLE
JavaDoc for public methods in library

### ISSUE THREAD

**Issue by ultraon** [Arello-Mobile/Moxy#53]
Hello, how about JavaDoc for public methods in library :-)

Thank you for you work, it's a cool library/framework

**Comment by xanderblinov** [comment]
Sources jar contains .class files, but should contains .java files. @senneco change please sources packaging folder

**Comment by senneco** [comment]
Fixed bug of build script. But this will being applied only with new release.

PS: currently new sources and javadoc jars published, but my Android Studio doesn't seeing this. But local maven show that this fix working.

**Comment by xanderblinov** [comment]
@senneco remove maven cash to reload artifact

**Comment by senneco** [comment]
@xanderblinov I'd remove local cache, but after sync, there are again old jars.

**Comment by senneco** [comment]
Published in Moxy v1.4.4
