### ISSUE TITLE
ViewPager MVP

### ISSUE THREAD

**Issue by Legementarion** [Arello-Mobile/Moxy#55]
Привет, мне очень понравилась ваша библиотека, просто потрясная реализация мвп) всё очень удобно и красиво) Единственное я бы хотел спросить как правильно поступить, что бы не городить велосипеды. У меня есть ViewPager с 3мя одинаковыми фрагментами, но они отображают разную информацию. При создании этих фрагментов, они все инжектятся к одному и тому же презентору) тот естественно запоминает состояние последнего добавленного фрагмента и после чего все 3 фрагмента начинают показывать одну и ту же информацию) Можно как то создавать для каждого фрагмента, свой отдельный презентер? или же есть какие то другие варианты?

**Comment by horse315** [comment]
@Legementarion я бы похожем кейсе трижды унаследовался от базовой реализации фрагмента и в каждой инжектил конкретный презентер.

**Comment by senneco** [comment]
@Legementarion по идее это должно работать из коробки, особенно если вы используете [FragmentStatePagerAdapter](https://developer.android.com/reference/android/support/v4/app/FragmentStatePagerAdapter.html)

Меня смущает фраза "При создании этих фрагментов, они все инжектятся к одному и тому же презентору". Что вы тут имеете ввиду? Вы инжектите во все презентеры один глобальный экземпляр презентера?

**Comment by Legementarion** [comment]
@senneco , нет, я не использую простой FragmentPagerAdapter, нужно изменить на FragmentStatePagerAdapter и попробовать через него?

у меня есть один класс фрагмента, в который через newInstance я передаю то что он должен будет отображать) этот фрагмент создаётся 3 раза, каждый объект для каждой странички) ну и в этом классе написано -
  @InjectPresenter
    ItemDetailPresenter mItemDetailPresenter;
 Я понимаю это так, что я создаю первый объект, он же создаёт и презентр, последующие два объекта уже не создают презентер, а просто связываются с уже существующим) ну и при перелистывании презентер запоминает инфу последнего фрагмента и начинает отображать только её на всех остальных подключённым фрагментах. А вот я так понимаю нужно как то сделать, что бы у каждого фрагмента был свой личный презентер, только как это правильно сделать, я не знаю.

**Comment by Legementarion** [comment]
@horse315 Ну я думал про этот вариант, но он мне кажется чуток накладным) если не будет другого подхода, то наверно придётся так делать )

**Comment by senneco** [comment]
@Legementarion да, FragmentStatePagerAdapter должен сработать. Потому что он перед тем, как удалить Fragment, сохранит tag его делегата в bundle save state, а затем его восстановит и переиспользует его презентеры

**Comment by Legementarion** [comment]
@senneco Уууууууууууууу)) даже не знаю как благодарить))) заработало))) Спасибо большое))) Тебе нужно работать в департаменте магии))

**Comment by senneco** [comment]
Рад помочь ;)
