### ISSUE TITLE
Best practice to save state of input fields

### ISSUE THREAD

**Issue by xasmwasm** [Arello-Mobile/Moxy#56]
Hello. Is there a best practice for Moxy to save view state of input fields?
For example, a scheme below causes looping.

```java
//LoginView
void onCreate(){
  editTextLogin.afterTextChanged((text) -> loginPresenter.onLoginChanged(text));
}
void showLogin(String login){
  editTextLogin.setText(login);
}


//LoginPresenter
void onLoginChanged(String newLogin){
  this.login = newLogin;
  getViewState().showLogin(newLogin);
}
```

**Comment by senneco** [comment]
Hello,

Are you realy want to save data in presenter on each text change?

Most simplest solution is to put string in EditText only if this command was being received for restore view state:

```java
void showLogin(String login){
  if (!loginPresenter.isInResoreState(this)) {
     return;
  }
  editTextLogin.setText(login);
}
```

But this issue has many other solutions. But then I need more info about your issue ;) Or is isInResoreState-solution enough?

**Comment by xasmwasm** [comment]
My issue is to perform real-time validation of data in EditText for make decision to show prompt message in View or not.
The solution with isInResoreState is acceptable. Thank you.
But I think that Presenter (or ViewState) should be responsible for such checks. Is it possible to do?

**Comment by senneco** [comment]
Well, you can don't send showLogin(newLogin) to View from Presenter. Android save EditText's value automatically if this have an id :D

In other cases this issue has many solutions. And you can come up own every time ;)

PS: In my cases, I assign this issue on Android. EditText value, ScrollView/ListView/RecyclerView scroll position, CheckBox/Switcher check-state. All these view states will have be saved by Android without problems.

**Comment by xasmwasm** [comment]
Thank you for help.
