### ISSUE TITLE
Проблема с пересозданием презентеров

### ISSUE THREAD

**Issue by user56i** [Arello-Mobile/Moxy#59]
Возникает проблема с пересозданием презентера после пересоздания активити если фрагмент этого презентера был в бекстеке. 

Например имеем 2 фрагмента A и B с презентерами. Сначала показываем A потом реплейсим на B. Далее сворачиваем приложение. Активити уничтожается (для воспроизведения ставлю в  настройках флаг “Do not keep activities”). При открытии приложения откроется фрагмент B, где презентер фрагмента B не пересоздался, а при нажатии бек откроется фрагмент A и презентер A - пересоздастся.

Фиксится указанием type = PresenterType.GLOBAL, но в таком случае презентер будет 1 для всех фрагментов этого типа.

**Comment by senneco** [comment]
А какую версию библиотеки вы используете?

**Comment by user56i** [comment]
1.1.2

**Comment by user56i** [comment]
От при сворачивании уничтожается, вызывается onDestroy у A presentera.

**Comment by senneco** [comment]
Попробуйте обновиться до 1.3.2

**Comment by user56i** [comment]
Обновление версии решило проблему. Спасибо.
