### ISSUE TITLE
NullPointerException в генерируемом коде после обновления до 1.3.2

### ISSUE THREAD

**Issue by CherryPerry** [Arello-Mobile/Moxy#60]
View interface:
```java
public interface CloseableView extends MvpView {
    @StateStrategyType(SkipStrategy.class)
    void close();
}
```

View implementation (Fragment):
```java
@Override
public void close() {
    if (getActivity() != null) getActivity().onBackPressed();
}
```

Presenter:
```java
public void apply() {
    localBroadcastManager.sendBroadcast(intent);
    getViewState().close();
}
```

По нажатию на кнопку во вью вызывается метод `apply` презентера. В `close` текущий фрагмент выкидывается из backstack'a, и на его место встает предыдущий. В итоге во `CloseableView$$State` в методе `close` выкидывается `NullPointerException` т.к. `getCurrentState` теперь возвращает `null`:
```java
@Override
public  void close() {
    CloseCommand closeCommand = new CloseCommand();
    mViewCommands.beforeApply(closeCommand);

    if (mViews == null || mViews.isEmpty()) {
        return;
    }

    for(CloseableView view : mViews) {
        view.close();
        getCurrentState(view).add(closeCommand);
    }

    mViewCommands.afterApply(closeCommand);
}
```

**Comment by senneco** [comment]
А NPE случается тогда, когда вы в первый раз вызываете `Presenter.apply()`, или вы у этого презентера ещё когда-то вызываете `apply()`?

**Comment by CherryPerry** [comment]
Apply можно вызвать только один раз, ведь после этого фрагмент уничтожается.

**Comment by senneco** [comment]
А, я понял, почему проблема происходит =) Сегодня-завтра опубликую решение. Вам нужна помощь со временным хот-фиксом?

**Comment by CherryPerry** [comment]
Нет, я пока обратно на 1.2.0 откачусь.

**Comment by senneco** [comment]
В аннотацию @InjectViewState можно передать свой класс ViewState. В который можно скопировать сгенерированный класс ViewState, у которого не будет вызываться `getCurrentState(view).add(closeCommand);`

PS: а откатываться лучше уж на 1.2.1 ;)

**Comment by senneco** [comment]
Исправлено в версии 1.3.3. Но release note еще не готов. Буду признателен, если проверите, корректно ли у вас этот момент отрабатывает в версии 1.3.3

**Comment by CherryPerry** [comment]
Хорошо, завтра проверю.

**Comment by CherryPerry** [comment]
Теперь не крашится, все ок.
Не будет проблем с другими типами презентеров (weak, global)?

**Comment by senneco** [comment]
@CherryPerry нет, с ними проблем подавно не будет =)

Спасибо за содействие.
