### ISSUE TITLE
Dagger 2 with ActivityComponent

### ISSUE THREAD

**Issue by lectricas** [Arello-Mobile/Moxy#61]
Hi. I have an ActivityComponent where I have a fragmentManager or Activity to help me to switch between screens(3 party library, which uses this parts to manipulate screens). 
I inject fragmentManager inside Presenter and then invoke it when needed. This is easy and I don't need to write two lines instead of one:

```
getActivityComponent().inject(this); //activity
getApplicationComponent.inject(this); //presenter
```

I can use ActivityCompenent as a static variable, but it can cause some memory leaks.
So, is there any way how can I inject "view stuff" in presenter?

**Comment by valeragit** [comment]
Hi!
First of all, i'm not sure that presenter is right place for manipulating with fragment manager because it makes unit testing more difficult.

Second, you can use @ProvidePresenter annotation and create the "right" dagger 2 constructor for presenter:
```
@Singleton
public class SimplePresenter extends MvpPresenter<SimpleView> {

    private FragmentManager fragmentManager;
    
    @Inject
    public SimplePresenter(FragmentManager fragmentManager) {
        this.fragmentManager = fragmentManager;
    }
}
```

And in your SimpleActivity:
```
public class SimpleActivity extends MvpAppCompatActivity {

    @InjectPresenter
    private SimplePresenter presenter;

    @ProvidePresenter
    public SimplePresenter providePresenter() {
        return getActivityComponent().provideSimplePresenter();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getActivityComponent().inject(this)
    }
}
```

Also you need to add provideSimplePresenter method in you ActivityComponent:
`SimplePresenter provideSimplePresenter();`

**Comment by valeragit** [comment]
More about custom presenters:
https://github.com/Arello-Mobile/Moxy/wiki/Provides-Presenter-and-its-Tag

**Comment by lectricas** [comment]
I just want to make my code shorter.
BasePresenter is my place where I inject all the stuff and then using lombok getters I take whatever I want and use it. 

I'm using **cicerone** library and I inject the navigator(which requires fragmentManager and activity to work). So, I just inject this thing in into BasePresenter and then I can reach it from any activity or fragment.

But if I try to inject the navigator inside BaseActivity (and all other network/db stuff into BasePresenter), then I need to write 
`getActivityComponent().inject(this) `
in every activity in addition to all presenters ApplicationComponent injections.

I even need a new PerFragment scope or something to make it look right. 

Sorry for TL DR, lets just make the question shorter:

Suppose you need to provide an activity object for the entire application. 
How would you solve this?

**Comment by senneco** [comment]
Sorry, but I don't understand you =(

1. Did you inject `Navigator` to Presenter? But for a what? It must be different for each activity.

2. Why do you want to provide single activity object to everywhere?

**Comment by lectricas** [comment]
@senneco 
I have one navigator where I switch fragments and activities(not only fragments).  That's why I need the activity object everywhere. 

```
public void launchScreenForward(Forward forward) {
        Fragment fragment = createFragment(forward.getScreenKey(), forward.getTransitionData()); //can have null if there are no fragments with given name. 
        if (fragment != null) {
            fragmentManager //forward fragment
                    .beginTransaction()
                    .replace(containerId, fragment)
                    .addToBackStack(forward.getScreenKey())
                    .commit();
        } else {
            activity.startActivity(((Intent) forward.getTransitionData()));
        }
    }
```
This is a sort of research, how to effectively lauch views without boilerplate and easy to read.
Maybe this approach is absolutely wrong. Free to propose your scenario.

**Comment by senneco** [comment]
I think, that this question you can ask in Cicerone repository's issues =)

I think, that Presenter is ugly place for Navigator. Because Presenter may
have no attached View, and if it send some command, Navigator do it, but it
must be not executed.


-----
С уважением,
Юрий

2016-12-09 15:36 GMT+07:00 alexey polusov <notifications@github.com>:

**Comment by lectricas** [comment]
true, true. Thanks.
