### ISSUE TITLE
Co-op with Gradle Transform API

### ISSUE THREAD

**Issue by alextel69** [Arello-Mobile/Moxy#63]
Objective is to transform classes of Moxy lib in post-compile step.

In order to do this one uses Gradle Transform API ([guide](https://afterecho.uk/blog/create-a-standalone-gradle-plugin-for-android-part-4-the-transform-api.html))

However, I found out that only xml resources (R$string, R$layout ans so on) from dependencies are getting into transform. Classes from Moxy are not coming at all. Maybe I need to process jars?

Related code (Transform etc.) [here](https://gist.github.com/alextel69/a6264e94220fda3124d09df056e77b3e)

**Comment by senneco** [comment]
Hi, I don't understand this issue. Moxy doen't use the Gradle Transfomr API. This's great idea to make Gradle Plugin for Moxy in future, but not now.
