### ISSUE TITLE
Сохранение состояния фрагментов

### ISSUE THREAD

**Issue by NoNews** [Arello-Mobile/Moxy#64]
Здравствуйте!
Есть небольшая проблема с сохранением состояния фрагментов.

1. Есть SplashScreenActivity, которая может показывать 1 из 2-х фрагментов.
View:

```
public interface SplashScreenView extends MvpView {
    void showMainActivityWithLoginFragment();  //если токен отсутствует
    void showMainActivityWithMainFragment(); //если есть токен
    void showErrorConnection();
    void goneErrorConnection();
}
```

2. MainActivity
View:
```
public interface MainActivityView extends MvpView {
    void showMainFragment();
    void showLoginFragment();
}

```

3. LoginFragment
View:
```
public interface LoginView extends MvpView {

    void visibleHeader();
    void goneHeader();
    void showSystemError(String errorText);
    void showPhoneError();
    void showPasswordError();
    void goneSystemError();
    void gonePhoneError();
    void gonePasswordError();
    void startErrorAnimation(TextView tvError);
    void showProgress(boolean progress);
    void showMainFragment();
}
```

4. MainFragment c `viewPager `
В нём происходит только инициализация `viewPager`+`tabLayout`, view-интерфейс пустой.

Насколько мне известно, по умолчанию, стоит стратегия `AddToEndStrategy` ко всем view-командам.
Получается, что при перевороте экрана, накопленные команды во view запустятся заново.
Но, при перевороте экрана, если  я нахожусь в ` LoginFragment`,  состояние `EditText` не сохраняется.
Так же, если я нахожусь в MainFragment, при перевороте открывается LoginFragment.
Для решения этой проблемы пробовал использовать     `@StateStrategyType(SingleStateStrategy.class)` к методам запуска MainFragment, но, ничего не изменилось)

Скорее всего, проблема в неправильных стратегиях. Какие использовать в данном случае — не совсем понятно.

**Comment by valeragit** [comment]
> public interface MainActivityView extends MvpView {
>     void showMainFragment();
>     void showLoginFragment();
> }

Здесь надо поставить `SkipStrategy.class`, тогда при повороте они не будут применяться снова. В данном случае состояние (какой фрагмент отображается в активити) будет восстановлено системой, а moxy восстановит состояние `LoginFragment`, если это будет нужно.
А сейчас у вас повторно добавляется тот фрагмент, который уже отображается.

**Comment by CherryPerry** [comment]
Вместо `SkipStrategy.class` можно использовать `OneExecutionStateStrategy.class` для навигации, тогда навигация, которая должна осуществиться после загрузки, не пропадет при сворачивании и разворачивании приложения.

**Comment by NoNews** [comment]
@valeragit 
Пробовал `@StateStrategyType(SkipStrategy.class)` 
LoginFragment  вообще не открывается в таком случае(

**Comment by valeragit** [comment]
@NoNews, не открывается после поворота или вообще?

**Comment by NoNews** [comment]
@valeragit вообще

**Comment by valeragit** [comment]
@NoNews, значит у вас где-то ещё закралась ошибка, т.к. `@StateStrategyType` на вызов метода не влияет.
Где у вас вызываются методы `MainActivityView `?

**Comment by NoNews** [comment]
@valeragit  LoginFragment не открывается только в том случае, если применить `SkipStrategy` к` showLoginFragment();`. (что очень странно). 

Методы MainActivityView вызываются в MainActivity:


```
 @Override
    public void showMainFragment() {
        getSupportFragmentManager().popBackStack(null, FragmentManager.POP_BACK_STACK_INCLUSIVE);
        getSupportFragmentManager()
                .beginTransaction()
                .replace(R.id.ltContainer, MainFragment.newInstance())
                .commit();
    }

    @Override
    public void showLoginFragment() {
        getSupportFragmentManager()
                .beginTransaction()
                .replace(R.id.ltContainer, LoginFragment.newInstance())
                .commit();
    }

```

**Comment by NoNews** [comment]
@valeragit в дебаггере так же видно, что метод showLoginFragment() вызывается
Но, вместо него открывается белый экран. (прошу прощение за неточность ранее)

**Comment by valeragit** [comment]
@NoNews 
> Методы MainActivityView вызываются в MainActivity
Стратегии сохранения состояния применяются если вы вызываете метод интерфейса **из презентера**, через getViewState(), в противном случае вызов метода нигде не сохраняется.

> в дебаггере так же видно, что метод showLoginFragment() вызывается
> Но, вместо него открывается белый экран.
Если метод вызывается и фрагмент добавляется - нужно смотреть что происходит дальше.

**Comment by NoNews** [comment]
@valeragit  методы я естественно вызываю из презентера. 
В дебаггере видно, что в презентере вызывается метод
`  getViewState().showLoginFragment();
`
При этом, сам вызов метода в MainActivity почему-то не производится. (т.е., фрагмент не создаётся).
Если убрать `SkipStrategy `— LoginFragment создастся.

Ниже можете посмотреть полный код на gist (с presenter и view)
[SplashScreenActivity](https://gist.github.com/NoNews/68acfaf56130f95eba1ce0e06d921b0a)
[LoginFragment](https://gist.github.com/NoNews/8993c0b30c324b3f5bdd03bb2ae19786)
[MainActivity](https://gist.github.com/NoNews/ab998fc7fb36cb6623322ac905623f28)
[MainFragment](https://gist.github.com/NoNews/79548c29472eca4fdfef5b01fb96099a)

**Comment by CherryPerry** [comment]
@NoNews 
А я понял, что не так. Ставьте вместо `SkipStrategy.class` `OneExecutionStateStrategy.class`.
У вас метод навигации `showLoginFragment()` вызывается в `onCreate()`, а в этот момент вью еще не приаттачена к презентеру, и следуя  `SkipStrategy.class`, вызов метода пропускается.
Аттач вью к презентеру [происходит](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-android/src/main/java/com/arellomobile/mvp/MvpActivity.java#L25) в `onResume()`.

**Comment by NoNews** [comment]
@CherryPerry 
Если применить `OneExecutionStateStrategy.class`, то при перевороте экрана на `MainFragment`, открываться будет опять `LoginFragment`. (проблемы с белым экраном не будет)

Попробовал так же вызвать в `onResume`, со `SkipStratigy.class`, проблема с белым экраном действительно пропала, но, при перевороте в `MainFragment` показывает так же `LoginFragment`

**Comment by CherryPerry** [comment]
@NoNews 
Так и должно быть, ибо при перевороте вызывается `onCreate()` и снова происходит навигация.
```java
mainPresenter.showFragment(getIntent().getIntExtra(Const.KEY_FRAGMENT, 0));
```
Нужно заменить на `@ProvidePresenter` блок и передавать `Const.KEY_FRAGMENT` в конструктор презентера, и в нем уже вызвать `getViewState().showMainFragment()` или другой метод навигации с `OneExecutionStateStrategy.class`.

**Comment by NoNews** [comment]
@CherryPerry 
Сможете привести небольшой пример на этот счёт?
Пока что смутно понятно про `@ProvidePresenter`

**Comment by CherryPerry** [comment]
Конструктор презентера:
```java
public MainActivityPresenter(int id) {
    switch (id) {
        case Const.TYPE_MAIN:
            getViewState().showMainFragment();
            break;
        case Const.TYPE_LOGIN:
            getViewState().showLoginFragment();
            break;
    }
}
```
Часть активити:
```java
...
@ProvidePresenter
MainActivityPresenter providePresenter() {
    return new MainActivityPresenter(getIntent().getIntExtra(Const.KEY_FRAGMENT, 0));
}

@Override
protected void onCreate(Bundle savedInstanceState) {
...
```

**Comment by NoNews** [comment]
@CherryPerry 

Всё получилось.
Спасибо Вам!

Я правильно понял, что презентер просто пересоздаётся при переворотах?
Соответственно, очередь теряется.

**Comment by CherryPerry** [comment]
Нет, презентер не пересоздается, в этом вся и суть.
В Вашем случае вы при перевороте заново вызывали навигацию, поэтому сохраненное состояние фрагментов терялось, если метод применялся, или, если не применялся, получали пустую активити.

**Comment by NoNews** [comment]
@CherryPerry 

Спасибо! Стало намного понятнее)
