### ISSUE TITLE
ViewPager и Presenter

### ISSUE THREAD

**Issue by NoNews** [Arello-Mobile/Moxy#68]
Здравствуйте.
Есть `MainActivity`, которая служит контейнером для всех фрагментов. (в т.ч. в одном из фрагментов реализован `viewPager` c 3-мя фрагментами)

В одном из фрагментов viewPager-а есть `RecyclerView`, из которого с помощью `EventBus `открывается другой фрагмент(в главном контейнере `MainActivity`).

Т.е, следующий кейс:

— Открыт фрагмент `OrdersFragment `(элемент `viewPager`)
— Открываем фрагмент `SelectedOrderFragment`( не является элементов `viewPager`)
— Возвращаемся назад из фрагмента `SelectedOrderFragment `в `OrdersFragment` (по сути, на текущую открытую табу в `MainFragment`)
— Презентеры всех фрагментов во viewPager пересоздаются. (такая же ситуация при перевороте экрана, что не очень удобно, т.к. планировал делать в конструкторах http-запросы).

Как с этим бороться?
метод открытия `MainFragment `(который с viewPager внутри) из `MainActivity`
имеет стратегию `@StateStrategyType(OneExecutionStateStrategy.class)`

На всякий случай, код с view:

[MainActivity](https://gist.github.com/NoNews/e971db6e69e3cf68daf108a9094f0e91)
[MainFragment](https://gist.github.com/NoNews/fe3098754a3f8936dd4d6081c6a2a8e4)//viewPager внутри
[OrdersFragment](https://gist.github.com/NoNews/07b2d146fe3a30877c9a20fbfd41c64c) //1 из элементов viewPager-а
[SelectedOrderFragment](https://gist.github.com/NoNews/95e57b98fcc9fdc5b0352a5a8748de74)

gradle:
```
    compile 'com.arello-mobile:moxy:1.3.3'
    provided 'com.arello-mobile:moxy-compiler:1.3.3'
    compile 'com.arello-mobile:moxy-app-compat:1.3.3'
    compile 'com.arello-mobile:moxy-android:1.3.3'
```

```

**Comment by senneco** [comment]
Попробуйте наследовать ваш адаптер от FragmentStatePagerAdapter. Если не поможет, то будем думать дальше

**Comment by NoNews** [comment]
@senneco
Адаптер унаследован от FragmentStatePagerAdapter изначально

**Comment by CherryPerry** [comment]
К слову о старом баге с ViewPager.
У меня сейчас такой же кейс (фрагмент с пейджером, который реплейсится с добавлением в бэкстек), и все работает как положено.

@NoNews
Ваша же проблема вероятней всего в том, что вы неправильно используете `addToBackStack()`. Он должен идти после `replace()`, а не до него.
Да и ловить события EventBus'a во View как-то нехорошо, как по мне.

**Comment by NoNews** [comment]
@CherryPerry 

> Ваша же проблема вероятней всего в том, что вы неправильно используете addToBackStack(). Он должен идти после replace(), а не до него.

Добавил `addToBackStack()` после `replace`.
Так же нашёл косяк в адаптере: переопределял метод `saveState()`, что и вызывало пересоздание.
Собственно, привёл адаптер вот к [такому ](https://gist.github.com/NoNews/58f2ca30c8586ddafea13dfcbc5c19cc)виду, проблема с пересозданием презентера пропала. 

Но, появилась новая — состояние фрагментов во `viewPager ` вообще перестало сохраняться. 

Т.е., делаем `replace`, нажимаем назад — попадаем на `viewPager `с белыми экранами.
Причём, команда на `replace` уже поступает из презентера открытого во `viewPager `фрагмента со стратегией `OneExecutionStateStrategy.class`

> Да и ловить события EventBus'a во View как-то нехорошо, как по мне.

В принципе, я думал о том, чтобы запускать `EventBus `в презентере.
Наверное можно попробовать в методах `onStop();` и `onStart();` текущего фрагмента подписывать и отписывать через `Presenter ``EventBus`.

**Comment by senneco** [comment]
@NoNews а какую версию Moxy вы используете?

**Comment by NoNews** [comment]
@senneco 

1.3.3.

**Comment by senneco** [comment]
@NoNews а можете попробовать 1.2.1? Если для этого вам не придётся перелопасивать пол проекта, конечно =)

**Comment by NoNews** [comment]
@senneco 

Да, конечно. Отпишусь вечером.

**Comment by NoNews** [comment]
@senneco

очень странно, но в один прекрасный день данная проблема пропала.
Возможно, дело было вряд ли в Moxy.
P.S. на 1.2.1 всё хорошо работает.
на 1.3.3 так же.

Отпишусь, если получится отловить этот момент ещё раз с конкретными условиями.
Спасибо за реакцию!
