### ISSUE TITLE
mViews.isEmpty()

### ISSUE THREAD

**Issue by pasha656** [Arello-Mobile/Moxy#69]
Method not call =( 

ActivityA
MyViewA
PresenterA

ActivityB
MyViewB
PresenterB

1. In ActivityA user click btn "Create new task"
2. Open ActivityB, user do something and click btn "Save"
3. PresenterB send event to PresenterA - new task was created
4. PresenterA receive event and call  getViewState().newTaskWasCreate()

Method not call =( because 
`if (mViews == null || mViews.isEmpty()) { return; }`
mViews.isEmpty() - true

But if I use handler with delay it is work fine

MyViewA
`@StateStrategyType(SkipStrategy.class)
void newTaskWasCreate(long taskId, long projectId, int fragmentPosition);
`

PreventerA
`@Subscribe(sticky = true)
 public void onEvent(MyTasksEvent.NewTaskWasCreate event){ 
 getViewState().newTaskWasCreate(event.getTaskId(), event.getProjectId(), event.getFragmentPosition());
}
`

Generate
`
@Override
	public  void newTaskWasCreate(long taskId, long projectId, int fragmentPosition) {
		NewTaskWasCreateCommand newTaskWasCreateCommand = new NewTaskWasCreateCommand(taskId, projectId, fragmentPosition);
		mViewCommands.beforeApply(newTaskWasCreateCommand);

		if (mViews == null || mViews.isEmpty()) {
			return;
		}

		for(MyTaskFragmentView view : mViews) {
			getCurrentState(view).add(newTaskWasCreateCommand);
			view.newTaskWasCreate(taskId, projectId, fragmentPosition);
		}

		mViewCommands.afterApply(newTaskWasCreateCommand);
	}
`

**Comment by senneco** [comment]
@pasha656 since Moxy 1.3.x view will be detached when it stopped. When view will being resumed it will be attached again and then apply commands.

**Comment by pasha656** [comment]
Check this, please - https://github.com/pasha656/MoxyBug
May be I do something wrong

'
    @Subscribe(threadMode = ThreadMode.MAIN)
    fun onEvent(event: ClickEvent) {
        Log.d("Pasha", "Receive event!")
        countUpdate++

        // Bug
        //viewState.updateTextView(countUpdate.toString())

        // Fix
        Handler().postDelayed({ viewState.updateTextView(countUpdate.toString()) }, 250)
    }
`

**Comment by CherryPerry** [comment]
@pasha656 
> `@StateStrategyType(SkipStrategy::class)`
Try `AddToEndStrategy`. `SkipStrategy` is skipped, when view is detached, and view is detached because of `onStop `of activity.

**Comment by pasha656** [comment]
But I do not wanna use AddToEndStrategy. Because if I wanna show snake bar and use AddToEndStrategy, when rotate screen, snake bar show again.

**Comment by CherryPerry** [comment]
> I wanna show snake bar and use AddToEndStrategy, when rotate screen, snake bar show again.
`OneExecutionStateStrategy.class`

**Comment by pasha656** [comment]
Thanks for your answer!
