### ISSUE TITLE
Duplicate entry MoxyReflector 

### ISSUE THREAD

**Issue by user56i** [Arello-Mobile/Moxy#72]
Добрый день. Столкнулся с проблемой в случае использования библиотеки Moxy одновременно в модуле приложения и модуле библиотеки. Поскольку 2 класса MoxyReflector  имеют одинаковый пакет. Подскажите решение. 

Java.util.zip.ZipException: duplicate entry: com/arellomobile/mvp/MoxyReflector.class

**Comment by senneco** [comment]
Хмм.. Не приятная проблема. А если попробовать moxy-compiler убрать из модуля приложения? Может компилер, который находится в библиотеке, отработает и для основного модуля. Хотя может лучше наоборот -- компилер запихнуть только в модуль приложения.

**Comment by user56i** [comment]
Нет. В случае если компайлер оставить только в модуле приложения, MoxyReflector остается таким же. А в sViewStateProviders и в sPresenterBinders не добавляются обработки презентеров либы.

**Comment by senneco** [comment]
Хм, плохо. Даже не могу с ходу придумать решение, и даже не могу придумать, чего в библиотеке такого сделать, чтобы оно работало. Я посмотрю, что происходит в аннотейшен процессоре, если мокси есть в двух модулях, но не знаю, когда найдётся время =(

**Comment by xanderblinov** [comment]
По-хорошему MoxyReflector должен находится в корне базового пакета - это решит рпоблему библиотек. Можно это попробовать сделать через  аргументы annotationProcessor-а

**Comment by senneco** [comment]
@xanderblinov у тебя есть идеи, как это сделать? @SavinMike придумал интересный подход:
1. В параметры процессора передать название пакета, в котором хочется держать MoxyReflector (как сказано [тут](http://tools.android.com/tech-docs/jackandjill#TOC-Repackaging-support))
2. Во время генерации MoxyReflector, складывать его в указанный пакет
3. Как-то научить Moxy находить нужный MoxyReflector

@user56i если вам критично наличие двух модулей с мокси в одном проекте, можете пока использовать 1.3.3, только нужно будет вставить заплатку от утечки памяти. Если нужно, то обращайтесь, помогу.

**Comment by senneco** [comment]
Да, надо сделать так же, как и в DBFlow: https://github.com/Raizlabs/DBFlow/blob/master/usage2/MultipleModules.md

**Comment by BlaizMiko** [comment]
Привет, возникла проблема, возможно смежная в рамках данного вопроса. Решил обновить либку c 1.3.3 до последней версии - 1.4.5. Приложение сразу упало, выдавая ошибки:
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/arellomobile/mvp/MoxyReflector;
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.arellomobile.mvp.MoxyReflector"
С чем может быть связано? Спасибо

**Comment by senneco** [comment]
@BlaizMiko а проект полноценный, не hello world? В вашем коде встречается хоть одно поле с  @InjectPresenter? Как подключаете moxy-compiler? Включен ли в градле плагин apt?

**Comment by BlaizMiko** [comment]
@senneco Проект как полноценный, так и потом на hello world попробывал, результат один. В коде поля нету, запуская просто пустую activity унаследованную от MvpAppCompatActivity. 
Подключаю как - annotationProcessor 'com.arello-mobile:moxy-compiler:1.4.5'. Нет, apt я не включал.

**Comment by senneco** [comment]
@BlaizMiko добавьте в вашу Activity хотя бы одно поле, отмеченное аннотацией @InjectPresenter, уберите польностью apt (т.е. у вас не должно быть даже apply plugin: 'com.neenbedankt.android-apt').

PS: ваша проблема явно к этой задаче не относится ;)

**Comment by BlaizMiko** [comment]
@senneco Спасибо, попробую. 
Смежность я определил по проблеме с MoxyReflector просто ;)

**Comment by morder** [comment]
Есть какое-то движение в направлении решения этой проблемы?

**Comment by terrakok** [comment]
Проблема легко должна решиться исключением зависимости:
```groovy
compile ('ваш библиотечный модуль') {
  exclude group: 'com.arellomobile.mvp'
}
```

**Comment by morder** [comment]
@terrakok можете привести пример применительно к moxy?

**Comment by terrakok** [comment]
так я для мокси и написал. замените 'ваш библиотечный модуль' на название вашего модуля и все

**Comment by morder** [comment]
@terrakok 
compile project(':my_module') {
    exclude group: 'com.arellomobile.mvp'
}
Так в Gradle нельзя делать

**Comment by terrakok** [comment]
минута гугления
```
compile( project('ваш библиотечный модуль')) {
  exclude group: 'com.arellomobile.mvp'
}
```

**Comment by morder** [comment]
не помогает
Error:Execution failed for task ':app:transformClassesWithJarMergingForDevDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/arellomobile/mvp/MoxyReflector.class

**Comment by terrakok** [comment]
Try like this: https://medium.com/@terrakok/how-to-fix-gradle-build-error-java-util-zip-zipexception-duplicate-entry-83d102038056

**Comment by terrakok** [comment]
Try like this: https://medium.com/@terrakok/how-to-fix-gradle-build-error-java-util-zip-zipexception-duplicate-entry-83d102038056

**Comment by zavbak** [comment]
Добрый день. Не могу понять в чем дело? В проекте MvpAppCompatActivity и MvpFragment. По нажатию на TextView в Activity меняю ее текст через презентер и  добавляю Fragment. 

getViewState().showMessage("click: " + new Date());
getViewState().showListFragment();

В фрагменте тоже есть TextView по нажатию на который вывожу текст через презентер фрагмента. 

getViewState().showMessage("click frag: " +new Date());

Получаю экран с 2-мя TextView и выведенным текстом.

Переворачиваю эмулятор. TextView Activity прекрасно востанавливается свое состояние, а TextView фрагмента нет.

В презентере  фрагмента при повороте снова вызывается onFirstViewAttach()

Понимаю, что мой презентер не сохранился. 

Если ставлю @InjectPresenter (type = PresenterType.GLOBAL, tag = ListPresenter.TAG)
То работает. Думаю, что в фрагменте не нужен глобальный презентер, чтобы только пережить поворот.

Гляньте пожалуйста в чем моя ошибка. https://github.com/zavbak/AnitApplication2

Проект простой.
Hello Word. Изучаю технологию.

**Comment by senneco** [comment]
@zavbak примените стратегию OneExecutionStrategy к команде showListFragment и всё будет ок. Если нужно больше помощи -- или создавайте новую issue(потому что к текущей никакого отношения не имеет), или велкам в чатик.

**Comment by senneco** [comment]
Пока ещё не опубликован фикс, поэтому реопну таску

**Comment by zavbak** [comment]
Спасибо большое. Все Ок.

**Comment by user56i** [comment]
Баг воспроизводится на 1.5.3. Только теперь крешит не при сборке, а в рантайме (презентер -  null). У нас в проекте в 2-ух модулях используется мокси. Если смотрю в дебаг режиме - вижу биндеры только одного модуля.

**Comment by senneco** [comment]
@ekursakov есть идеи, куда стоит смотреть?)

**Comment by ekursakov** [comment]
Судя по тому что презентер null что-то неправильно отрабатывает в модуле с вью.
Первое что посмотреть – во всех ли модулях подключен moxy-compiler.
Дальше проверить правильно ли он сконфигурирован:
- в модулях-библиотеках должен стоять параметр annotation processor'а `moxyReflectorPackage`, у каждого модуля свой
- в модуле приложения на любом классе надо прописать аннотацию `@RegisterMoxyReflectorPackages({"com.example.common"})` и указать в ней все пакеты из библиотек.
В модуле с приложением `moxyReflectorPackage` не ставить.

Ну и если не поможет, то неплохо бы посмотреть на сгенерированные классы MoxyReflector. В основном модуле он лежит в `app/build/generated/source/kapt/debug/com/arellomobile/mvp/MoxyReflector.java` или около того. В библиотеках должен генерироваться в тех пакетах в которые указаны в конфигурации.

**Comment by ekursakov** [comment]
Написал небольшую инструкцию, можно в вики закинуть: https://gist.github.com/ekursakov/b8ffe396ae4e00a5400f7f4e3d546f9a

**Comment by senneco** [comment]
@ekursakov спасибо! https://github.com/Arello-Mobile/Moxy/wiki/Multiple-modules

**Comment by EkslV** [comment]
спасибо. метод сработал для меня.

**Comment by jukov** [comment]
Стоит добавить, что как минимум в одном модуле должен остаться MoxyReflector со стандартным пакетом. Если задать кастомный пакет во всех модулях, то ничего работать не будет.
