### ISSUE TITLE
MvpFragment need to set mIsStateSaved = false in onStart(), not in onResume()

### ISSUE THREAD

**Issue by Jeevuz** [Arello-Mobile/Moxy#74]
You need to set ```mIsStateSaved = false``` in ```onStart()```, because it is possible that after state saved fragment will be *started* and then immediately *stopped* and *destroyed*.  
**Without** entering **resume** state. And we will **leak the presenter**.

It can be reproduced by adding following in the activity:
```java
private int counter = 0;
@Override
public void onStart() {
    Timber.d("onStart()");
    if (counter == 1) {
        finish();
    }
    counter++;
    super.onStart();
}
```
And then turning off and on the screen by clicking on the power button. 

In logs of the fragment you will see the following:
```java
D/MainActivity: onStart()
D/Presenter: Created presenter
D/MainFragment: onStart()
D/MainFragment: onResume()
D/MainFragment: onPause()
D/MainFragment: onSaveInstanceState()
D/MainFragment: onStop()
// Here screen turned off
// Then switched on
D/MainActivity: onStart()
D/MainFragment: onStart()
// Main activity decided to kill itself
D/MainFragment: onStop()
D/MainFragment: onDestroyView()
D/MainFragment: onDestroy()
// No logged D/Presenter: Destroyed presenter, because isSavedState still true.
```

**Comment by dmdevgo** [comment]
We need to set this flag in onStart() and in onResume(), because the case is possible when the fragment is resumed after a pause. For example after displaying a permission dialog.

**Comment by Jeevuz** [comment]
Yes, @dmdevgo right. To be sure we need it in both.

**Comment by senneco** [comment]
Will be applied in near release

**Comment by senneco** [comment]
Ready in Moxy v1.4.5
