### ISSUE TITLE
Codegeneration for Inner classes extending from MvpView

### ISSUE THREAD

**Issue by jungornti** [Arello-Mobile/Moxy#75]
I have such interface:

```
public interface Contract {
    interface View extends MvpView {                                           
        void setLoadingIndicator(boolean active);                               
    }                                                                           
    interface Presenter {                                                       
        ...
    }                                                                       
}
```

Also, i have a presenter 

```
@InjectViewState                                                                
public class Presenter
        extends AbstractPresenter<Contract.View> implements Contract.Presenter {
```

When i  build project, the error occurs: it can not find variable "View" in the generated code for Contract$View$$ViewState class.

If i refactor Contract.View to simple ContractView interface, then everything works fine.

Is this my mistake or moxy does not support code generation for nested interfaces?

**Comment by senneco** [comment]
Hi, moxy doesn't support this approach. But it seems ok to do this. Will be done in some near release ;)

**Comment by jungornti** [comment]
That's great, because it is very nice to have the class, defining the view/presenter contract (as adviced by google android architecture samples).

Thanks! I will leave this issue open, if you don't mind.

**Comment by senneco** [comment]
This is published in version 1.4.6.

**Comment by jungornti** [comment]
That is just great, thank you very much!

**Comment by c0defather** [comment]
Hi, this works in 1.4.6, but fails in 1.5.5. Would you mind to fix this? Thanks!

**Comment by s-ilnar** [comment]
Copy paste^) Hi, this works in 1.4.6, but fails in 1.5.5. Would you mind to fix this? Thanks!

```
    implementation 'tech.schoolhelper:moxy-x:1.7.0'
    annotationProcessor 'tech.schoolhelper:moxy-x-compiler:1.7.0'
    implementation 'tech.schoolhelper:moxy-x-androidx:1.7.0'
```
