### ISSUE TITLE
Orientation change - last method from presenter is called 

### ISSUE THREAD

**Issue by candeiasdan** [Arello-Mobile/Moxy#78]
I created a simple example with Moxy, and I noticed that once the device changes orientation the last method from presenter is called once again. 
Example: layout with one TextView and one Button. Once the view is created my presenter modifies the text on TextView. Then when i click on the button the view shows a Toast. If now I rotate the device the Toast shows again, and now after each rotation the Toast is appearing.

This is the sample I have to reproduce this problem:

TestActivity:
```
public class TestActivity extends MvpAppCompatActivity implements TestView {

    @InjectPresenter
    TestPresenter presenter;
    private ActivityTestBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = DataBindingUtil.setContentView(this, R.layout.activity_test);
        binding.button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                presenter.onButtonClick();
            }
        });
        presenter.onViewCreated();
    }

    @Override
    public void showToast(String message) {
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show();
    }

    @Override
    public void setText(String str) {
        binding.text.setText(str);
    }
}
```

TestView:
```
public interface TestView extends MvpView {

    void showToast(String message);

    void setText(String str);
}
```

TestPresenter:
```
@InjectViewState
public class TestPresenter extends MvpPresenter<TestView> {
    void onViewCreated() {
        getViewState().setText("text set by presenter");
    }

    void onButtonClick(){
        getViewState().showToast("this is an error");
    }
}
```

**Comment by senneco** [comment]
Each command that apply to View also put in to commands queue, by default. But you have availability to manage strategy of save command to this queue. Apply annotation @StateStrategy to each command(or to full View interface).

In case of Toast, you can apply strategy like OneExecutionStrategy or SkipStrategy.

**Comment by candeiasdan** [comment]
It seems to do the trick.

The  wiki page [View State Strategy](https://github.com/Arello-Mobile/Moxy/wiki/View-commands-state-strategy) is empty, would be nice some description for each strategy with simple example ;)
