### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jjvargas** [Arello-Mobile/Moxy#8]
Any suggestion on how to test a project using this library?

**Comment by senneco** [comment]
Hello,

You can directly test each part of your MVP. You can mock presenters of your view. Then you can make simply integration tests. Also, you cam mock view and models of your presenter. and simply test your model. Then you will get simple unit tests.

Currently we do not write integration/unit tests. But we are on the plan to do so in the future. May be some one else could help you. Or you can ask more concrete questions. May be I will can help you.

**Comment by senneco** [comment]
@jjvargas, have you any more concrete questions?

**Comment by jjvargas** [comment]
It was more on the side of having already the sample unit/integration
tests.  I have not really experimented with the library but will do so in
the near future

**Comment by senneco** [comment]
@jjvargas good news! You can see example of testing in sample-github module 😄
