### ISSUE TITLE
Callback method called multiply times

### ISSUE THREAD

**Issue by lectricas** [Arello-Mobile/Moxy#80]
```
public void loadTeasers(int skip, boolean refresh, Category category) {
        getViewState().showProgress();

        Subscription s2 = ActiveAndroidHelper.getSources()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(teasers -> {
                    getViewState().onTeasersLoaded(teasers);
                    getViewState().hideProgress();
                }, this::onError);
        unsubscribeOnDestroy(s2);
    }
```
Suppose we have simple method which loads some data from network. I want to refresh my network data every onResume method.
And, in this case, on each call of loadTeasers(true, new Category()), the callback method onTeasersLoaded(teasers) is called N times, where N is the number of onResume methods (and loadTeasers) executed.
I think I need to unsubscribe and null the previous subsribition, but which method to use here?
Thanks

**Comment by senneco** [comment]
Well you can use this method to do it =) Just like this:

```java
Subscription loadTeasersSubscription;

public void loadTeasers(int skip, boolean refresh, Category category) {
        if (loadTeasersSubscription != null && !loadTeasersSubscription.isUnsubscribed()) {
                loadTeasersSubscription.unsubscribe();
        }

        getViewState().showProgress();

        loadTeasersSubscription = ActiveAndroidHelper.getSources()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(teasers -> {
                    getViewState().onTeasersLoaded(teasers);
                    getViewState().hideProgress();
                }, this::onError);

        unsubscribeOnDestroy(loadTeasersSubscription);
    }```

**Comment by lectricas** [comment]
@senneco Nope, this does not work. That was only a guess about necessity to unsubsribe. 
loadTeasersSubscription  is not null, but unsubsribed. 
I think the problem is somewhere else. 
Haven't you encountered this issue already??

**Comment by senneco** [comment]
It seems that I didn't understand what is your problem? Problim is that this method call each time after onResume, or problem that it's not? Or something else?

**Comment by A-Zaiats** [comment]
What strategy do you use for `onTeaserLoaded(teasers)` method? Was your view stopped before resume? Are you sure that `onTeaserLoaded(teasers)` method is called N times from `subsrciber#onNext` callback?

Looks like you use default strategy. So it can be following behavior:
- the View was stopped
- the View was detached from presenter
- the View was attached to the Presenter
- the ViewState restored state (called all `onTeaserLoaded(teasers)` that was called before)
- one more `onTeaserLoaded(teasers)` was called by `loadTeasers` callback

**Comment by lectricas** [comment]
I just call loadTeasers() each time my fragment executes OnResume method. 
And I get onTeaserLoaded(teasers) executed N times (over and over, after only single OnResume call). 
And this N grows every time Fragment executed OnResume method.
Suppose you have two fragments and you just moving to and fro between them. The first fragment has a presenter, where  loadTeasers() method is. 
So the strategy is the default one, just copied the code from the sample.

**Comment by senneco** [comment]
@lectricas it seems like bug is in your `ActiveAndroidHelper.getSources()`, or `onTeasersLoaded(teasers)` has `default` or `AddToEndStrategy`.  Try to annotate your `onTeasersLoaded(teasers)` method with annotation `@StateStrategy(AddToEndSingleStrategy.class)`.

**Comment by A-Zaiats** [comment]
Can you print some message to LogCat on `onTeaserLoaded(teasers)` callback? Something like that:
```java
public void loadTeasers(int skip, boolean refresh, Category category) {
        if (loadTeasersSubscription != null && !loadTeasersSubscription.isUnsubscribed()) {
                loadTeasersSubscription.unsubscribe();
        }

        getViewState().showProgress();

        loadTeasersSubscription = ActiveAndroidHelper.getSources()
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(teasers -> {
                    Log.d("TAG", "SOME MESSAGE THERE")
                    getViewState().onTeasersLoaded(teasers);
                    getViewState().hideProgress();
                }, this::onError);

        unsubscribeOnDestroy(loadTeasersSubscription);
    }
```
 Then check how much it will be printed. If it will be printed just once so it is a view state restoring but not onTeaserLoaded(teasers) callback.

**Comment by lectricas** [comment]
@senneco 
LogCat.  
```
D/MyInteger: startLoadingInFragment 
D/MyInteger: subscribeInPresenter 
D/MyInteger: CallBackInFragment:1
D/MyInteger: startLoadingInFragment
D/MyInteger: CallBackInFragment:1
D/MyInteger: subscribeInPresenter
 D/MyInteger: CallBackInFragment:1
D/MyInteger: startLoadingInFragment
 D/MyInteger: CallBackInFragment:1
D/MyInteger: CallBackInFragment:1
 D/MyInteger: subscribeInPresenter
 D/MyInteger: CallBackInFragment:1
D/MyInteger: startLoadingInFragment
D/MyInteger: CallBackInFragment:1
 D/MyInteger: CallBackInFragment:1
 D/MyInteger: CallBackInFragment:1
 D/MyInteger: subscribeInPresenter
D/MyInteger: CallBackInFragment:1
```

```
public void testInteger() {
        getViewState().showProgress();
        s3 = Observable.just(1)
        .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(integer -> {
                    Log.d("MyInteger", "subscribeInPresenter");
                    getViewState().integerTest(integer);
                    getViewState().hideProgress();
                }, this::onError);
        unsubscribeOnDestroy(s3);
    }
```
Seems like callback method is called by its own. Presenter calls callback method correctly - single time on each subscribe.

**Comment by senneco** [comment]
@lectricas could you provide me your MvpView interface?

**Comment by lectricas** [comment]
@senneco 
```
public interface BaseNewsViewState extends BaseViewState {
    void onTeasersLoaded(List<Teaser> teasers);
    void onTeasersQueried(List<Teaser> teasers);
    void onCurrencyLoaded(CurrencyRequestAnswer currencyAnswer);
    void integerTest(Integer integer);
}
```

```
public interface BaseViewState extends MvpView {
    void hideProgress();
    void showProgress();
    void onError(Throwable throwable);
}
```

**Comment by senneco** [comment]
@lectricas try to apply AddToEndStrategy, like this:

```java
@StateStrategy(AddToEndSingleStrategy.class)
public interface BaseNewsViewState extends BaseViewState {
    void onTeasersLoaded(List<Teaser> teasers);
    void onTeasersQueried(List<Teaser> teasers);
    void onCurrencyLoaded(CurrencyRequestAnswer currencyAnswer);
    void integerTest(Integer integer);
}
```

**Comment by lectricas** [comment]
@senneco 
```
D/MyInteger: startLoadingInFragment
D/MyInteger: CallBackInFragment:1
D/MyInteger: subscribeInPresenter
D/MyInteger: CallBackInFragment:1
D/MyInteger: startLoadingInFragment
D/MyInteger: CallBackInFragment:1
D/MyInteger: subscribeInPresenter
D/MyInteger: CallBackInFragment:1
D/MyInteger: startLoadingInFragment
D/MyInteger: CallBackInFragment:1
D/MyInteger: subscribeInPresenter
D/MyInteger: CallBackInFragment:1
```

Better now, but first callback is kinda redundant.

**Comment by A-Zaiats** [comment]
I think `SkipStrategy.class` will be better. 
If View is valid, callback will be called. If no, presenter reload data on resume.

**Comment by lectricas** [comment]
@A-Zaiats 
woohoo
works as desired. Thanks.
