### ISSUE TITLE
Want my request to wait untill views are inflated.

### ISSUE THREAD

**Issue by lectricas** [Arello-Mobile/Moxy#84]
So, I have a fragment

```
public class ExampleFragment extends Fragment {

    @InjectPresenter
    ExamplePresenter presenter;
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        
        View view =  inflater.inflate(R.layout.fragment_example, container, false);
        //butterknife it!
        //here is the place when we can populate our UI.
        presenter.makeSomeNetworkRequest();
        return view;
    }
}
```
And I want to run 
```
@Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        presenter.makeSomeNetworkRequest();
    }
```
then wait untill all my views are inflated(untill onCreateView is executed) and then bring the result back to the Fragment and populate the UI. Is it possible?
I want it so, because I don't wanna wait untill my fragment is created and also I want to clean onCreateView a little bit. 
Thanks.

**Comment by terrakok** [comment]
Usually you must do it in presenter.onFirstViewAttach().
This method will be called in super.onStart().

Or, for specific case, you can start request in presenter constructor. But it is dangerous because it is not evidently.
