### ISSUE TITLE
Add possibility to inject MvpDelegate during unit tests

### ISSUE THREAD

**Issue by storix** [Arello-Mobile/Moxy#86]
Hi, guys,

I've encountered an issue when trying to run my unit tests for an `Activity` which extents `MvpAppCompatActivity`. I'm using JUnit 4.12 and Robolectric 3.2.2 and the following exception is being thrown:
> java.lang.NoClassDefFoundError: com/arellomobile/mvp/MoxyReflector

So I've copied the source code of `MvpAppCompatActivity` and injected [mMvpDelegate](https://github.com/Arello-Mobile/Moxy/blob/master/moxy-app-compat/src/main/java/com/arellomobile/mvp/MvpAppCompatActivity.java#L16) manually. All tests passed. Obviously, it would be great to have the ability to inject this delegate using a setter or the like. 

I am not making a pull request because, I'm sure, you, as the authors, can choose the more appropriate design pattern for this.

**Comment by senneco** [comment]
Hi,

You can override method getMvpDelegate inside your test, and then return your custom Delegate. But it seems that there is some error, because test must see the generated MoxyReflector. Does it ok in debug/release run?

**Comment by storix** [comment]
Ok, thank you for the reply. Initially I thought it isn't supposed to work for test variants. That's why I just tried to mock out the `MvpDelegate`. However, I finally managed to solve this issue. Here is what I did (maybe this will help someone): File -> Invalidate Caches / Restart. Now everything's working fine.

Thank you for the library!
