### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by CherryPerry** [Arello-Mobile/Moxy#9]
Можете вести ченджлог по версиям? А то что-то обновляется, а что именно непонятно.

**Comment by senneco** [comment]
А не удобней пользоваться [страницей](https://github.com/Arello-Mobile/Moxy/releases) с описанием релизов? Некоторые я упустил, но в них не было ничего критичного. Или очень хочется именно такой файлик?

**Comment by xanderblinov** [comment]
Changelog available at [release history page](https://github.com/Arello-Mobile/Moxy/releases)

(I've just translated @senneco answer)
