### ISSUE TITLE
Presenter onDestroy()

### ISSUE THREAD

**Issue by mradzinski** [Arello-Mobile/Moxy#92]
Hi, quick question:

In which situations does ```onDestroy()``` method in the presenters gets called? I have local presenters injected using the ```@InjectPresenter``` annotation and I've never seen the presenters being destroyed, not even after my Activity/Fragment ```onDestroy()``` gets called.

**Comment by senneco** [comment]
Hi,

It gets called when activity/fragment go out from back stack. For example, when you finish activity, or navigate back within back stack of activity/fragments.
