### ISSUE TITLE
Integration with Conductor

### ISSUE THREAD

**Issue by mradzinski** [Arello-Mobile/Moxy#94]
Hi,

Is it possible to integrate Moxy with [Bluelinelabs Conductor](https://github.com/bluelinelabs/Conductor)? I've been checking the Wiki for how to do this and the closer implementation I found has been to integrate Moxy as it was a custom view (using MvpDelegate), but no idea if this is the best way of doing so.

**Comment by garmax1** [comment]
I used this class and it works fine
`public abstract class MoxyController extends ButterKnifeController {
    private MvpDelegate<? extends MoxyController> mMvpDelegate;

    protected MoxyController() {
        super();
        this.getMvpDelegate().onCreate();
    }

    protected MoxyController(Bundle args) {
        super(args);
        this.getMvpDelegate().onCreate(args);
    }

    @Override
    protected void onAttach(@NonNull View view) {
        super.onAttach(view);
        this.getMvpDelegate().onAttach();
    }

    @Override
    protected void onDetach(@NonNull View view) {
        super.onDetach(view);
        this.getMvpDelegate().onDetach();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        this.getMvpDelegate().onDestroy();
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        this.getMvpDelegate().onSaveInstanceState(outState);
    }

    private MvpDelegate getMvpDelegate() {
        if (this.mMvpDelegate == null) {
            this.mMvpDelegate = new MvpDelegate<>(this);
        }

        return this.mMvpDelegate;
    }
}`

**Comment by mradzinski** [comment]
@garmax1, yeah, I ended up doing pretty much the same this morning. Thanks for sharing your work though! :metal:
