### ISSUE TITLE
Стресс тест для ViewCommands<View extends MvpView>

### ISSUE THREAD

**Issue by KaNcHeR** [Arello-Mobile/Moxy#95]
В сервисе происходит загрузка изображений, с передачей в презентер через EventBus  статусов загрузки изображений (в том числе и (стресс)прогресс). Была замечена следующая проблема:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.arellomobile.mvp.viewstate.ViewCommand.apply(com.arellomobile.mvp.MvpView)' on a null object reference`

Визуально вот так:

![1](https://cloud.githubusercontent.com/assets/16061591/23479753/b207cd56-feef-11e6-884f-7d33f64eae17.png)

Помогло вот такое, пришлось мастерить отдельный ViewState где указать кастомный ViewCommands. Вот его отличие от оригинала(одно из двух либо при объявлении Collections.synchronizedList(new ArrayList<>()), либо блоками):

![2](https://cloud.githubusercontent.com/assets/16061591/23480248/7bc839b8-fef1-11e6-91d6-7299f74ea63b.jpeg)

**Comment by senneco** [comment]
У меня возник один вопрос: какие стратегии у вас есть в интерфесе View, у которой происходит такая проблема? У меня есть подозрение, что у вас есть какая-то кастомная стратегия, которая в определенную позицию currentState выставляет null.

**Comment by KaNcHeR** [comment]
Кастомных нет. Общая для всех, OneExecutionStateStrategy.

**Comment by senneco** [comment]
Ну он в то же время довольно логичный, потому что команды во вью должны улетать только с главного потока. Есть подозрение, что так же, вместо синхронизированного списка, может помочь CopyOnWriteArrayList -- должно быть производительней

**Comment by KaNcHeR** [comment]
Кстати да, ты прав на счёт CopyOnWriteArrayList. Но и не с главного потока они улетали всё же, почти работало)
