### ISSUE TITLE
VIewState does not override annotations like @Nonnull

### ISSUE THREAD

**Issue by Yukooo** [Arello-Mobile/Moxy#97]
VIewState implementation  does not override annotations like @Nonnull for parameters in method, as a result the studio complains 
`interface DetailsView extends MvpView {
void renderModel(@Nonnull Item model)
}`

**Comment by senneco** [comment]
Is it fixed in https://github.com/Arello-Mobile/Moxy/pull/111 ? It seems that this PR is about this issue.

**Comment by senneco** [comment]
FYI, these PR was published at Moxy 1.5.0

**Comment by Yukooo** [comment]
@senneco  Thank you for your work!
